### ISSUE TITLE
Ask SQA to test CKF 1.9 with juju 3.6/beta

### ISSUE THREAD

**Issue by orfeas-k** [canonical/bundle-kubeflow#1011]
### Context

Ask SQA to test CKF 1.9 with juju 3.6 so we know early on if we hit issues with it.

### What needs to get done

Described title

### Definition of Done

SQA has scheduled/ran tests of CKF 1.9 on juju 3.6

**Comment by DnPlas** [comment]
I have asked SQA to start testing the bundle with [`ckf-1.9-stable`](https://github.com/canonical/bundle-kubeflow/blob/main/test-reference/versions.json#L2) test reference, which includes juju 3.6/beta. We should get the results we want from that test execution.

Closing this issue as the task is already done.
