### ISSUE TITLE
Explore the Istio and tls-operators cryptographic information

### ISSUE THREAD

**Issue by orfeas-k** [canonical/bundle-kubeflow#1020]
### Context

SSDL - Cryptography [epic](https://warthogs.atlassian.net/browse/KF-5509)

### What needs to get done

Pods in user-namespaces have Istio sidecars. There’s mTLS between Pods in user namespaces (between them, and IngressGateway). Questions we need to answer:
* For mTLS what libraries are used by sidecars?
* Is `istiod` distributing certificates to the `sidecar` charms?
* Has the Service Mesh team information about this?
* Is Istio-pilot `charm.py` using any crypto libraries?

### Definition of Done

We have enough information in order to document istio work with cryptographic libraries.

**Comment by mvlassis** [comment]
Together with @kimwnasptd we experimented on a Kubeflow deployment and examined the Istio documentation, here is the relevant information we have extracted:
- `istiod` distributes an `X.509` certificate to every sidecar charm, in the following path: `/var/run/secrets/istio/root-cert.pem`. The signature used is `sha256WithRSAEncryption`.
- Istio tunnels communication between services (a client and a server) using [Envoy proxies](https://www.envoyproxy.io/), which in our case are the sidecar containers that are injected in each pod in the user's namespace.
- When a workload container (**client**) sends a request to another workload container (**server**):
    - Istio re-routes the outbound traffic to the client's sidecar.
    - The client's sidecar starts an mTLS handshake with the server's sidecar.
    - The 2 sidecars establish an mTLS connection, and Istio forwards the traffic from the client to the server.
    - The server sidecar authorizes the request, and forwards the traffic to the backend service through local TCP connections.
- The minimum version of TLS used is `TLSv1_2`. The cipher suites used for the mTLS connection are:
    - `ECDHE-ECDSA-AES256-GCM-SHA384`
    - `ECDHE-RSA-AES256-GCM-SHA384`
    - `ECDHE-ECDSA-AES128-GCM-SHA256`
    - `ECDHE-RSA-AES128-GCM-SHA256`
    - `AES256-GCM-SHA384`
    - `AES128-GCM-SHA256`
- Our charm's code in `istio-pilot` does not perform any additional actions when it comes to cryptography between the sidecars. 

Main reference page: https://istio.io/latest/docs/concepts/security/#mutual-tls-authentication

**Comment by NohaIhab** [comment]
nice exploration @mvlassis ! 
A few comments:
1. What about the [`CertHandler`](https://github.com/canonical/istio-operators/blob/main/charms/istio-pilot/lib/charms/observability_libs/v1/cert_handler.py) and [`tls-certificates`](https://github.com/canonical/istio-operators/blob/main/charms/istio-pilot/lib/charms/tls_certificates_interface/v3/tls_certificates.py) libraries used by `istio-pilot` charm?
2. Did we get in touch with the Service Mesh team? I think it'll be valuable to have their input on this.

**Comment by orfeas-k** [comment]
To add to point 1, I had documented here https://github.com/canonical/bundle-kubeflow/issues/995#issuecomment-2277875882 what cryptography operations take place in those libraries and maybe we should mention that our charms uses those.

**Comment by mvlassis** [comment]
I'll update with more relevant information!

**Comment by mvlassis** [comment]
After contacting the Service Mesh team, they don't have anything else to add!
