### ISSUE TITLE
SSDLC exploration task Software Bill of Material

### ISSUE THREAD

**Issue by misohu** [canonical/bundle-kubeflow#1025]
### Context

We want to learn more what is the effort for the given epic https://warthogs.atlassian.net/browse/KF-5511

### What needs to get done

1. Explore details of this epic https://warthogs.atlassian.net/browse/KF-5511
2. Create all necessary tasks  needed to complete the epic 

### Definition of Done

1. Details documented in this issue 
2. Tasks created in Jira

**Comment by NohaIhab** [comment]
Discussed with the SSDLC team and the conclusion is:
* we'll use the fetch service tool released by the SSDLC team to generate SBOMs for the mlflow bundle, the kubeflow bundle, the resource-dispatcher charm, and the dss snap. the tasks created are #1062 , #1061 , https://github.com/canonical/resource-dispatcher/issues/65 and https://github.com/canonical/data-science-stack/issues/176
* mlflow bundle is our test SBOM, I have created it and requested a review from the team
* For the OCI images and rocks, we will write a script using `syft` to scan them, more details are in the task #1078 
* the SBOMs will be stored in our team's drive in a dedicated directory [SMOBs](https://drive.google.com/drive/folders/1rp3Iyn1PVhwTKEZDMJVSh0POgE-tIf4Q?usp=drive_link)
