### ISSUE TITLE
Create a terraform module for each charm 

### ISSUE THREAD

**Issue by NohaIhab** [canonical/bundle-kubeflow#1041]
### Context

According to the terraform modules organization spec, this is the first step to provide a terraform solution module. We need to create a terraform module for each charm.

### What needs to get done

For each charm in Charmed Kubeflow bundle and MLFlow bundle, create a terraform module that complies with the [spec](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit?usp=drivesdk).

### Definition of Done

All charms in CKF and MLFlow bundles have terraform modules in their repos.

**Comment by mvlassis** [comment]
Closing since we have now created individual tasks for each charm.
