### ISSUE TITLE
Write a tutorial for e2e wine UAT

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/bundle-kubeflow#1065]
### Context

We want to have a new tutorial that guides users on how to use a lot of components of Kubeflow, which should be the continuation of the first tutorial we have on spinning up CKF.

A very good candidate that showcases this is the wine e2e UAT, that we converted to work with 1.9 and KFP v2 
https://github.com/canonical/charmed-kubeflow-uats/issues/85

The above example guides users through:
- Creating a notebook
- Creating and running pipeline
- Storing the model in MLflow
- Serving it with KServe

### What needs to get done

1. Convert the UAT to a guide
2. Discuss with @afgambin on how to convert to a tutorial, and what language to use

### Definition of Done

1. The documentation is published in our public docs

**Comment by mvlassis** [comment]
Marking as done, the tutorial has been created and can be found in [this page](https://charmed-kubeflow.io/docs/explore-kubeflow).
