### ISSUE TITLE
Write a spec for Feast

### ISSUE THREAD

**Issue by misohu** [canonical/bundle-kubeflow#1079]
### Context

Based on the exploration task here https://github.com/canonical/bundle-kubeflow/issues/1064 We want to write a spec for feast bundle.

### What needs to get done

1. Write a spec for feast bundel

### Definition of Done

1. Spec is approved

**Comment by NohaIhab** [comment]
spec approved in `KF106`

**Comment by ACodingfreak** [comment]
Any plans about when we will have FEAST integration in kubeflow bundle ?
