### ISSUE TITLE
Update the docs for the NIMs how-to guide

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/bundle-kubeflow#1112]
### Context

This is a follow up from https://github.com/canonical/bundle-kubeflow/issues/1077

Once we've run the guide manually and agreed on how to run the NIMs on top of CKF, we should then create a how-to guide for deploying NIMs

### What needs to get done

1. Verify the manual steps for running NIMs
2. Coordinate with @afgambin on the content of the how-to and where to publish it
3. Write the guide

### Definition of Done

1. There is a how-to guide in CKF docs on how to deploy a NIM

**Comment by NohaIhab** [comment]
guide approved and published on https://charmed-kubeflow.io/docs/deploy-nvidia-nim-on-charmed-kubeflow
