### ISSUE TITLE
Create a common infrastructure for testing Spark

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/bundle-kubeflow#1164]
### Context

As part of the integration pulse to test Kubeflow<>Spark we will need to spin up some common infra to work together.

This could be either:
1. A VM, with necessary snaps (microk8s and spark-client)
2. EKS cluster

Then we'll also need to configure an S3 endpoint, that will be used from the Spark pods. My suggestion would be to go with a VM, as it can contain also spark snap in one place.

### What needs to get done

1. Setup central environment that multiple folks can access (i.e. VM with ssh keys)
2. Install K8s and have the spark-client snap available
3. Add users to the common environment
4. Configure some S3, which Pods in the cluster can access

### Definition of Done

1. An environment with K8s is deployed
2. The Spark credentials can be created in the Kubeflow user namespace
3. Pod in user namespace can put/pull files from S3

**Comment by NohaIhab** [comment]
AWS VM has been created and shared across participants
