### ISSUE TITLE
Validate we can run a Spark job from a Notebook

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/bundle-kubeflow#1165]
### Context

As part of our integration pulse we want to ensure that we can run Spark jobs from a Notebook.

We had done this in the Vancouver sprint and have some instructions on:
1. [gdoc](https://docs.google.com/document/d/1CVDXxJjewzaqCcuzs84_YrWVb23iPXcaLiyW52MYYD4/edit?tab=t.0#heading=h.cj1qhfv42uid)
2. [slides](https://docs.google.com/presentation/d/10eJLiKHdLPTx7BNFcXXo1ZPhZGg2LaJTAM7Ef4Fov3g/edit#slide=id.g658852891d_0_10)

We'll need to evaluate if those instructions are still adequate for 
* spinning up a notebook with jupyter-spark
* configuring the Istio ports (PodDefault) for communication between Notebook and worker pods
* using the ServiceAccount created from the spark snap
* get the results in the notebook pod

### What needs to get done

1. Run the steps of the hackathon
2. Document any issues from that approach

### Definition of Done

1. We know if the vancouver hackathon steps are still valid
2. If not, we have a list of issues

**Comment by NohaIhab** [comment]
The steps were validated and tested with `ghcr.io/canonical/charmed-spark-jupyterlab:3.4.2-4.0.11-22.04_edge` image, Notebook works as expected with Spark PodDefault and image.
