### ISSUE TITLE
Default image version  tensorflow-1.13.1-notebook-gpu does not work

### ISSUE THREAD

**Issue by aym-frikha** [canonical/bundle-kubeflow#123]
Hello the deafult notebook image version tensorflow-1.13.1-notebook-gpu does not work:

Error: context deadline exceeded
kubelet ip-172-31-55-47.ec2.internal
spec.containers{asdascxz}
1
2019-10-25T15:58 UTC
2019-10-25T15:58 UTC
warning
Error: failed to reserve container name "asdascxz_asdascxz-0_kubeflow_bd97f0d0-2dae-437a-938e-c5f0fdab78b8_0": name "asdascxz_asdascxz-0_kubeflow_bd97f0d0-2dae-437a-938e-c5f0fdab78b8_0" is reserved for "a76b7494613b2cb12c3238b47126f9067553c8c9db99b6130f93fb4917b8af0c"
kubelet ip-172-31-55-47.ec2.internal
spec.containers{asdascxz}
1
2019-10-25T15:58 UTC
2019-10-25T15:58 UTC
Container image "gcr.io/kubeflow-images-public/tensorflow-1.13.1-notebook-gpu:v0.5.0" already present on machine
kubelet ip-172-31-55-47.ec2.internal
spec.containers{asdascxz}
3
2019-10-25T15:58 UTC
2019-10-25T15:59 UTC
warning
Error: failed to reserve container name "asdascxz_asdascxz-0_kubeflow_bd97f0d0-2dae-437a-938e-c5f0fdab78b8_0": name "asdascxz_asdascxz-0_kubeflow_bd97f0d0-2dae-437a-938e-c5f0fdab78b8_0" is reserved for "8a2230b4c8ccd7f2a1afb3689d76ee0748b9d07336e14c60a25baa16f150a578"
kubelet ip-172-31-55-47.ec2.internal
spec.containers{asdascxz}

But it works with this image version tensorflow-1.9.0-notebook-gpu.

**Comment by DomFleischmann** [comment]
With this issue being almost 2 years old and us using new tensorflow images this issue will be close.

If you are able to reproduce this in the latest kubeflow bundle and the issue is still relevant feel free to reopen it.
