### ISSUE TITLE
Dex/OIDC fails to configure

### ISSUE THREAD

**Issue by grebennikov** [canonical/bundle-kubeflow#169]
First, the manual says to configure "public-url". Not sure what it will be for the extended cluster.
I assumed this is the address of the ambassador (<IP>.xip.io).
Configured public-url='http://<IP>.xip.io:80' for both dex-auth and oidc-gatekeeper.
Once both dex and oidc charms finished the config, oidc complaints:

time="2020-01-26T11:03:23Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: Get https://172.29.146.175.xip.io/dex/.well-known/openid-configuration: x509: certificate is valid for ingress.local, not 172.29.146.175.xip.io"

And obviously the ambassador doesn't allow to login, instead showing "OIDC Setup is not complete yet."

**Comment by knkski** [comment]
The "OIDC Setup is not complete yet." error message comes from using an old version of Ambassador that doesn't support the `bypass_auth` attribute.

**Comment by lwileczek-dmc** [comment]
So how does one get to the dashboard?

**Comment by jas042** [comment]
@lwileczek-dmc You can declare the 172.29.146.175.xip.io in your /etc/hosts point to valid public ip address and access. Now Im verify can I force to pass de HOST proxy header in Ingress entry for solve this.
