### ISSUE TITLE
MPI-Operator should be included into the bundle

### ISSUE THREAD

**Issue by grebennikov** [canonical/bundle-kubeflow#176]
According to the corporate user, MPI-Operator is a must when it comes to the distributed training and use of Horovod library.
Currently it is not a part of the bundle and never was.

**Comment by DomFleischmann** [comment]
@DnPlas is this something that is supported now with the new training-operator?

**Comment by DnPlas** [comment]
> @DnPlas is this something that is supported now with the new training-operator?

Unfortunately no, this component is still in Alpha status, and thus has not been added as part of the jobs the training-operator manages.
"Alpha means that the application is in the early phases of development and/or integration into Kubeflow." (See [Support](https://www.kubeflow.org/docs/started/support/#application-status))

**Comment by DnPlas** [comment]
Closing this issue as MPIJobs are now supported by the latest [training-operator](https://github.com/canonical/training-operator/blob/main/src/crds_manifests.yaml) in `latest/edge`.
