### ISSUE TITLE
CMR relation for keystone integration

### ISSUE THREAD

**Issue by aym-frikha** [canonical/bundle-kubeflow#188]
It would be nice to have charmed kubeflow connected to keystone through CMR. In a standard bare-metal charmed k8s deployment we typically use keystone for authentication service for k8s. It would be nice to use the same authentication service with Kubeflow instead of adding another authentication service like Dex to connect to LDAP. It will reduce management effort for administrators.

**Comment by DomFleischmann** [comment]
For now,  our priority is supporting LDAP and OIDC through Dex. Please go through the internal canonical channels if you want this feature in the future.
