### ISSUE TITLE
deploy fails on CDK 1.19

### ISSUE THREAD

**Issue by DavidSpek** [canonical/bundle-kubeflow#240]
After setting up a Charmed Kubernetes 1.19 cluster and manually adding it to juju and bootstrapping a controller (bootstrapping with juju 2.8.2 seems broken btw) I tried to deploy charmed Kubeflow. When running the command `python3 scripts/cli.py deploy-to juju-k8s --cloud k8s-cloud` everything seems to go smoothly but it exits with the following error:

```
DEBUG:root:pytorch-operator is lead by pytorch-operator/0
DEBUG:root:seldon-core is lead by seldon-core/0
DEBUG:root:tf-job-operator is lead by tf-job-operator/0
+ juju kubectl apply -f /tmp/tmpelzkkd4i
Error: ErrorMessage { msg: "Couldn\'t determine cloud substrate." }
Command '('juju', 'kubectl', 'apply', '-f', '/tmp/tmpelzkkd4i')' returned non-zero exit status 1.
```

I did not run the `python3 scripts/cli.py ck setup` command as it seems this will deploy and bootstrap a CDK cluster, which I already have. Looking through the script quickly I didn't see the setup command doing more that just creating a cluster and bootstrapping a controller.

**Comment by DavidSpek** [comment]
I doubt it is related but I am currently facing the following issue when trying to deploy Kubeflow with kfctl (which is why I decided to try charmed-kubeflow). 

https://github.com/kubeflow/manifests/issues/1543

**Comment by knkski** [comment]
Are you using the same controller for both CK and Kubeflow? I ask because the `juju kubectl` command relies on scp'ing `kubeconfig` from the `kubernetes-master/0` unit in the `default` model to work properly. If your setup looks different, it would be interesting to know what it looks like, so that `juju kubectl` could be made smarter.

At any rate, it should work for you if set up `~/.kube/config` properly to talk to CK, then change these 3 references to `run('kubectl', ...` instead of `juju('kubectl', ...`:

https://github.com/juju-solutions/bundle-kubeflow/blob/master/scripts/cli.py#L347
https://github.com/juju-solutions/bundle-kubeflow/blob/master/scripts/cli.py#L349
https://github.com/juju-solutions/bundle-kubeflow/blob/master/scripts/cli.py#L360

And then update these lines to be `'kubectl', ...` instead of `'juju', 'kubectl', ...`:

https://github.com/juju-solutions/bundle-kubeflow/blob/master/scripts/cli.py#L144
https://github.com/juju-solutions/bundle-kubeflow/blob/master/scripts/cli.py#L186
https://github.com/juju-solutions/bundle-kubeflow/blob/master/scripts/cli.py#L193
https://github.com/juju-solutions/bundle-kubeflow/blob/master/scripts/cli.py#L200

**Comment by DavidSpek** [comment]
I am not using the same controller for CK and Kubeflow. The model I am using for CK is not default but one I created (k8s). I did manually copy the config file with `juju scp kubernetes-master/0:config ~/.kube/config`. I will try with your mentioned edits in just a moment after my new kfctl deployment finishes failing. 

FYI, I did manage to resolve the issue with deploying istio on CK which requires `--service-account-issuer` and `--service-account-signing-key-file` to be set on the kube-apiserver. Initially I tried to use juju to configure the `api-extra-args` without succes (althought I think it should be possible to change this way). I SSH'ed into the master nodes and ran `sudo openssl rsa -in /root/cdk/serviceaccount.key -pubout -out /root/cdk/serviceaccount.pub` to generate the public key. Then I edited `/var/snap/kube-apiserver/current/args` and added `--service-account-issuer="kubernetes.default.svc" --service-account-signing-key-file="/root/cdk/serviceaccount.key"` and changed `--service-account-key-file="/root/cdk/serviceaccount.key"` to `--service-account-key-file="/root/cdk/serviceaccount.pub"`. Hopefully somebody can provide a proper or better way of setting the `--service-account-issuer` and `--service-account-signing-key-file` on CK (preferably something that can be configured in the deployment bundle).

**Comment by DavidSpek** [comment]
The error I was facing has been resolved with the edits you mentioned above. However I am getting stuck at:
`kubectl wait --namespace=kubeflow --for=condition=Ready pod --timeout=-1s --all`

The pipelines-viewer pod and the ambassador pod are having trouble. The pipelinesviewer pod is in crashbackloop with the following log:

```
W0915 15:12:00.553509       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
fatal error: mlock failed
runtime stack:
runtime.throw(0x12223db, 0xc)
	/usr/local/go/src/runtime/panic.go:1112 +0x72
runtime.mlockGsignal(0xc000602300)
	/usr/local/go/src/runtime/os_linux_x86.go:72 +0x107
runtime.mpreinit(0xc000700000)
	/usr/local/go/src/runtime/os_linux.go:341 +0x78
runtime.mcommoninit(0xc000700000)
	/usr/local/go/src/runtime/proc.go:630 +0x108
runtime.allocm(0xc00006e000, 0x12a4658, 0x0)
	/usr/local/go/src/runtime/proc.go:1390 +0x14e
runtime.newm(0x12a4658, 0xc00006e000)
	/usr/local/go/src/runtime/proc.go:1704 +0x39
runtime.startm(0x0, 0xc000426301)
	/usr/local/go/src/runtime/proc.go:1869 +0x12a
runtime.wakep(...)
	/usr/local/go/src/runtime/proc.go:1953
runtime.resetspinning()
	/usr/local/go/src/runtime/proc.go:2415 +0x93
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2527 +0x2de
runtime.park_m(0xc000102600)
	/usr/local/go/src/runtime/proc.go:2690 +0x9d
runtime.mcall(0x20000)
	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
goroutine 1 [runnable]:
k8s.io/apimachinery/pkg/api/meta.NewDefaultRESTMapper(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/api/meta/restmapper.go:81
k8s.io/client-go/restmapper.NewDiscoveryRESTMapper(0xc00015b800, 0x1c, 0x20, 0x1c, 0x20)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20180718001006-59698c7d9724/restmapper/discovery.go:94 +0x62a
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDiscoveryRESTMapper(0xc00016e000, 0xc, 0x1220956, 0xa, 0x12208ca)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.0.0-20181121180216-5558165425ef/pkg/client/apiutil/apimachinery.go:40 +0x9f
sigs.k8s.io/controller-runtime/pkg/manager.New(0xc00016e000, 0xc0000baf60, 0x12a47c8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffeea823f85, ...)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.0.0-20181121180216-5558165425ef/pkg/manager/manager.go:156 +0x112
main.main()
	/src/github.com/kubeflow/pipelines/backend/src/crd/controller/viewer/main.go:74 +0x36e
goroutine 6 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1bf3880)
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x26f
goroutine 25 [IO wait]:
internal/poll.runtime_pollWait(0x7f60138cd008, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc000128718, 0x72, 0x2700, 0x271f, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000128700, 0xc000500000, 0x271f, 0x271f, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000128700, 0xc000500000, 0x271f, 0x271f, 0x203000, 0x700c10, 0xc000188bb8)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000186040, 0xc000500000, 0x271f, 0x271f, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc0004c6740, 0xc000500000, 0x271f, 0x271f, 0x13e, 0x271a, 0xc00009f9c8)
	/usr/local/go/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc000188cd8, 0x139ede0, 0xc0004c6740, 0x40bc45, 0x10e3d80, 0x11dac60)
	/usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc000188a80, 0x13a0260, 0xc000186040, 0x5, 0xc000186040, 0x8)
	/usr/local/go/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc000188a80, 0x0, 0x0, 0xc00009fd38)
	/usr/local/go/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc000188a80, 0xc000494000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1233 +0x15b
bufio.(*Reader).Read(0xc000492360, 0xc000484118, 0x9, 0x9, 0xc00009fd38, 0x12a4800, 0x813b12)
	/usr/local/go/src/bufio/bufio.go:226 +0x24f
io.ReadAtLeast(0x139ec40, 0xc000492360, 0xc000484118, 0x9, 0x9, 0x9, 0xc0000a6060, 0x0, 0x139ef00)
	/usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc000484118, 0x9, 0x9, 0x139ec40, 0xc000492360, 0x0, 0x0, 0xc00059b080, 0x0)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20190827160401-ba9fcec4b297/http2/frame.go:237 +0x87
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0004840e0, 0xc00059b080, 0x0, 0x0, 0x0)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20190827160401-ba9fcec4b297/http2/frame.go:492 +0xa1
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00009ffa8, 0xc00008c7b0, 0x7e41b2)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20190827160401-ba9fcec4b297/http2/transport.go:1686 +0x8d
golang.org/x/net/http2.(*ClientConn).readLoop(0xc00018a480)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20190827160401-ba9fcec4b297/http2/transport.go:1614 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
	/go/pkg/mod/golang.org/x/net@v0.0.0-20190827160401-ba9fcec4b297/http2/transport.go:673 +0x64a
```

The ambassador pod shows `Readiness probe failed: Get "http://10.1.40.80:8877/ambassador/v0/check_ready": dial tcp 10.1.40.80:8877: connect: connection refused` with the following log:

```
2020-09-15 15:16:20 kubewatch [20 TMainThread] 0.50.0 INFO: kubewatch starting: mode 'sync' ambassador_config_dir '/ambassador/ambassador-config' envoy_config_file '/ambassador/envoy/envoy.json' debug 'False' delay '1.0' pid 'None'
2020-09-15 15:16:20 kubewatch [20 TMainThread] 0.50.0 INFO: namespace kubeflow, watching all namespaces
2020-09-15 15:16:20 kubewatch [20 TMainThread] 0.50.0 ERROR: couldn't read namespace kubeflow? (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'babf9967-a547-42bc-9e4b-1d5910260dff', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 15 Sep 2020 15:16:20 GMT', 'Content-Length': '329'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"default\" is forbidden: User \"system:serviceaccount:kubeflow:default\" cannot get resource \"namespaces\" in API group \"\" in the namespace \"default\"","reason":"Forbidden","details":{"name":"default","kind":"namespaces"},"code":403}
2020-09-15 15:16:20 kubewatch [20 TMainThread] 0.50.0 INFO: cluster ID is 07eb43c8-1166-5145-a060-45e4dd907e10 (from hardcoded ID)
2020-09-15 15:16:20 kubewatch [20 TMainThread] 0.50.0 WARNING: Kubernetes access failure! (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'fc78e7f2-be4d-40f2-bdda-c32534162832', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 15 Sep 2020 15:16:20 GMT', 'Content-Length': '287'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden: User \"system:serviceaccount:kubeflow:default\" cannot list resource \"services\" in API group \"\" at the cluster scope","reason":"Forbidden","details":{"kind":"services"},"code":403}
```

**Comment by Cynerva** [comment]
> Then I edited /var/snap/kube-apiserver/current/args and added --service-account-issuer="kubernetes.default.svc" --service-account-signing-key-file="/root/cdk/serviceaccount.key" and changed --service-account-key-file="/root/cdk/serviceaccount.key" to --service-account-key-file="/root/cdk/serviceaccount.pub".

Careful here, the charm or the snap will revert this change sooner or later.

You should be able to set this with api-extra-args on the charm. Something like this:

```
juju config kubernetes-master api-extra-args="service-account-issuer=kubernetes.default.svc service-account-signing-key=/root/cdk/serviceaccount.key service-account-key-file=/root/cdk/serviceaccount.pub"
```

**Comment by DavidSpek** [comment]
@Cynerva That would indeed make the changes persistent, however I doubt this setup will work from a bundle directly as `serviceaccount.pub` would need to be created.

**Comment by DomFleischmann** [comment]
@DavidSpek is this issue still relevant?
