### ISSUE TITLE
Memory warning also appears in Lite and Edge bundles

### ISSUE THREAD

**Issue by RFMVasconcelos** [canonical/bundle-kubeflow#260]
Kubeflow lite & edge is announced to be available for devices with less than 14Gb of RAM, but the warning is still there:

![image](https://user-images.githubusercontent.com/27001378/98275866-12220000-1f8d-11eb-9661-bc28f2febcb1.png)

**Comment by DomFleischmann** [comment]
This should be fixed by now. 

If you are able to reproduce this with the latest microk8s release please feel free to reopen this issue.
