### ISSUE TITLE
"microk8s enable kubeflow" command failing

### ISSUE THREAD

**Issue by xxl007** [canonical/bundle-kubeflow#276]
Hello, I have tried to deploy kubeflow on microk8s on a g4dn.2xlarge on AWS.

The command fails. See screenshot below.

![image](https://user-images.githubusercontent.com/232548/101347596-9caa9780-388a-11eb-836d-02ca9ab24389.png)

**Comment by knkski** [comment]
@xxl007: Can you run `microk8s inspect`, and attach the tarball here that it generates?
