### ISSUE TITLE
Documentation refers to a function that does not exist

### ISSUE THREAD

**Issue by VibratingPig** [canonical/bundle-kubeflow#277]
In https://github.com/juju-solutions/bundle-kubeflow/blob/master/README.md on line 120 it states

"Note that until https://github.com/kubeflow/pipelines/issues/1654 is resolved,
you will have to attach volumes to any locations that output artifacts are
written to, see the `attach_output_volume` function in
`pipline-samples/sequential.py` for an example."

Is this still true?  When I go to pipeline-samples/sequential.py i see no output volume function.

**Comment by knkski** [comment]
@VibratingPig: A better example would be the test pipelines, such as this one:

https://github.com/canonical/bundle-kubeflow/blob/master/tests/pipelines/cowsay.py

As far as I'm aware that is still true, but I will investigate and see if those volumes can be eliminated
