### ISSUE TITLE
katib service accounts are missing permissions/bindings

### ISSUE THREAD

**Issue by VariableDeclared** [canonical/bundle-kubeflow#292]
Hi,

When deploying Charmed Kubeflow on Charmed Kubernetes the katib-controller is unresponsive to HTTPS requests, checking the katib controller logs it is possible to observe multiple permission error logs e.g.

```
sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *unstructured.Unstructured: tfjobs.kubeflow.org is forbidden: User "system:serviceaccount:kubeflow:katibcontroller" cannot list resource "tfjobs" in API group "kubeflow.org" at the cluster scope
```

This causes the kubeflow pipeline tests to fail.

[Workaround]

As a quick workaround the `katib-ui` and `katib-controller` need a new rolebinding created with appropriate permissions, this can either be done by binding the two service accounts to an existing policy of creating a new one from the error logs.

Thanks!
Peter

**Comment by knkski** [comment]
Fixed by https://github.com/kubeflow/katib/pull/1426
