### ISSUE TITLE
Can't access the Kubeflow dashboard with http://10.64.140.43.xip.io

### ISSUE THREAD

**Issue by AdeloreSimiloluwa** [canonical/bundle-kubeflow#301]
Currently working on with Ubuntu vm in windows.  I ran the following codes and kubeflow was successfully installed but I cant access the kubeflow dashboard with `http://10.64.140.43.xip.io`

    1) sudo snap install microk8s --classic --channel=latest/edge
    2) sudo microk8s status --wait-ready
    3) sudo usermod -a -G microk8s $USER
    4) sudo chown -f -R $USER ~/.kube
    5) microk8s.enable dns dashboard storage
    6) microk8s.enable kubeflow --bundle=lite
    7) choose a password
    8) microk8s.kubectl get all --all-namespaces
    9) http://10.64.140.43.xip.io

![dasss](https://user-images.githubusercontent.com/62348760/105926602-56fb8700-6010-11eb-85be-6d3eef6d7d4a.PNG)

![err](https://user-images.githubusercontent.com/62348760/105926623-6084ef00-6010-11eb-8311-8c4cadbfa7cc.PNG)

**Comment by knkski** [comment]
@AdeloreSimiloluwa: Since you're running MicroK8s inside a VM, connecting to the dashboard will be a little trickier. The easiest way is to connect via a SOCKS proxy as detailed here:

https://charmed-kubeflow.io/docs/dashboard

**Comment by AdeloreSimiloluwa** [comment]
@knkski , thank you. I tried  `ssh -D 9999 ubuntu@<machine_public_ip>` but I got permission denied error (public key).

**Comment by knkski** [comment]
@AdeloreSimiloluwa: Depending on how you've set up your VM, you may need to change that command. If you haven't yet, you'll need to include your SSH key in the `~/.ssh/authorized_keys` file in the VM.

**Comment by AdeloreSimiloluwa** [comment]
I am  not getting this how to work with this @knkski , I get a directory error

**Comment by RFMVasconcelos** [comment]
This issue is outdated.
