### ISSUE TITLE
tests/test_pipelines.py::test_pipelines[jupyter-params3-jupyter_pipeline] fails with 404

### ISSUE THREAD

**Issue by jhobbs** [canonical/bundle-kubeflow#316]
This test is failing, and the only output is "404 page not found"

This is kubeflow deployed on top of CK on aws.

https://solutions.qa.canonical.com/testruns/testRun/12abd4e4-0645-4176-9cb5-ddf4c2b809ec

**Comment by knkski** [comment]
@jhobbs: Sorry, this got lost the the email shuffle. Does this still happen / does it happen consistently?

**Comment by genet022** [comment]
@knkski Sorry its been a month since we've properly done a Kubeflow deploy. We just ran into this 5 times in a row. Here's a sample run:
https://solutions.qa.canonical.com/testruns/testRun/937d4021-44b1-4f42-a45e-555833b048d2
