### ISSUE TITLE
katib test fails with "b'no matches for kind "Experiment" in version "kubeflow.org/v1alpha3"\n'"

### ISSUE THREAD

**Issue by jhobbs** [canonical/bundle-kubeflow#320]
This is on CK on AWS. It fails every time.

pod logs from failed test:
https://paste.ubuntu.com/p/CKKHsvHswR/

failed test run output:
https://paste.ubuntu.com/p/t34jxbczmw/

juju status:
https://paste.ubuntu.com/p/RgDFhWKxtm/

k8s crashdump with more pod logs etc:
http://people.canonical.com/~jhobbs/juju-crashdump-kubernetes-2021-02-25-15.39.27.tar.gz

**Comment by knkski** [comment]
In the short term, you should be able to redeploy the katib-controller to get it working. Longer term, this issue is tracking updating the katib operators, which should fix this issue:

https://github.com/kubeflow/katib/issues/1453

**Comment by DomFleischmann** [comment]
The operators have been updated and this issue should be resolved.
