### ISSUE TITLE
Error getting Artifacts on running a pipeline

### ISSUE THREAD

**Issue by RFMVasconcelos** [canonical/bundle-kubeflow#321]
![Screenshot from 2021-02-26 14-14-05](https://user-images.githubusercontent.com/27001378/109310879-ffce1980-783c-11eb-80d7-41b35a658b23.png)

**Comment by RFMVasconcelos** [comment]
cc @knkski

**Comment by RFMVasconcelos** [comment]
This happens for example pipelines (in this case conditional), when you click on one pipeline component

![Screenshot from 2021-02-26 15-27-58](https://user-images.githubusercontent.com/27001378/109319924-593b4600-7847-11eb-9bdb-e26a03ff1127.png)

**Comment by Ursanon** [comment]
related with #338
