### ISSUE TITLE
most tests are failing to connect to localhost

### ISSUE THREAD

**Issue by asbalderson** [canonical/bundle-kubeflow#331]
on a deployment of  cs:kubeflow on k8s on top of aws.
5 out of 9 tests fail, and 2 out of 9 tests error.

most tests are showing that they fail to connect to 127.0.0.1
the selenium tests cant seem to find something called "geckodriver"

FAILED tests/test_kubectl.py::test_running_full - AssertionError: assert {'ad...
FAILED tests/test_pipelines.py::test_pipelines[mnist-params0-mnist_pipeline]
FAILED tests/test_pipelines.py::test_pipelines[cowsay-params1-cowsay_pipeline]
FAILED tests/test_pipelines.py::test_pipelines[katib-params2-katib_pipeline]
FAILED tests/test_pipelines.py::test_pipelines[jupyter-params3-jupyter_pipeline]
ERROR tests/test_selenium.py::test_login - selenium.common.exceptions.WebDriv...
ERROR tests/test_selenium.py::test_notebook - selenium.common.exceptions.WebD...

one testrun can be found at
https://solutions.qa.canonical.com/testruns/testRun/84121012-f507-4123-8cc7-b91e12d6cf51

with logs and crashdumps at
https://oil-jenkins.canonical.com/artifacts/84121012-f507-4123-8cc7-b91e12d6cf51/index.html

**Comment by knkski** [comment]
@asbalderson: Can you run `sudo apt install firefox-geckodriver`? It needs to be better documented, but here's where we install any necessary apt packages for the CI tests:

https://github.com/canonical/bundle-kubeflow/blob/master/.github/workflows/test-microk8s.yaml#L186

**Comment by asbalderson** [comment]
ahh yeah the extra depends resolved it
