### ISSUE TITLE
Err installing Kale on Kubeflow on MicroK8s 

### ISSUE THREAD

**Issue by RFMVasconcelos** [canonical/bundle-kubeflow#334]
Steps to bug:
1. Install `kubeflow-lite` on MicroK8s 
2. Start a Jupyter notebook server on Kubeflow dashboard
3. Connecting to notebook server
4. Open a new terminal on that server
5. Type [first step to install kale](https://github.com/kubeflow-kale/kale) - `pip install kubeflow-kale`

ERR below:

![Screenshot from 2021-03-09 09-47-07](https://user-images.githubusercontent.com/27001378/110451826-80520d00-80bc-11eb-9b6b-433ffd100674.png)
![Screenshot from 2021-03-09 09-47-30](https://user-images.githubusercontent.com/27001378/110451830-81833a00-80bc-11eb-99ff-faf4afb5dc92.png)

**Comment by RFMVasconcelos** [comment]
@knkski @DomFleischmann am I doing something incorrectly?

**Comment by DomFleischmann** [comment]
Did you use JupyterNotebook version 2 or the older one for the Notebook
Server?

According to this
<https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag>
it
seems to be some issue with the version of the enum module.

Dominik Fleischmann

Software Engineer

Mobile: +34 633 06 77 99 (Spain)

Email: dominik.fleischmann@canonical.com

**Comment by RFMVasconcelos** [comment]
I've chosen the latest TF cpu image from the default options:
![Screenshot from 2021-03-09 11-42-50](https://user-images.githubusercontent.com/27001378/110465647-99fb5080-80cc-11eb-9633-1713f0f92833.png)

**Comment by RFMVasconcelos** [comment]
@DomFleischmann

**Comment by knkski** [comment]
@RFMVasconcelos: Can you try running `pip uninstall -y enum34`? It looks like that package can conflict with the version from the standard library.

**Comment by RFMVasconcelos** [comment]
![Screenshot from 2021-03-09 18-35-18](https://user-images.githubusercontent.com/27001378/110520335-3aba3200-8106-11eb-978d-05c324024e27.png)

**Comment by RFMVasconcelos** [comment]
@knkski

**Comment by RFMVasconcelos** [comment]
If I try to `sudo uninstall` asks for the password for `jovyan`

**Comment by RFMVasconcelos** [comment]
https://github.com/jupyter/docker-stacks/issues/408 which seems to be a whole topic

**Comment by RFMVasconcelos** [comment]
Retested this on a fresh Ubuntu server instance on AWS, same outcome.

**Comment by DomFleischmann** [comment]
We now have instructions on how to use Kale [here](https://charmed-kubeflow.io/docs/kubeflow-basics)
