### ISSUE TITLE
Kubeflow - 'Cannot load dashboard menu link'

### ISSUE THREAD

**Issue by RFMVasconcelos** [canonical/bundle-kubeflow#348]
Installed `kubeflow-lite` via `juju deploy` and accessing the dashboard only home appears:

![Screenshot from 2021-04-29 12-29-05](https://user-images.githubusercontent.com/27001378/116537457-8c04c780-a8e6-11eb-8b9d-1bea9fe33a64.png)

**Comment by RFMVasconcelos** [comment]
cc @knkski @DomFleischmann

**Comment by RFMVasconcelos** [comment]
Same happening on deploying the whole Kubeflow bundle

**Comment by RFMVasconcelos** [comment]
According to [slack discussion](https://kubeflow.slack.com/archives/CQHMK8F09/p1619541727022000), creating this [configmap](https://github.com/kubeflow/manifests/blob/master/apps/centraldashboard/upstream/base/configmap.yaml) might solve it

**Comment by DomFleischmann** [comment]
This should be fixed now
