### ISSUE TITLE
Kubeflow Dashboard -  HTTP Error 403 Forbidden

### ISSUE THREAD

**Issue by ChrisEdel** [canonical/bundle-kubeflow#354]
Hi!

We followed this installation guide: https://ubuntu.com/tutorials/deploy-kubeflow-ubuntu-windows-mac#1-overview
In addition, we had to find this fix to access the dashboard: https://github.com/canonical/bundle-kubeflow/issues/344#issuecomment-827936799

The strange thing is, it already worked, we already started a jupyter Notebook last Friday (30.4.2021). Actually, it worked on two different servers managed by us. 
And now suddenly we get `HTTP Error 403 Forbidden` on both servers (which are completely independent from each other!) when trying to access the Kubeflow dashboard (without touching the servers in between). All the pods are active and running, we tried different versions of `microk8s`, we tried completely reinstalling it and we also tried other installation guides (https://www.kubeflow.org/docs/distributions/microk8s/kubeflow-on-microk8s/), but nothing helped. We are running Ubuntu 20.04 and we are not even able to access the dashboard locally from the server (via `wget` for example), so in our opinion this shouldn't be a networking problem.

**Comment by onurgu** [comment]
I can confirm this. I have the same error.

**Comment by ChrisEdel** [comment]
Have you been able to resolve this issue? We‘re still working on it, but no luck so far!

**Comment by DomFleischmann** [comment]
It seems like `xip.io` is not available anymore, we are currently working on a fix.

**Comment by ChrisEdel** [comment]
Is there are workaround to just not use xip.io for a while locally?
That would help a lot!

**Comment by ChrisEdel** [comment]
Just in case anyone else is having this issue, the following installation guide (which apparently does not rely on `xip.io`) worked for us: https://github.com/kubeflow/manifests#install-with-a-single-command

**Comment by DomFleischmann** [comment]
Sorry, I didn't see the last question, if you just substitute `xip.io` with `nip.io` everything should work fine. We are currently working on changing our docs.

**Comment by mat-ej** [comment]
I have the same issue with dex-auth. I followed the documentation exactly to the dot:
[https://charmed-kubeflow.io/docs/install](https://charmed-kubeflow.io/docs/install)

only thing I changed in the tutorial is  the env variable for dex-auth KUBERNETES_POD_NAMESPACE according to this:
[https://github.com/canonical/dex-auth-operator/pull/8](https://github.com/canonical/dex-auth-operator/pull/8)

-All the services, pods, deployments running



for the dex-auth public-url i used the same ip as in the tutorial:
URL = 10.64.140.43.nip.io
juju config dex-auth public-url=http://URL
juju config oidc-gatekeeper public-url=http://URL

I can access the istio-ingressgateway and see the dex-auth login page

![Screenshot at 2021-05-10 12-34-47](https://user-images.githubusercontent.com/10036980/117663399-ecc2b880-b1a0-11eb-9a31-82448a43d3fe.png)

but after the login I get http 403 error:
![Screenshot at 2021-05-08 09-11-31](https://user-images.githubusercontent.com/10036980/117663441-f51af380-b1a0-11eb-9bf3-a3b89f932a19.png)

I do not see any errors in any of the pods that I have checked.

microk8s inspection report:
[inspection-report-20210510_145215.tar.gz](https://github.com/canonical/bundle-kubeflow/files/6452300/inspection-report-20210510_145215.tar.gz)

**Comment by DomFleischmann** [comment]
@mat-ej there was an additional issue with dex-auth that should be fixed now in the latest bundle. To get that one please follow the instructions you mentioned on https://charmed-kubeflow.io/docs/install but using this command in the deploy step:
`juju deploy cs:kubeflow-lite` or `juju deploy cs:kubeflow` for the full bundle.

**Comment by sudopedia** [comment]
I have installed microk8s successfully on an Ubuntu AWS Instance and enabled kubeflow as well.
The dashboard credentials are displayed.
Have tunneled my way to port 9999, using SSH.

When trying to access the kuberflow dashboard IP, the webpage (Dashboard) doesn't load up and throws a 403 error.

How can I fix this issue so I can access my dashboard? Any help and assistance is appreciated.
Regards.

**Comment by DomFleischmann** [comment]
There was an issue with dex-auth that has been fixed in the latest bundle which is available on the `latest/edge` microk8s channel

**Comment by sudopedia** [comment]
> There was an issue with dex-auth that has been fixed in the latest bundle which is available on the `latest/edge` microk8s channel

So we tried the latest/edge microk8s channel.
All the pods seem to be running correctly. The URL http://10.64.140.43.nip.io/ has generated again. When accessing the URL, the login page loads correctly. After the credentials are entered, the page goes blank again and encounters '403' error.

Any advice on overcoming this?
Regards.

**Comment by brettkoonce** [comment]
You might consider upgrading to 1.3: https://github.com/ubuntu/microk8s/issues/2253#issuecomment-838158746
