### ISSUE TITLE
Kubeflow Dashboard - 403 Forbidden

### ISSUE THREAD

**Issue by ajith05** [canonical/bundle-kubeflow#358]
Hi

We followed the documentation given [here](https://www.kubeflow.org/docs/distributions/microk8s/kubeflow-on-microk8s/) to install kubeflow. We were not able to access the dashboard using the url provided in the output which is http://10.64.140.43.xip.io. We got to know from #354 that `xip.io` is not working and we should try `nip.io`. With `nip.io`, we are getting 403 Forbidden error. We are not even able to access login page. Below is the screenshot.
![image](https://user-images.githubusercontent.com/21294096/117958139-5b864a00-b338-11eb-992a-e4df5cc507b8.png)

Please let me know how I can fix this issue. Any help is appreciated.

Thanks.

**Comment by DomFleischmann** [comment]
There was an issue with dex-auth that has been fixed in the latest bundle which is available on the `latest/edge` microk8s channel. Please install that one.

**Comment by ajith05** [comment]
Hi! I tried installing microk8s on `latest/edge` channel as you said. I am able to see the login page as below
![image](https://user-images.githubusercontent.com/21294096/117980293-72856600-b351-11eb-998f-52e8f907f43d.png)

But after login it is giving 403 error code again.
![image](https://user-images.githubusercontent.com/21294096/117980446-9779d900-b351-11eb-838f-76e15e0043b7.png)

**Comment by brettkoonce** [comment]
See also #354.

You might consider upgrading to 1.3: https://github.com/ubuntu/microk8s/issues/2253#issuecomment-838158746

**Comment by ajith05** [comment]
> You might consider upgrading to 1.3
Do you mean microk8s or kubeflow?

As far as I am aware, there is no microk8s v1.3, correct me if I am wrong.

If you mean kubeflow, please let me know how I can choose/upgrade kubeflow version using microk8s method.

**Comment by brettkoonce** [comment]
@ajith05 kubeflow, see the link in my comment above!
