### ISSUE TITLE
Implementing new Katib UI 

### ISSUE THREAD

**Issue by RFMVasconcelos** [canonical/bundle-kubeflow#363]
The v1.3 Kubeflow Katib UI has a different image it might be worth moving to the latest image when possible.

![Screenshot from 2021-05-26 17-38-07](https://user-images.githubusercontent.com/27001378/119698457-2bb36800-be49-11eb-8855-d5cf097744cd.png)

**Comment by DomFleischmann** [comment]
I'm not sure if the screenshot you posted is the outdated UI or how the new one should look. There seems to be a new UI but it doesn't seem to have feature parity with the old one yet. More info [here](https://www.kubeflow.org/docs/components/katib/hyperparameter/#the-new-katib-ui).

If you were expecting the new UI, in my opinion I think we are fine with the old UI for this release and we could change to the newer one once they have feature parity.

**Comment by RFMVasconcelos** [comment]
I see! My intent with this issue was to discuss when we should move to the new Katib UI. Given that feature parity is not there yet, it looks like we might want to delay the move.

Let's perhaps keep this issue to track the change.

**Comment by DomFleischmann** [comment]
This will be released with 1.4
