### ISSUE TITLE
Logout button causes crash loop

### ISSUE THREAD

**Issue by RFMVasconcelos** [canonical/bundle-kubeflow#364]
When you click logout on the dashboard it loops and does not load any page.

![Screenshot from 2021-05-26 17-43-54](https://user-images.githubusercontent.com/27001378/119699434-1428af00-be4a-11eb-88b3-e6310c45e78d.png)

**Comment by Barteus** [comment]
Hi team, do we know when this is fixed and in which upstream ticket? Based on the upstream issue statuses this should be fixed. I have a current solution deployed and its not working.

**Comment by i-chvets** [comment]
@Barteus Is this the one? https://github.com/kubeflow/kubeflow/issues/5704

**Comment by i-chvets** [comment]
This claims that it is fixed, but comments in it state otherwise:
https://github.com/kubeflow/kubeflow/issues/6372

**Comment by i-chvets** [comment]
Another issue claiming the fix https://github.com/kubeflow/kubeflow/pull/5174

**Comment by i-chvets** [comment]
Launchpad https://bugs.launchpad.net/kubeflow-bundle/+bug/1999888

**Comment by i-chvets** [comment]
Need to see if it is resolved in 1.7

**Comment by DomFleischmann** [comment]
This issue should be interesting to fix this: https://github.com/kubeflow/kubeflow/pull/6609

**Comment by ca-scribner** [comment]
And also this: https://github.com/kubeflow/kubeflow/issues/6940
