### ISSUE TITLE
x509 err - Kubeflow Deployment

### ISSUE THREAD

**Issue by KYUNGSOO-LEE** [canonical/bundle-kubeflow#369]
run command:
   #) juju deploy cs:kubeflow-lite

err below:
   **ERROR cannot resolve charm URL "cs:kubeflow-lite": cannot get "/kubeflow-lite/meta/any?include=id&include=supported-series&include=published": Get "https://apiow-lite/meta/any?include=id&include=supported-series&include=published": x509: certificate signed by unknown authority**

I updated my certification. when I run command ( **"curl https://api.jujucharms.com/charmstore/v5/kubeflow-lite/meta/any?include=id&include=supported-series&include=published"**). I got the response. (**{"Id":"cs:bundle/kubeflow-lite-53","Meta":{"id":{"Id":"cs:bundle/kubeflow-lite-53","Series":"bundle","Name":"kubeflow-lite","Revision":53}}}**)

How to solve x509 error issue?

**Comment by KYUNGSOO-LEE** [comment]
debug log :
juju deploy cs:kubeflow-lite --debug
10:49:15 INFO  juju.cmd supercommand.go:56 running juju [2.9.3 0 16f33363aae986b8775dd1f7e5b3782e274a045e gc go1.14.15]
10:49:15 DEBUG juju.cmd supercommand.go:57   args: []string{"/snap/juju/16337/bin/juju", "deploy", "cs:kubeflow-lite", "--debug"}
10:49:15 INFO  juju.juju api.go:78 connecting to API addresses: [10.233.36.39:17070]
10:49:16 DEBUG juju.api apiclient.go:618 starting proxier for connection
10:49:16 DEBUG juju.api apiclient.go:622 tunnel proxy in use at localhost on port 37105
10:49:16 DEBUG juju.api apiclient.go:1149 successfully dialed "wss://localhost:37105/api"
10:49:16 INFO  juju.api apiclient.go:1051 cannot resolve "localhost": operation was canceled
10:49:16 INFO  juju.api apiclient.go:680 connection established to "wss://localhost:37105/api"
10:49:16 INFO  juju.juju api.go:78 connecting to API addresses: [10.233.36.39:17070]
10:49:16 DEBUG juju.api apiclient.go:618 starting proxier for connection
10:49:16 DEBUG juju.api apiclient.go:622 tunnel proxy in use at localhost on port 40139
10:49:16 DEBUG juju.api apiclient.go:1149 successfully dialed "wss://localhost:40139/model/e5bbed2b-be3f-4457-82cb-037e7e62c799/api"
10:49:16 INFO  juju.api apiclient.go:1051 cannot resolve "localhost": operation was canceled
10:49:16 INFO  juju.api apiclient.go:680 connection established to "wss://localhost:40139/model/e5bbed2b-be3f-4457-82cb-037e7e62c799/api"
10:49:16 INFO  juju.juju api.go:78 connecting to API addresses: [10.233.36.39:17070]
10:49:16 DEBUG juju.api apiclient.go:618 starting proxier for connection
10:49:16 DEBUG juju.api apiclient.go:622 tunnel proxy in use at localhost on port 35991
10:49:16 DEBUG juju.api apiclient.go:1149 successfully dialed "wss://localhost:35991/api"
10:49:16 INFO  juju.api apiclient.go:1051 cannot resolve "localhost": operation was canceled
10:49:16 INFO  juju.api apiclient.go:680 connection established to "wss://localhost:35991/api"
10:49:16 DEBUG juju.cmd.juju.application.deployer deployer.go:400 cannot interpret as local charm: file does not exist
10:49:16 DEBUG juju.cmd.juju.application.deployer deployer.go:206 cannot interpret as a redeployment of a local charm from the controller
10:49:16 DEBUG juju.api monitor.go:35 RPC connection died
ERROR cannot resolve charm URL "cs:kubeflow-lite": cannot get "/kubeflow-lite/meta/any?include=id&include=supported-series&include=published": Get "https://api.jujucharms.com/charmstore/v5/kubeflow-lite/meta/any?include=id&include=supported-series&include=published": x509: certificate signed by unknown authority
10:49:16 DEBUG cmd supercommand.go:537 error stack:
cannot resolve charm URL "cs:kubeflow-lite": cannot get "/kubeflow-lite/meta/any?include=id&include=supported-series&include=published": Get "https://api.jujucharms.com/charmstore/v5/kubeflow-lite/meta/any?include=id&include=supported-series&include=published": x509: certificate signed by unknown authority

**Comment by knkski** [comment]
@KYUNGSOO-LEE Are you on a machine that has restricted HTTPS certificates? I'm not sure why you'd be seeing this issue otherwise, as api.jujucharms.com has a valid certificate

**Comment by edhenry** [comment]
@KYUNGSOO-LEE Are you behind a proxy where the cluster is being deployed? The added certificate from the proxy in the chain breaks the certificate validation mechanisms within python.

I had similar issues with this and once an exception was added for `api.jujucharms.com` everything functioned fine. 

You can verify that certificates for the URL using CURL as shown below.

```bash
curl --insecure -vvI https://api.jujucharms.com/ 2>&1 | awk 'BEGIN { cert=0 } /^\* SSL connection/ { cert=1 } /^\*/ { if (cert) print }'
```

It should produce output as shown below 

```
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=api.jujucharms.com
*  start date: May 30 06:50:43 2021 GMT
*  expire date: Aug 28 06:50:43 2021 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
* Connection #0 to host api.jujucharms.com left intact
```

Though if you have a proxy in the path it might have some information regarding that in the `issuer:` field shown above.

**Comment by KYUNGSOO-LEE** [comment]
Yes, I am on a machine that has restricted HTTPS certificates. I added my private certificate and update.  
When I run CURL command. Below result:

```
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=api.jujucharms.com
*  start date: May 30 06:50:43 2021 GMT
*  expire date: Aug 28 06:50:43 2021 GMT
*  issuer: C=KR; ST=Gyeonggi-do; L=Icheon; O=SK hynix; OU=IT Security; CN=hynix; emailAddress=network@skhynix.com
*  SSL certificate verify ok.
* Mark bundle as not supporting multiuse
* Connection #0 to host api.jujucharms.com left intact
```
I would use proxy server of my company. How to add exception for api.jujucharms.com in my machine?

**Comment by edhenry** [comment]
There are ways to disable the verification using environmental variables, ***though it must be mentioned that the solution has potential of increasing an attack surface of a system leveraging the workaround.***

That said, if you set the environmental variable `PYTHONHTTPSVERIFY=0` this _should_ allow disabling of the verification when the Python interpreter is envoked.

Something like this should work

```bash
export PYTHONHTTPSVERIFY=0
```

The above example will set the environmental variable for your current working session. If you want to persist the setting, depending on the underlying OS, there are ways to do just that. An example would be modifying `~/.bashrc` and appending the above command, in Ubuntu.

I did try this, myself, but with the layers of abstraction I was dealing with in terms of hypervisors and execution environments I wasn't able to get it functional.

**Comment by knkski** [comment]
@KYUNGSOO-LEE: I believe this documentation will fix the issue for you:

https://discourse.charmhub.io/t/adding-trusted-certificate-authority-certificates-ca-certs-to-machines-including-machines-yet-to-be-provisioned/2289

Closing this issue since the documentation seems to fix the issue, feel free to reopen if it doesn't
