### ISSUE TITLE
'Sorry, /katib/ is not a valid page' after deploying katib

### ISSUE THREAD

**Issue by DnPlas** [canonical/bundle-kubeflow#371]
I've followed [these](https://github.com/kubeflow/katib/tree/master/operators#5-deploy-the-katib-bundle) instructions to deploy katib on an existing Kubeflow deployment. I was expecting to be able to click on the 'Experiments (AutoML)' tab and see Katib UI, but instead I get the message 'Sorry, /katib/ is not a valid page'.

Besides running `juju deploy katib`, I have not ran any other command (like to setup a PV). Am I missing something?

Current setup:
- Microk8s 1.20.7
- juju 2.9.4
- Kubeflow 1.20.7 via juju deploy 
- Katib via juju deploy

**Comment by evilnick** [comment]
Hi, thanks for reporting this issue. I will have to look at it further, but I think it is likely that something has changed in Kubeflow 1.3, which is now the current version

**Comment by knkski** [comment]
@DnPlas I think the missing link here for you is setting up this relation that we have defined in `bundle.yaml`:

https://github.com/canonical/bundle-kubeflow/blob/master/bundle.yaml#L35

You should be able to run `juju relate istio-pilot katib-ui` and have that route set up for you. @evilnick @RFMVasconcelos this seems like a documentation bug that we should fix

**Comment by DnPlas** [comment]
Ah! Thanks @knkski that makes total sense and solves it for me. Feel free to keep this bug open if you'd like to track the documentation bug; otherwise, feel free to close it.

**Comment by evilnick** [comment]
I updated [this page](https://discourse.charmhub.io/t/customize-your-kubeflow-deployment/3813) in the docs, but there should be some more general guidance on adding charms
