### ISSUE TITLE
"Service Istiod Not Found" When Creating Notebook

### ISSUE THREAD

**Issue by jnikles1** [canonical/bundle-kubeflow#386]
Hello,

I'm experiencing the following error after installing the kubeflow bundle cs:kubeflow as described here https://charmed-kubeflow.io/docs/install. This errer can be observed in the statefulset as well as the jupyter-controller

> Reason:"FailedCreate", Message:"Reissued from statefulset/test: create Pod test-0 in StatefulSet test failed error: Internal error occurred: failed calling webhook \"sidecar-injector.istio.io\": Post \"https://istiod.kubeflow.svc:443/inject?timeout=30s\": service \"istiod\" not found"

When I look at the sidecar injector mutatingwebhookconfiguration I can see that the service "istiod" is referenced:
```
  name: istio-sidecar-injector
  resourceVersion: "47653819"
  uid: 48cbe4ab-15a0-4414-941a-dc6474f93b99
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: <key>
    service:
      name: istiod
      namespace: kubeflow
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: sidecar-injector.istio.io
  namespaceSelector:
    matchLabels:
      istio-injection: enabled
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
``` 

I've made no changes to the bundle, and didn't previously install istio on my cluster. I'm really hoping to get kubeflow to work on my cluster, so I'd love to understand what needs to change from here. Do I install istiod? Is this a bug in the bundle? Should I rename the service to istiod-pilot? Thanks in advance!

**Comment by knkski** [comment]
@jnikles1 Are you able to paste the output from `juju status` (or `microk8s juju status` )? I'm not sure how the webhook got into the state of referencing `istiod`, as it should be based off of the name of the `istio-pilot` charm, as seen here:

https://github.com/canonical/bundle-istio/blob/master/charms/istio-pilot/src/charm.py#L329-L335

Additionally, if you could run `microk8s inspect` and upload the resulting tarball, that should help diagnose this issue.

**Comment by jnikles1** [comment]
![image](https://user-images.githubusercontent.com/61483166/128063918-724b59cd-7896-4184-8b3f-e98b174db25d.png)
![image](https://user-images.githubusercontent.com/61483166/128063945-aa47d982-1ec6-41cc-be6f-0885cb788332.png)

I added the jupyter-web module only after opening this issue to see if it would help anything, but i've since removed it. I'm not on microk8s. I am using a Gardener cluster deployed on GCP

**Comment by jnikles1** [comment]
@knkski thank you for the reply btw!

**Comment by knkski** [comment]
Glad to hear you figured it out, thanks for the update!
