### ISSUE TITLE
Add registration for `abort_on_fail` pytest mark

### ISSUE THREAD

**Issue by genet022** [canonical/bundle-kubeflow#387]
We just need to register the mark in `pytest.ini`.
Using `addopts = --strict-markers` with unregistered pytest marks causes errors.

Reference here:
https://docs.pytest.org/en/latest/how-to/mark.html#raising-errors-on-unknown-marks

**Comment by genet022** [comment]
Hit this 6 times in a row last night on our aws SKU. 20 times overall so far. Here's a link to all the runs:
https://solutions.qa.canonical.com/bugs/bugs/bug/1939037

**Comment by knkski** [comment]
@genet022 Sorry about this. Are you able to run `tox -e tests` instead of the existing `pytest` command? That will avoid this issue

**Comment by genet022** [comment]
Ooh yeah we'll give that a shot on the next kubeflow deploy in the lab and then close this if it fixes. Thanks!
