### ISSUE TITLE
Centraldashboard searches for ~/.kube/config or sets namespace=kubeflow if not found

### ISSUE THREAD

**Issue by phvalguima** [canonical/bundle-kubeflow#391]
Hi,

Namespace of the deployment is different from "kubeflow".

I was running latest ```cs:kubeflow``` and found out that my kubeflow-dashboard unit was breaking with same issue as #344.
The centraldashboard-config configmap was available already, rendered by the charm; however the dashboard was still not able to load that configuration. I've tried re-applying the configmap, as described on the bug but no luck either.

On my troubleshooting, I've found out that (1) centraldashboard [loads a kubeconfig](https://github.com/kubeflow/kubeflow/blob/e6fdf515c09ba1f695d60a87c9c56ba5fb1718e8/components/centraldashboard/app/k8s_service.ts#L58) and (2) it will consider its own namespace as "kubeflow" if kubeconfig not found.

If I describe the kubeflow-dashboard, I cannot see any volume that mounts to ~/.kube: https://pastebin.ubuntu.com/p/xPQZrfjfrj/

**Comment by DomFleischmann** [comment]
Thanks for pointing this out, we should investigate some more, on what K8s are you running this?

**Comment by phvalguima** [comment]
@DomFleischmann here is the details of my deployment: Charmed Kubernetes

Deployed Kubeflow with MAAS
Kubernetes bundle: https://pastebin.canonical.com/p/NkKqJ5pNrb/
Kubeflow bundle: latest stable (juju deploy cs:kubeflow)

**Comment by ca-scribner** [comment]
fyi as a workaround, copying the configmap that juju creates (in the model's namespace) into the `kubeflow` namespace gets things running

**Comment by DomFleischmann** [comment]
Let's unify this issue with [this one](https://github.com/canonical/kubeflow-dashboard-operator/issues/22) which makes it a bit more concise. Currently we can't deploy kubeflow-dashboard in namespaces that are not called `kubeflow`
