### ISSUE TITLE
[KFP] Dashboard for pipelines fails if running in multiuser

### ISSUE THREAD

**Issue by phvalguima** [canonical/bundle-kubeflow#393]
Hi,

Deployed Kubeflow with MAAS
Kubernetes bundle:  https://pastebin.canonical.com/p/NkKqJ5pNrb/
Kubeflow bundle: latest stable (juju deploy cs:kubeflow)

Using NodePort to connect to istio-ingressgateway.

When connecting to "kubeflow dashboard > Experiments (KFP)",  I get the following error:

```
{"error":"Invalid input error: In single-user mode, ListExperiment cannot filter by namespace.","code":3,"message":"Invalid input error: In single-user mode, ListExperiment cannot filter by namespace.","details":[{"@type":"type.googleapis.com/api.Error","error_message":"In single-user mode, ListExperiment cannot filter by namespace.","error_details":"Invalid input error: In single-user mode, ListExperiment cannot filter by namespace."}]}
```

Error comes from [this line](https://github.com/kubeflow/pipelines/blob/00a0ffbdb72bc4984984cfdeec9a96fd4a72e010/backend/src/apiserver/server/experiment_server.go#L154)

Checking the pipelines source code, I can see that multiuser mode [can be configured](https://github.com/kubeflow/pipelines/blob/00a0ffbdb72bc4984984cfdeec9a96fd4a72e010/backend/src/apiserver/common/config.go#L26).

If I patch kfp-api configmap to add MULTIUSER and MULTIUSER_SHARED_READ:
```
Name:         kfp-api-config-config
Namespace:    kubeflow
Labels:       juju-app=kfp-api
Annotations:  juju.io/charm-modified-version: 0
              juju.io/controller: 7c83f993-a037-4669-8a62-2d94a8d22e0d
              juju.io/model: 12267019-24a9-443b-82e2-f392b5078033

Data
====
sample_config.json:
----
[
  {
    "name": "[Tutorial] Data passing in python components",
    "description": "[source code](https://github.com/kubeflow/pipelines/tree/master/samples/tutorials/Data%20passing%20in%20python%20components) Shows how to pass data between python components.",
    "file": "/samples/tutorials/Data passing in python components/Data passing in python components - Files.py.yaml"
  },
  {
    "name": "[Tutorial] DSL - Control structures",
    "description": "[source code](https://github.com/kubeflow/pipelines/tree/master/samples/tutorials/DSL%20-%20Control%20structures) Shows how to use conditional execution and exit handlers. This pipeline will randomly fail to demonstrate that the exit handler gets executed even in case of failure.",
    "file": "/samples/tutorials/DSL - Control structures/DSL - Control structures.py.yaml"
  }
]

config.json:
----
{"DBConfig": {"DBName": "mlpipeline", "DriverName": "mysql", "GroupConcatMaxLen": "4194304", "Host": "10.1.91.237", "Password": "root", "Port": "3306", "User": "root"}, "ObjectStoreConfig": {"AccessKey": "minio", "BucketName": "mlpipeline", "Host": "minio", "Multipart": {"Disable": "true"}, "PipelinePath": "pipelines", "Port": 9000, "Region": "", "SecretAccessKey": "3QNFYEPTC61DGFLCDUI6OUEEI7WS72", "Secure": "false"}, "ARCHIVE_CONFIG_LOG_FILE_NAME": "main.log", "ARCHIVE_CONFIG_LOG_PATH_PREFIX": "/artifacts", "AUTO_UPDATE_PIPELINE_DEFAULT_VERSION": true, "CACHE_IMAGE": "gcr.io/google-containers/busybox", "CacheEnabled": "true", "DefaultPipelineRunnerServiceAccount": "pipeline-runner", "InitConnectionTimeout": "5s", "ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_HOST": "kfp-viz", "ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_PORT": "8888", 
"MULTIUSER": true, "MULTIUSER_SHARED_READ": true} <<<<-----------------------------------------------------
Events:  <none>
```

The error disappears.

An error that seems similar: https://github.com/kubeflow/pipelines/issues/5906

**Comment by DomFleischmann** [comment]
We don't support multiuser in our current release. We do plan to include it with the 1.4 release which should come out in the next month.

I will for now close this issue as we aren't currently aiming for this to work in the current release. If this still happens with our 1.4 release feel free to reopen.

**Comment by phvalguima** [comment]
Hi @DomFleischmann, I am not sure if I did something wrong, but it seems I have no option other than multiuser with current Kubeflow. The way I've deployed this cluster was:

Deployed Kubeflow with MAAS
Kubernetes bundle: https://pastebin.canonical.com/p/NkKqJ5pNrb/
Kubeflow bundle: latest stable (juju deploy cs:kubeflow)

And that rendered the above error.

**Comment by ca-scribner** [comment]
Yeah I think @phvalguima's issue here really is that he'd like pipelines, and the only way he can get there is by enabling multiuser atm.
