### ISSUE TITLE
Kubeflow installation cannot complete on Ubuntu 18 and 20

### ISSUE THREAD

**Issue by besn0847** [canonical/bundle-kubeflow#396]
Hi,

After 2 days of trying to install Kubeflow on Microk8s, i finally come to the community.
I trying on possible combination of Ubuntu 18.04 & 20.04 + Microk8s 1.18, 1.19, 1.20, 1.21.

On my my last attempt i had Ubuntu 18.04.5 and installed Microk8s 1.19.

Then i do the standards described here : https://www.kubeflow.org/docs/distributions/microk8s/kubeflow-on-microk8s/
	- microk8s enable dns dashboard storage istio
	<wait until all PODs are up & running>
	- microk8s enable kubeflow

After more than 1 hour of install, the installation stalls and the message keeps saying there are still 10 components to install.
However looking at the kubectl get pods -A output, all pods are up & running.

When i do : 
	export NAMESPACE=istio-system
	microk8s kubectl port-forward -n ${NAMESPACE} --address 0.0.0.0 svc/istio-ingressgateway 8080:80
and connect to the Kubeflow dashboard on port 8080, i get the overall frame but there is no section in the lesft panel.

If i connect locally to the http://<my ip>.nip.io, i get a 404 error.

My VM is 8 vCPU, 32 GB RAM and 192GB SDD : so likely not a resource issue.

Any ideas ?

thx

**Comment by besn0847** [comment]
[inspection-report-20210922_041649.tar.gz](https://github.com/canonical/bundle-kubeflow/files/7207696/inspection-report-20210922_041649.tar.gz)

**Comment by DomFleischmann** [comment]
Hello @besn0847, it is very possible that you enabling istio before kubeflow is causing problems. You don't have to enable anything before executing `microk8s enable kubeflow`. Especially istio isn't necessary as kubeflow comes with its own istio.

I would recommend you to do the following:
Remove microk8s completely:
`sudo snap remove microk8s --purge`

Reinstall microk8s 1.21:
`sudo snap install microk8s --classic --channel=1.21/stable`

And afterwards enable kubeflow with the latest bundle:
`microk8s enable kubeflow --bundle=cs:kubeflow-lite`

**Comment by besn0847** [comment]
Thank you. It finally worked by switching to a more powerful server. Was probably timeouting.
