### ISSUE TITLE
seldon-controller-manage Back-off restarting failed container

### ISSUE THREAD

**Issue by studentz** [canonical/bundle-kubeflow#399]
Deploying `cs:kubeflow-edge`

**Description of the issue**:
The deploy stop leaving operators and other resources in a waiting state.
Error:
pod seldon-controller-manager-\*\*\*-\*\*\*       Back-off restarting failed container

**Deployment**:
MAAS->juju->k8s->kubeflow
GPU server and dynamic storage provision 

**Additional Info**:
1. From Kubeflow side:
> 1.1. events
- Successfully assigned kuberflow/seldon-controller-manager-**-** to gpu2
- Container image "jujusolutions/jujud-operator:2.9.9" already present on machine
- Created container juju-pod-init
- Started container juju-pod-init
- Container image "registry.jujucharms.com/seldon-charmers/seldon-core/oci-image@sha256:82fd0294b88c46e40df161404c4d9fb3743a674c22fe6f8b1aaa9a09e14e07b7" already present on machine
- Created container seldon-core
- Started container seldon-core
- Back-off restarting failed container
> 1.2. logs
- {"level":"info","ts":1633440253.2846353,"logger":"setup","msg":"Intializing operator"}
- {"level":"info","ts":1633440253.3284042,"logger":"setup","msg":"CRD not found - trying to create"}
- {"level":"error","ts":1633440253.4033308,"logger":"setup","msg":"unable to initialise operator","error":"the server could not find the requested resource","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/workspace/main.go:149\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

2- From juju side:
> 2.1 juju debug-hook  ./dispatch

- 2021-10-05 13:38:37,594 DEBUG    Operator Framework 1.1.0 up and running.
- 2021-10-05 13:38:37,656 DEBUG    Legacy hooks/update-status does not exist.
- 2021-10-05 13:38:37,712 DEBUG    Using controller storage: JUJU_VERSION=2.9.9
- 2021-10-05 13:38:37,962 DEBUG    Emitting Juju event update_status.

**Comment by chshr** [comment]
I also have a similar issue

**Comment by DomFleischmann** [comment]
This is a known issue when using a kubernetes version later than 1.21. For now we only support up to Kuberentes 1.21 due to pending upstream work to support later versions.
