### ISSUE TITLE
Not able to access kubeflow 

### ISSUE THREAD

**Issue by leeadh** [canonical/bundle-kubeflow#406]
I cant seem to be able to access mkubeflow through microk8. I followed this guide here https://iamageek.medium.com/install-kubeflow-in-10-steps-on-macos-96d7dda9612 and  here https://ubuntu.com/tutorials/deploy-kubeflow-ubuntu-windows-mac#5-access-the-kubeflow-dashboard and even on your docs: https://v0-6.kubeflow.org/docs/started/workstation/getting-started-macos/

I am using sudo snap install microk8s --classic --channel=1.18

After ensuring that the kubeflow is successfully installed, I did the below

```
ubuntu@kubeflow:~$ sudo -- sh -c "echo '10.64.140.43\t10.64.140.43.xip.io' >> /etc/hosts"
ubuntu@kubeflow:~$ sudo iptables -P FORWARD ACCEPT
ubuntu@kubeflow:~$ exit
ssh -i kubeflow -D9999 ubuntu@192.168.64.4
```

But I keep getting an access issue to 10.64.140.43.xip.io was forbidden when I try to access via the browser ( I already set the SOCKS proxy) and I tried both chrome and firefox.  Really bad documentation as it doesn't tell us how to debug. 

![image](https://user-images.githubusercontent.com/15122358/140637912-f298de27-b722-468e-9082-48e0508479fc.png)

**Comment by DomFleischmann** [comment]
Can you try with a later microk8s like `1.21/stable`? Also, we have moved from `xip.io` to `nip.io` as xip has been abandoned upstream.

**Comment by leeadh** [comment]
Sorry i wrote it wrong. Im accessing nip.io. I will try with 1.21/stable. It would be good to update your documentation so people who are trying out don't waste time. I tried with 1.22 then wasn't supported. Then tried 1.18 didn't work. so now trying 1.21.

**Comment by leeadh** [comment]
ok now it worked with 1.21. BUT another issue

When i tried accessing workbooks, I get a {
  "log": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.", 
  "status": 404, 
  "success": false, 
  "user": "admin"
![image](https://user-images.githubusercontent.com/15122358/140706780-7d656ba7-c258-48be-a90e-b8aa4c8d8740.png)

}

**Comment by leeadh** [comment]
i also tried to run a pipeline but it shows This step is in Error state with this message: task 'file-passing-pipelines-ff5tb.repeat-line' errored: Internal error occurred: failed calling webhook "admission-webhook.kubeflow.org": Post "https://admission-webhook.kubeflow.svc:443/apply-poddefault?timeout=30s": x509: certificate signed by unknown authority. 

Seems like this is very buggy.

![image](https://user-images.githubusercontent.com/15122358/140707543-20d775a6-1bf8-4786-8412-a4271da252a7.png)

**Comment by ca-scribner** [comment]
Sorry there's some things mixed up with the current pipeline setup.  This should be resolved in ~2 weeks or so when we release a new bundle that supports Kubeflow 1.4

**Comment by jrgirona** [comment]
Hi! I have just tried the 2 tutorials that come with Kubeflow version: Charmed Kubeflow, from Canonical, version 1.4 
The error seems to be the same that the one presented in the thread:   task 'file-passing-pipelines-wjvkq.write-numbers' errored: Internal error occurred: **failed calling webhook "admission-webhook.kubeflow.org"**: Post "https://admission-webhook.kubeflow.svc:4443/apply-poddefault?timeout=10s": x509: certificate signed by unknown authority,   
![Screenshot from 2022-08-11 17-11-59](https://user-images.githubusercontent.com/5008993/184167895-c38f14a2-818e-4471-90f3-7dbfd4fb115e.png)

Is there any fix?
Thanks very much,
Ramón Girona
