### ISSUE TITLE
In single-user mode, ListExperiment cannot filter by namespace.

### ISSUE THREAD

**Issue by pshegde** [canonical/bundle-kubeflow#412]
Hi,

I see this error in single user mode,

host="http://ml-pipeline.kubeflow.svc.cluster.local:8888"
client = kfp.Client(host=host)
print(client.get_kfp_healthz())

print(requests.get(f"{host}/apis/v1beta1/experiments").content) #works 
print(client.list_experiments()) #error
print(client.create_experiment('exp3')) #error

fp_server_api.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Trailer': 'Grpc-Trailer-Content-Type', 'Date': 'Wed, 01 Dec 2021 03:12:29 GMT', 'Transfer-Encoding': 'chunked'})
HTTP response body: {"error":"Invalid input error: In single-user mode, ListExperiment cannot filter by namespace."

Tried to use the kfp-ui nodeport ip as the host too but see the same error.

**Comment by joselmh** [comment]
After following the installation procedure [here](https://charmed-kubeflow.io/docs/install), I'm having exactly the same issue when just clicking on Experiments(KFP). 

![Selection_366](https://user-images.githubusercontent.com/42437499/144400123-154a82e2-46fe-4f2a-bca4-39b588e6a97d.png)

Also, when trying to create an experiment after uploading a pipeline I also have a single-use related error.

![Selection_367](https://user-images.githubusercontent.com/42437499/144400433-8850c06c-39e9-49c0-8163-b285bf6513af.png)

I think this is related to the original post. If not, please let me know and I will create a separate issue.

**Comment by DomFleischmann** [comment]
This issue should be fixed with the latest Charmed Kubeflow 1.4 release, feel free to reopen this issue if it still occurs.
