### ISSUE TITLE
Multi-user enabled installation

### ISSUE THREAD

**Issue by joselmh** [canonical/bundle-kubeflow#413]
I'm following this [documentation](https://charmed-kubeflow.io/docs/install) to install Kubeflow on an AKS cluster.
But after the procedure, it seems that it's a single-user mode installation.
Is there a way of enabling multi-user or some other procedure to follow to install with multi-user mode?

**Comment by pshegde** [comment]
Pease check https://github.com/canonical/bundle-kubeflow/issues/411#issuecomment-983533728

**Comment by DomFleischmann** [comment]
Multi-user is now enabled with our latest release of kubeflow 1.4.
