### ISSUE TITLE
kubeflow installation

### ISSUE THREAD

**Issue by Pisou** [canonical/bundle-kubeflow#416]
is it possible to install kubeflow on local machine?

**Comment by Pisou** [comment]
juju bootstrap myk8s my-controller
ERROR cannot connect to API: no controller API addresses; is bootstrap still in progress?

**Comment by evilnick** [comment]
it is if you have the resources to run it there. Have you just recently installed MicroK8s? It may be that the cluster hasn't settled.
Are you following this - https://juju.is/docs/olm/get-started-on-kubernetes
