### ISSUE TITLE
How to get username and password fileds on dex login instead of email and password for kubeflow?

### ISSUE THREAD

**Issue by shamiulshifat** [canonical/bundle-kubeflow#422]
When I deployed kubeflow for first time, it generated a user id and password with a url. When I go to that address, the login page shows email and password fields, not user and password. I am stuck here. How to resolve this?

**Comment by DomFleischmann** [comment]
This might be poor naming on our side, but the static-username field is equal to the email field, sorry for the confusion.

**Comment by shamiulshifat** [comment]
thanks. it works.
