### ISSUE TITLE
Charmed Kubeflow failing to deploy on Kubernetes v1.21.6 deployed with Kubeflow

### ISSUE THREAD

**Issue by ajdecon** [canonical/bundle-kubeflow#424]
I'm running into an error when attempting to install Charmed Kubeflow on a freshly-deployed cluster running Kubernetes v1.21.6 on Ubuntu 20.04.1, deployed using [Kubespray v2.17.1](https://github.com/kubernetes-sigs/kubespray/releases/tag/v2.17.1).

The error I see is:

```
- upload charm kubeflow-roles from charm-hub for series kubernetes from channel latest/stable
- deploy application kubeflow-roles from charm-hub with 1 unit on kubernetes with latest/stable
ERROR cannot deploy bundle: series "kubernetes" not supported by charm, supported series are: focal
```

Full install log in [this gist](https://gist.github.com/ajdecon/4a8bd0a087bc88ca47ffb75986339e1e)

Any suggestions for resolving or troubleshooting this issue?

I'm troubleshooting this on a virtual test cluster, but some miscellaneous system details that may be helpful:

```
vagrant@virtual-mgmt01:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
vagrant@virtual-mgmt01:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:50:34Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

```
vagrant@virtual-mgmt01:~$ kubectl get nodes
NAME             STATUS   ROLES                  AGE   VERSION
virtual-gpu01    Ready    <none>                 33m   v1.21.6
virtual-gpu02    Ready    <none>                 33m   v1.21.6
virtual-mgmt01   Ready    control-plane,master   35m   v1.21.6
virtual-mgmt02   Ready    control-plane,master   34m   v1.21.6
virtual-mgmt03   Ready    control-plane,master   34m   v1.21.6
```

**Comment by DomFleischmann** [comment]
Hello @ajdecon thank you for filing this issue.

I'm not entirely sure what the issue is here, but I suspect there might be something missing in your Kubernetes cluster for juju to work correctly. One thing you will need for sure is a storage class that you can pass through during the `add-k8s` command and some working dns, you can gather more information in the [juju docs](https://juju.is/docs/olm/get-started-on-kubernetes).

**Comment by ajdecon** [comment]
@DomFleischmann : Thanks for the reply!

I rebuilt my test cluster from scratch with the same scripts, but paused before trying to install Kubeflow again. At this stage, my current cluster state looks like this: [gist](https://gist.github.com/ajdecon/ab7b74cc1af3055203e59fb3cae46b69). I can confirm that this cluster includes a functioning storage class (NFS provisioner) and DNS.

However, I still wouldn't be surprised if something is missing here! This is a pretty minimal cluster install: we set up Kubernetes with Kubespray, install the NFS Client Provisioner storage class, and then stop.

Is there a document that lays out the cluster level requirements for Juju and/or Kubeflow? I'm finding it difficult to locate a clear list of requirements. For example, the [juju docs you referred to](https://juju.is/docs/olm/get-started-on-kubernetes) don't explicitly call out a storage class anywhere, except in the context of enabling add-ons for microk8s.

I'd also appreciate pointers on extra troubleshooting steps I could take. E.g., are there any juju debugging commands that would be helpful to inspect where this failure is occurring or why?

**Comment by DomFleischmann** [comment]
Yes, there have been some changes in the juju docs, that removed the part I was looking for, I will follow up with them.

In the meanwhile, if this is a minimal cluster install I could recommend you using [microk8s](https://microk8s.io/) it is the environment we use for our testing and where we can be sure it works. There is this [quickstart](https://charmed-kubeflow.io/docs/quickstart) guide that can help you get started.

**Comment by ajdecon** [comment]
@DomFleischmann : In a new test today, I was able to successfully deploy the `kubeflow-lite` bundle in this environment! 🎉 

However, it did require re-running the install command 2-3 times in order to successfully install. (`juju deploy --verbose --trust kubeflow-lite`) 

Apologies, I hadn't tried a retry in place before as it wasn't clear from the juju docs that this was a safe operation to retry.

The error message I saw was pretty unhelpful, and as you mentioned the docs don't have clear requirements, so I think there are at least some user-friendliness issues here. ;-)

But from my perspective, you can close this issue now. Thanks for the help!

**Comment by DomFleischmann** [comment]
Glad you got it working @ajdecon !

I'll pass on those user-frindliness issues.
