### ISSUE TITLE
Charmed Kubeflow 1.5

### ISSUE THREAD

**Issue by DomFleischmann** [canonical/bundle-kubeflow#440]
With the upstream release of Kubeflow 1.5 happening in the next week we are opening this issue to track progress on Charmed Kubeflow 1.5. 

Unfortunately we won't be able to align our release date with upstream but will make an effort to keep track of any progress on it in this issue.

**Comment by DnPlas** [comment]
Invalid as we are releasing 1.6. Feel free to re-open if needed.
