### ISSUE TITLE
Updating the MinIO credentials is not forcing the pods which use them to restart.

### ISSUE THREAD

**Issue by Barteus** [canonical/bundle-kubeflow#441]
The minio credentials are in the secrets and the change using juju config is changing it there. Noting happens after it. No Pods, which are related to the Minio, are notified of the change = no Pods are recreated. The Pods are taking the minio credentials at the start. When the change of config does not force Pods to recreate - applications do not know about configuration changes. 

This means that after config change I need to manually delete all the Pods that uses this and operators will recreate them. Additionally, I need to know which Pods needs to be restarted after a configuration change.

**Workaround**
Delete all pods that are not operators.

**Comment by DomFleischmann** [comment]
@ca-scribner is this addressed with the addition of the config hash?

**Comment by misohu** [comment]
fixed in https://github.com/canonical/minio-operator/pull/56
