### ISSUE TITLE
Bug with security concerns: Use of certifi installs hard coded set of ca-certificates. Use of certifi should be avoided for all container based deployments

### ISSUE THREAD

**Issue by ReggieCarey** [canonical/bundle-kubeflow#444]
When attempting to deploy kubeflow into a k8s environment running on openstack behind a corporate firewall with TLS interposition, Corporate CA certificates need to be installed or made available inside containers such as the kubeflow deployment operators and the juju-operator container used by juju in particular.

Some subset of the operators deployed with "juju deploy kubeflow" rely on "certifi" to establish a known set of ca certificates.  This set of certificates cannot be changed. Thus it makes it impossible to deploy these components in an environment where an alternate ca-certificate is required.

The use of certifi in a container environment makes it impossible to utilize custom CA certificates and control the trust platform. Injecting ca-certs into /etc/ssl/certs or /usr/local/share/ca-certificates does not work because the python code only looks to certifi to serve ca-certificates.  

NO ONE should have trust in a set of ca-certificates embedded in a python module.

This appears to be a really bad design choice for implementation of operators for deployment of kubeflow in particular.

The following kubeflow operators appear to be affected:

argo-controller-operator-0
pod-dex-auth-operator-0
pod-envoy-operator-0
istio-ingressgateway-operator-0
istio-pilot-operator-0
jupyter-ui-operator-0
katib-ui-operator-0
kfp-api-operator-0
kfp-persistence-operator-0
kfp-profile-controller-operator-0
kfp-ui-operator-0
kfp-viz-operator-0
kubeflow-dashboard-operator-0
kubeflow-profiles-operator-0
kubeflow-volumes-operator-0
minio-operator-0
mlmd-operator-0
oidc-gatekeeper-operator-0
tensorboards-web-app-operator-0

The above pods all fail in exactly the same code location for exactly the same reason:

  File "/var/lib/juju/agents/<pod-name>/charm/venv/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/<pod-name>/charm/venv/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/<pod-name>/charm/venv/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/<pod-name>/charm/venv/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /canonical/operator-schemas/master/ingress.yaml (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))

All of the above pods utilize certifi 

One only need look to /var/lib/juju/agents/unit-*/charm/venv/certifi to verify its use and to see the ca-certificates imposed by the certifi developers.

**Comment by kimwnasptd** [comment]
Closing this issue since it hasn't been a priority for the last year, and we don't think we'll prioritise this soon enough.

We'll need to better understand in the future what are the implications of `certifi` and if migrating to using Canonical's TLS Operator Charms could resolve this.
