### ISSUE TITLE
kubectl: command not found

### ISSUE THREAD

**Issue by CodeCreatorLLC** [canonical/bundle-kubeflow#448]
Patch not working.....

![image](https://user-images.githubusercontent.com/17622584/163011202-49456520-63d0-4092-8ca0-4d3ce2c109ac.png)

**Comment by CodeCreatorLLC** [comment]
Any one have any suggestions on why the patch doesn't work?

**Comment by DomFleischmann** [comment]
Can you provide some more context?

What is the error message? What Kubernetes are you using? What version of charmed kubeflow?

**Comment by CodeCreatorLLC** [comment]
Hello Dom,  Thanks for getting back to me.  Tried to install on Ubuntu 20.04 server.  Followed instructions pretty much to a tee found here (https://youtu.be/M_Ama8ZY8OQ)

However when applying the patch manually (seen at time at 6:23).  The command is not found.   Here is the patch applied.

kubectl patch role -n kubeflow istio-ingressgateway-operator -p '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"name":"istio-ingressgateway-operator"},"rules":[{"apiGroups":["*"],"resources":["*"],"verbs":["*"]}]}'

However if you need further info, I will have to go back and spin up a new server to provider that info.

Deeply appreciate your help in advance.

**Comment by DomFleischmann** [comment]
In general we recommend to use the official [documentation](https://charmed-kubeflow.io/docs) as it is kept more up to date. In particular the [quick start guide](https://charmed-kubeflow.io/docs/quickstart) is a good place to get started quickly.

Regarding your issue given that you installed kubeflow with microk8s you probably need to append `microk8s` in front of the command like this:
`microk8s kubectl patch role -n kubeflow istio-ingressgateway-operator -p '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"name":"istio-ingressgateway-operator"},"rules":[{"apiGroups":[""],"resources":[""],"verbs":["*"]}]}'`

If this doesn't work please try using the quick start guide which contains the latest instructions.

**Comment by CodeCreatorLLC** [comment]
Great I'll give it a try.   Thank you kindly for your help

**Comment by CodeCreatorLLC** [comment]
Hello Dom,

Followed instructions found on the official documentation page.  https://charmed-kubeflow.io/docs/quickstart
Ran an AWS Ubuntu 20.04 instance, etc....
Got as far a "Accessing the Dashboard" and ran into a problem in the url.  Any help would be greatful

 See screen shots


![screen 1](https://user-images.githubusercontent.com/17622584/164312391-35f06398-e445-4bfe-b6c2-402d602ed060.JPG)

![screen 2](https://user-images.githubusercontent.com/17622584/164312404-0aba36ad-ec62-4d68-968f-c38ac64daf35.JPG)

![screen 3](https://user-images.githubusercontent.com/17622584/164312408-d305acfc-a880-48e1-bd4f-4439ce57a99e.JPG)

**Comment by DomFleischmann** [comment]
Hello @CodeCreatorLLC given that your status still shows multiple applications in waiting can you please try once all the applications are in `active`?

**Comment by CodeCreatorLLC** [comment]
Hello Dom... Thanks for all your help.  Unfortunately same result for url to access dashboard.   See screen shots.....

![Kubeflow 1](https://user-images.githubusercontent.com/17622584/164555973-634a7ed1-d02a-416f-8eac-50854aee66df.JPG)

![Kubeflow 2](https://user-images.githubusercontent.com/17622584/164555993-8b67596e-0525-4e2a-8036-baf90491b02e.JPG)

Not sure what to do next.  All ports are open....  Appreciate any further help.

**Comment by DomFleischmann** [comment]
Just to be sure, are you installing this on your local machine or a remote one?

If it is a remote one you will have to use something like socks proxy to access the dashboard (see the docs [here](https://charmed-kubeflow.io/docs/dashboard))

Also, have you set the URL in the authentication charms like this?
```
juju config dex-auth public-url=http://<URL>
juju config oidc-gatekeeper public-url=http://<URL>
