### ISSUE TITLE
Issues with seldon-controller-manager

### ISSUE THREAD

**Issue by soumen-ghosh** [canonical/bundle-kubeflow#449]
I've installed kubeflow-lite bundle through juju following instructions from https://charmed-kubeflow.io/docs/install. But seldon-controller-manager pod keeps crashing since deployment.

(base) root@pbm088:~# kubectl logs pod/seldon-controller-manager-cf7545746-5442x -n kubeflow
{"level":"info","ts":1649909040.3439353,"logger":"setup","msg":"Intializing operator"}
{"level":"info","ts":1649909040.3547642,"logger":"setup","msg":"CRD not found - trying to create"}
{"level":"error","ts":1649909040.4087517,"logger":"setup","msg":"unable to initialise operator","error":"the server could not find the requested resource","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/workspace/main.go:149\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

I tried with kubeflow (instead of kubeflow-lite) bundle also - even with that deployment seldon-controller-manager keeps crashing.

My kubernetes version is following:
(base) root@pbm088:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.5-2+c812603a312d2b", GitCommit:"c812603a312d2b0c59687a1be1ae17c0878104cc", GitTreeState:"clean", BuildDate:"2022-03-17T16:14:08Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.5-2+c812603a312d2b", GitCommit:"c812603a312d2b0c59687a1be1ae17c0878104cc", GitTreeState:"clean", BuildDate:"2022-03-17T16:11:06Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}

I did kubectl describe pod also - I could not find anything useful. How to root cause the issue and fix?

**Comment by Barteus** [comment]
Current Charmed Kubeflow supports only kubernetes version `1.21`.

**Comment by DomFleischmann** [comment]
This is effectively due to seldon-controller-manager not supporting k8s versions above `1.21` please use an older version for installing this software.
