### ISSUE TITLE
deployment Kubeflow-lite bundle get stuck on microk8s on serverstack.

### ISSUE THREAD

**Issue by saltiyazan** [canonical/bundle-kubeflow#451]
I have been trying to deploy kubeflow-lite using juju on microk8s on serverstack, I followed the steps from [this guide.]( https://discourse.ubuntu.com/t/install-kubeflow-anywhere/20207).

The deployment gets stuck as in the screenshot:
<img width="1259" alt="Screenshot 2022-04-22 at 15 05 24" src="https://user-images.githubusercontent.com/26838825/164702845-4d2df66d-b9b3-42ae-b0c9-30e23dd20c7b.png">

Pods aren't coming up as expected, output of `kubectl get po -A` [here](https://pastebin.canonical.com/p/KSHf4b3ZPZ/)

Many statefulset.apps also get stuck, output of `kubectl get statfulsets -A` [here](https://pastebin.canonical.com/p/3K6gFgspgS/)
When describing a random statefulset which is not ready (for example envoy-operator) we get [this output](https://pastebin.canonical.com/p/XNhqx4TsSC/).

The error is the same for the other statefulsets as well which is:
error: Internal error occurred: failed calling webhook "admission-webhook.kubeflow.org": Post "https://admission-webhook.kubeflow.svc:4443/apply-poddefault?timeout=10s": Forbidden

Proxy is configured on serverstack and microk8s was installed from behind a proxy.
And the dns was enabled with the same dns used by the host machine. (the change can be seen in configmap/coredns as the 'forward' has the correct value). [content of configmap/coredns here](https://pastebin.canonical.com/p/8nYhxvcQ3j/)

This issue only appears with microk8s on serverstack. (I could successfully deploy kubeflow-lite on charmed-k8s on serverstack and on microk8s on AWS).

**Comment by DomFleischmann** [comment]
This seems like a missing proxy configuration and we are already tracking this in another issue. I will therefore close this one.
