### ISSUE TITLE
Stuck on Waiting for Istio Pilot information

### ISSUE THREAD

**Issue by dwojcik92** [canonical/bundle-kubeflow#469]
Hello, 
I am trying to install kubeflow charm on Kubernetes 1.21.12+k3s1.
```
juju deploy kubeflow --trust
```

The deploy is stuck on: Waiting for Istio Pilot information.

![Screenshot 2022-07-21 at 07 40 20](https://user-images.githubusercontent.com/10101471/180137924-1ab3d3fe-fbe9-4339-bc61-ef36e79d88b5.png)

I used:
```
kubectl patch role -n kubeflow istio-ingressgateway-operator -p '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"name":"istio-ingressgateway-operator"},"rules":[{"apiGroups":["*"],"resources":["*"],"verbs":["*"]}]}'
```
But it does nothing. I tried restarting these pods but still no luck. It is stuck on this for 8h now.

Logs:
![Screenshot 2022-07-21 at 07 46 28](https://user-images.githubusercontent.com/10101471/180138652-9a4137c2-2280-4fc5-b6d6-d85b5b311b45.png)

![Screenshot 2022-07-21 at 07 46 38](https://user-images.githubusercontent.com/10101471/180138669-f2e8fbae-e5b8-434a-b403-68e7665b3976.png)

![Screenshot 2022-07-21 at 07 46 04](https://user-images.githubusercontent.com/10101471/180138601-c08b5deb-ee6e-4365-b6c9-b76a979f2f8c.png)

**Comment by natalian98** [comment]
Hello @dwojcik92, thanks for reporting the issue.
Could you please share with us your deployment details by attaching the output of `kubectl get all -n kubeflow` and `juju status --relations`?

In general, we recommend deploying kubeflow on [microk8s](https://microk8s.io/) by following this [quickstart guide](https://charmed-kubeflow.io/docs/quickstart) to ensure that the required k8s addons are functioning properly.

**Comment by dwojcik92** [comment]
I assumed that I can use charmed kubeflow with my production cluster (k3s) on bare metal. 
While deploying kubeflow with kustomize I found a similar problem (stuck at Istio). I backtracked the problem and I found that before I deployed kubeflow I removed Istio from the cluster. Turns out that Istio did not clean up properly. This is related to [this issue](https://github.com/istio/istio/issues/36727#issuecomment-1007629086).

It is important to delete Istio related stuff in 
- validatingwebhookconfiguration
- mutatingwebhookconfiguration
After that I was able to install kubeflow with kustomize.  The deploy with juju should also work but I have not tested that. Also I needed more custom settings that this charm provides.

Anyway, I think charm should be able to deal with such situations or at least warn user about such issue.

**Comment by ca-scribner** [comment]
@dwojcik92 you make a good point.  I'll add a feature request for the istio charm to look for signs of a previous istio install that didn't clean up properly

Does that mean we're all good for this issue?  I think so, so I'll close it.  But please reopen if I've misunderstood.  Thanks!
