### ISSUE TITLE
Bundle-kubeflow tutorials don't run properly 

### ISSUE THREAD

**Issue by jrgirona** [canonical/bundle-kubeflow#472]
Hi,

I have been trying the 2 tutorials that come with the bundle: [Tutorial] DSL - Control structures] and [Tutorial] Data passing in python components and I cannot get any result, since the run ends in error: This step is in Error state with this message: task 'file-passing-pipelines-wjvkq.repeat-line' errored: Internal error occurred: failed calling webhook "admission-webhook.kubeflow.org": Post "https://admission-webhook.kubeflow.svc:4443/apply-poddefault?timeout=10s": x509: certificate signed by unknown authority. 
I have also compiled sequential.py a very simple sample with dsl-compile without success, same error message in the Run.   

I guess this is a small issue, but nevertheless difficult to fix for a newcomer. If would appreciate any help you could provide

While I was executing the sequential.py, the debug-log was:
application-envoy: 18:42:23 INFO juju.worker.caasoperator.uniter.envoy/0.operation ran "update-status" hook (via hook dispatching script: dispatch)
application-kfp-db: 18:43:56 INFO unit.kfp-db/0.juju-log Reactive main running for hook update-status
application-kfp-db: 18:43:56 INFO unit.kfp-db/0.juju-log Initializing Leadership Layer (is leader)
application-kfp-db: 18:43:56 INFO unit.kfp-db/0.juju-log Invoking reactive handler: reactive/mariadb.py:61:set_mariadb_active
application-kfp-db: 18:43:56 INFO unit.kfp-db/0.juju-log Invoking reactive handler: hooks/relations/mysql/provides.py:20:_handle_joined:mysql
application-kfp-db: 18:43:56 INFO unit.kfp-db/0.juju-log Invoking reactive handler: reactive/mariadb.py:71:provide_database
application-kfp-db: 18:43:56 INFO unit.kfp-db/0.juju-log request -> mysql:11 for app -> kfp-api
application-kfp-db: 18:43:56 INFO unit.kfp-db/0.juju-log db params: mysql:password@mlpipeline
application-kfp-db: 18:43:56 INFO unit.kfp-db/0.juju-log status-set: active: ready
application-kfp-db: 18:43:57 INFO juju.worker.caasoperator.uniter.kfp-db/0.operation ran "update-status" hook (via explicit, bespoke hook script)
application-seldon-controller-manager: 18:43:59 INFO juju.worker.caasoperator.uniter.seldon-controller-manager/0.operation ran "update-status" hook (via hook dispatching script: dispatch)

The status of juju shows everything in green except for:
dex-auth/3*                   error     idle   10.1.5.157  5556/TCP   hook failed: "oidc-client-relation-broken"
dex-auth/4                    waiting   idle   10.1.5.132  5556/TCP  Waiting for leadership

Thanks very much for your kind support.

Regards,

Ramón Girona

**Comment by misohu** [comment]
Hi Ramon, thanks for your ticket. Sadly I am not able to replicate the problem with latest/stable bundle (`juju deploy kubeflow-lite --trust`). Can you please give me more context to your problem. 

- Which bundle did you deploy? 
- What are the logs in dex-pods  (get pods name `kubectl get po -n kubeflow | grep dex` and then logs `kubectl logs -f <name> -n kubeflow`)
- What are the logs in admission webhook pods?
- Please try also to check ` juju debug-log --replay` (history of logs) for any ERRORs

**Comment by jrgirona** [comment]
Hi, thanks very much Misohu, Answers in line:

- Which bundle did you deploy?
If the bundle  version corresponds to the build version on the left bottom corner is **build version dev_local**. The bundle I downloaded from https://www.kubeflow.org/docs/started/installing-kubeflow/ was 1.4. I f you need other version from specific components, pls let me know_

- What are the logs in dex-pods (get pods name kubectl get po -n kubeflow | grep dex.
Sorry I can not get them. I got other issues with The connection to the server localhost:8080 was refused - did you specify the right host or port?. I set up the env variable KUBECONFIG to point to ~/.kube/conf without success. conf file after installation was anyway: 
apiVersion: v1
clusters: null
contexts:
- context:
    cluster: "" 
    user: ""
  name: /home/ramon/.kube/kubeconfig1.yml
current-context: /home/ramon/.kube/kubeconfig1.yml
kind: Config
preferences: {}
users: null  

I made some changes trying to set up the cluster server address server: http://10.64.140.43.nip.io and name to cluster.local without success

- Please try also to check juju debug-log --replay (history of logs) for any ERRORs
Since I booted the linux partition, the errors I received were:
application-minio: 22:05:26 DEBUG juju.api **no** error, but not connected, probably cancelled before we started
application-minio: 22:05:30 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0abb01] "application-minio" cannot open api: cannot resolve "controller-service.controller-microk8s-localhost.svc.cluster.local": lookup controller-service.controller-microk8s-localhost.svc.cluster.local: i/o timeout
impacting most  services not only minio

Then:
application-kfp-viewer: 22:05:42 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0abb01] "application-kfp-viewer" cannot open api: unable to connect to API: dial tcp 10.152.183.204:17070: connect: connection refused
application-kfp-profile-controller: 22:05:43 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0abb01] "application-kfp-profile-controller" cannot open api: unable to connect to API: dial tcp 10.152.183.204:17070: connect: connection refused
application-kubeflow-volumes: 22:05:43 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0abb01] "application-kubeflow-volumes" cannot open api: unable to connect to API: dial tcp 10.152.183.204:17070: connect: connection refused
application-seldon-controller-manager: 22:05:43 DEBUG juju.api no error, but not connected, probably cancelled before we started
application-minio: 22:05:43 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0abb01] "application-minio" cannot open api: cannot resolve "controller-service.controller-microk8s-localhost.svc.cluster.local": lookup controller-service.controller-microk8s-localhost.svc.cluster.local: i/o timeout
application-seldon-controller-manager: 22:05:43 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0abb01] "application-seldon-controller-manager" cannot open api: try was stopped
application-kfp-viz: 22:05:44 DEBUG juju.api no error, but not connected, probably cancelled before we started
application-kfp-viz: 22:05:44 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0abb01] "application-kfp-viz" cannot open api: unable to connect to API: dial tcp 10.152.183.204:17070: connect: connection refused
application-kfp-api: 22:05:55 ERROR juju.worker.dependency "upgrader" manifold worker returned unexpected error: codec.ReadHeader error: error receiving message: read tcp 10.1.5.174:35748->10.152.183.204:17070: read: connection reset by peer
application-kfp-api: 22:05:55 ERROR juju.worker.caasoperator.uniter.kfp-api/0.relation while stopping unit watcher: codec.ReadHeader error: error receiving message: read tcp 10.1.5.174:35748->10.152.183.204:17070: read: connection reset by peer
application-kfp-api: 22:05:55 ERROR juju.worker.dependency "migration-inactive-flag" manifold worker returned unexpected error: codec.ReadHeader error: error receiving message: read tcp 10.1.5.174:35748->10.152.183.204:17070: read: connection reset by peer
application-kfp-api: 22:05:55 INFO juju.worker.caasoperator.uniter.kfp-api/0 unit "kfp-api/0" shutting down: failed to initialize uniter for "unit-kfp-api-0": cannot create relation state tracker: codec.ReadHeader error: error receiving message: read tcp 10.1.5.174:35748->10.152.183.204:17070: read: connection reset by peer
application-kfp-api: 22:05:55 INFO juju.worker.caasoperator.runner stopped "kfp-api/0", err: failed to initialize uniter for "unit-kfp-api-0": cannot create relation state tracker: codec.ReadHeader error: error receiving message: read tcp 10.1.5.174:35748->10.152.183.204:17070: read: connection reset by peer
application-kfp-api: 22:05:55 ERROR juju.worker.caasoperator.runner exited "kfp-api/0": failed to initialize uniter for "unit-kfp-api-0": cannot create relation state tracker: codec.ReadHeader error: error receiving message: read tcp 10.1.5.174:35748->10.152.183.204:17070: read: connection reset by peer
application-kfp-api: 22:05:55 ERROR juju.worker.dependency "migration-minion" manifold worker returned unexpected error: codec.ReadHeader error: error receiving message: read tcp 10.1.5.174:35748->10.152.183.204:17070: read: connection reset by peer
application-kfp-api: 22:05:55 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: codec.ReadHeader error: error receiving message: read tcp 10.1.5.174:35748->10.152.183.204:17070: read: connection reset by peer
application-kubeflow-profiles: 22:05:55 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: codec.ReadHeader error: error receiving message: read tcp 10.1.5.186:59004->10.152.183.204:17070: read: connection reset by peer
application-dex-auth: 22:05:58 INFO juju.worker.caasoperator.uniter.dex-auth/3 awaiting error resolution for "relation-broken" hook
application-kubeflow-profiles: 22:05:58 ERROR juju.worker.caasoperator.uniter.kubeflow-profiles/0 resolver loop error: executing operation "upgrade to ch:amd64/focal/kubeflow-profiles-63" for kubeflow-profiles/0: writing state: connection is shut down
application-kubeflow-profiles: 22:05:58 INFO juju.worker.caasoperator.runner stopped "kubeflow-profiles/0", err: codec.ReadHeader error: error receiving message: read tcp 10.1.5.186:59004->10.152.183.204:17070: read: connection reset by peer
application-kubeflow-profiles: 22:05:58 ERROR juju.worker.caasoperator.runner exited "kubeflow-profiles/0": codec.ReadHeader error: error receiving message: read tcp 10.1.5.186:59004->10.152.183.204:17070: read: connection reset by peer
unit-metacontroller-operator-0: 22:05:58 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: codec.ReadHeader error: error receiving message: read tcp 10.1.5.130:43730->10.152.183.204:17070: read: connection reset by peer
unit-metacontroller-operator-0: 22:05:58 ERROR juju.worker.uniter resolver loop error: executing operation "run start hook" for metacontroller-operator/0: writing state: codec.ReadHeader error: error receiving message: read tcp 10.1.5.130:43730->10.152.183.204:17070: read: connection reset by peer
unit-metacontroller-operator-0: 22:05:58 INFO juju.worker.uniter unit "metacontroller-operator/0" shutting down: executing operation "run start hook" for metacontroller-operator/0: writing state: codec.ReadHeader error: error receiving message: read tcp 10.1.5.130:43730->10.152.183.204:17070: read: connection reset by peer
application-kfp-schedwf: 22:06:00 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: codec.ReadHeader error: error receiving message: read tcp 10.1.5.177:49628->10.152.183.204:17070: read: connection reset by peer
application-kfp-schedwf: 22:06:00 INFO juju.worker.caasoperator.runner stopped "kfp-schedwf/0", err: leadership failure: error making a leadership claim: codec.ReadHeader error: error receiving message: read tcp 10.1.5.177:49628->10.152.183.204:17070: read: connection reset by peer
application-kfp-schedwf: 22:06:00 ERROR juju.worker.caasoperator.runner exited "kfp-schedwf/0": leadership failure: error making a leadership claim: codec.ReadHeader error: error receiving message: read tcp 10.1.5.177:49628->10.152.183.204:17070: read: connection reset by peer
application-kfp-viewer: 22:06:02 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: codec.ReadHeader error: error receiving message: read tcp 10.1.5.167:49212->10.152.183.204:17070: read: connection reset by peer
application-kfp-viewer: 22:06:02 ERROR juju.worker.caasoperator.uniter.kfp-viewer/0.context cannot apply changes: codec.ReadHeader error: error receiving message: read tcp 10.1.5.167:49212->10.152.183.204:17070: read: connection reset by peer
application-kfp-viewer: 22:06:02 ERROR juju.worker.caasoperator.uniter.kfp-viewer/0.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: cannot apply changes: codec.ReadHeader error: error receiving message: read tcp 10.1.5.167:49212->10.152.183.204:17070: read: connection reset by peer
application-kfp-viewer: 22:06:02 INFO juju.worker.caasoperator.runner stopped "kfp-viewer/0", err: leadership failure: error making a leadership claim: codec.ReadHeader error: error receiving message: read tcp 10.1.5.167:49212->10.152.183.204:17070: read: connection reset by peer
application-kfp-viewer: 22:06:02 ERROR juju.worker.caasoperator.runner exited "kfp-viewer/0": leadership failure: error making a leadership claim: codec.ReadHeader error: error receiving message: read tcp 10.1.5.167:49212->10.152.183.204:17070: read: connection reset by peer
application-istio-pilot: 22:06:02 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: codec.ReadHeader error: error receiving message: read tcp 10.1.5.191:51220->10.152.183.204:17070: read: connection reset by peer
application-istio-pilot: 22:06:02 INFO juju.worker.caasoperator.runner stopped "istio-pilot/0", err: leadership failure: error making a leadership claim: codec.ReadHeader error: error receiving message: read tcp 10.1.5.191:51220->10.152.183.204:17070: read: connection reset by peer
application-istio-pilot: 22:06:02 ERROR juju.worker.caasoperator.runner exited "istio-pilot/0": leadership failure: error making a leadership claim: codec.ReadHeader error: error receiving message: read tcp 10.1.5.191:51220->10.152.183.204:17070: read: connection reset by peer
application-dex-auth: 22:06:03 INFO juju.worker.caasoperator.uniter.dex-auth/3 awaiting error resolution for "relation-broken" hook
application-dex-auth: 22:06:05 INFO juju.worker.caasoperator.uniter.dex-auth/3 awaiting error resolution for "relation-broken" hook
application-kfp-viewer: 22:06:11 INFO juju.worker.caasoperator.uniter.kfp-viewer/0 awaiting error resolution for "upgrade-charm" hook
application-kubeflow-profiles: 22:06:12 INFO unit.kubeflow-profiles/0.juju-log pod.set_spec() completed without errors
application-kubeflow-profiles: 22:06:14 INFO unit.kubeflow-profiles/0.juju-log pod.set_spec() completed without errors
application-dex-auth: 22:06:15 INFO juju.worker.caasoperator.uniter.dex-auth/3 awaiting error resolution for "relation-broken" hook
unit-kubeflow-roles-0: 22:06:15 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: codec.ReadHeader error: error receiving message: read tcp 10.1.5.163:33676->10.152.183.204:17070: read: connection reset by peer
application-dex-auth: 22:06:16 INFO juju.worker.caasoperator.uniter.dex-auth/3 awaiting error resolution for "relation-broken" hook
application-kfp-viewer: 22:06:16 INFO juju.worker.caasoperator.uniter.kfp-viewer/0 awaiting error resolution for "upgrade-charm" hook
application-kubeflow-volumes: 22:06:19 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: codec.ReadHeader error: error receiving message: read tcp 10.1.5.148:38714->10.152.183.204:17070: read: connection reset by peer
application-kubeflow-volumes: 22:06:19 INFO juju.worker.caasoperator.runner stopped "kubeflow-volumes/0", err: leadership failure: error making a leadership claim: codec.ReadHeader error: error receiving message: read tcp 10.1.5.148:38714->10.152.183.204:17070: read: connection reset by peer
application-kubeflow-volumes: 22:06:19 ERROR juju.worker.caasoperator.runner exited "kubeflow-volumes/0": leadership failure: error making a leadership claim: codec.ReadHeader error: error receiving message: read tcp 10.1.5.148:38714->10.152.183.204:17070: read: connection reset by peer
application-dex-auth: 22:06:35 INFO juju.worker.caasoperator.uniter.dex-auth/3 awaiting error resolution for "relation-broken" hook
application-dex-auth: 22:06:36 INFO juju.worker.caasoperator.uniter.dex-auth/3 awaiting error resolution for "relation-broken" hook
application-dex-auth: 22:07:16 INFO juju.worker.caasoperator.uniter.dex-auth/3 awaiting error resolution for "relation-broken" hook
application-dex-auth: 22:07:17 INFO juju.worker.caasoperator.uniter.dex-auth/3 awaiting error resolution for "relation-broken" hook
application-dex-auth: 22:07:34 INFO juju.worker.caasoperator.uniter.dex-auth/3 awaiting error resolution for "relation-broken" hook
application-dex-auth: 22:07:49 INFO juju.worker.caasoperator.uniter.dex-auth/3 awaiting error resolution for "relation-broken" hook
application-dex-auth: 22:08:38 INFO juju.worker.caasoperator.uniter.dex-auth/3 awaiting error resolution for "relation-broken" hook
application-dex-auth: 22:08:39 INFO juju.worker.caasoperator.uniter.dex-auth/3 awaiting error resolution for "relation-broken" hook
application-kfp-db: 22:11:07 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: read tcp 10.1.5.189:38560->10.152.183.204:17070: read: connection reset by peer: use of closed network connection
application-dex-auth: 22:11:17 INFO juju.worker.caasoperator.uniter.dex-auth/3 awaiting error resolution for "relation-broken" hook
...
unit-training-operator-0: 22:11:50 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: read tcp 10.1.5.171:36544->10.152.183.204:17070: read: connection reset by peer: use of closed network connection
application-dex-auth: 22:16:18 INFO juju.worker.caasoperator.uniter.dex-auth/3 awaiting error resolution for "relation-broken" hook
... (other INFO messages)

**Comment by DnPlas** [comment]
Hi @jrgirona, regarding this:

```
task 'file-passing-pipelines-wjvkq.repeat-line' errored: Internal error occurred: failed calling webhook "admission-webhook.kubeflow.org": Post "https://admission-webhook.kubeflow.svc:4443/apply-poddefault?timeout=10s": x509: certificate signed by unknown authority.
```

Looks related to canonical/admission-webhook-operator#26, which our team has identified recently. Do you mind trying the workaround in the description of that issue and let us know your results?

Please note that our [official documentation](https://charmed-kubeflow.io/docs/install) has instructions on how to deploy Charmed Kubeflow correctly. Also note that we now have two versions, 1.4/stable and 1.6/beta, to assist you better in the future, the version of your Charmed Kubeflow deployment is whatever you specify in your deployment command, for example: `juju deploy kubeflow --channel 1.4/stable --trust`.

**Comment by jrgirona** [comment]
Hi, the environment is further degraded.

I will copy you what I got and what I have tried. This morning I was talking with a technician from Canonical (a marketing meeting) and he told me to dump the bundle configuration by means of  

_(base) ramon@ramon-XPS-15-9510:~$ conda activate kube_
_(kube) ramon@ramon-XPS-15-9510:~$ juju status_
_ERROR starting proxy for api connection: connecting k8s proxy: Get "https://192.168.1.77:16443/api/v1/namespaces/controller-microk8s-localhost/services/controller-service": x509: certificate has expired or is not yet valid: current time 2022-08-25T23:12:23+02:00 is before 2022-08-25T23:08:23Z_
**THIS ERROR IS PRETTY NEW (FROM TODAY)**

_(kube) ramon@ramon-XPS-15-9510:~$ juju status_
_ERROR starting proxy for api connection: connecting k8s proxy: Get "https://192.168.1.77:16443/api/v1/namespaces/controller-microk8s-localhost/services/controller-service": x509: certificate has expired or is not yet valid: current time_ _2022-08-25T23:12:48+02:00 is before 2022-08-25T23:08:23Z_


Here I try your kubectl command, but the error is the same I already mentioned above when making use of Kubectl  

_(kube) ramon@ramon-XPS-15-9510:~$ kubectl rollout restart deployment/admission-webhook -n kubeflow_
_The connection to the server localhost:8080 was refused - did you specify the right host or port?_
_(kube) ramon@ramon-XPS-15-9510:~$ juju_ 
_Welcome to the Juju interactive shell._
_Type "help" to see a list of available commands._
_Type "q" or ^D or ^C to quit._

_admin@microk8s-localhost:kubeflow$ ^C_


I then try to deploy gain kubeflow to start it over, same ERROR than when using juju status

_(kube) ramon@ramon-XPS-15-9510:~$ juju deploy kubeflow --channel 1.4/stable --trust_
_ERROR starting proxy for api connection: connecting k8s proxy: Get "https://192.168.1.77:16443/api/v1/namespaces/controller-microk8s-localhost/services/controller-service": x509: certificate has expired or is not yet valid: current time_ _2022-08-25T23:16:03+02:00 is before 2022-08-25T23:08:23Z_


And then to export the bundel config

_(kube) ramon@ramon-XPS-15-9510:~$ juju export-bundle_
_ERROR starting proxy for api connection: connecting k8s proxy: Get "https://192.168.1.77:16443/api/v1/namespaces/controller-microk8s-localhost/services/controller-service": x509: certificate has expired or is not yet valid: current time_ _2022-08-25T23:18:15+02:00 is before 2022-08-25T23:08:23Z_

**I don't know what could I do next? Remove kubeflow? Kubeflow and microk8s? Everything, including Juju and restart from scratch?** 

Thanks

**Comment by jrgirona** [comment]
See that I am using the laptop with dual boot, since I am usually working in windows, and I don't know if this also has consequences for Kubeflow and juju. Thanks very much

**Comment by jrgirona** [comment]
I have seen that microk8s has jumped to 2.9

(kube) ramon@ramon-XPS-15-9510:~$ juju controllers
Use --refresh option with this command to see the latest information.

Controller           Model     User   Access     Cloud/Region        Models  Nodes  HA  Version
microk8s-localhost*  kubeflow  admin  superuser  microk8s/localhost       2      1   -  **2.9.32**  

I recall it was necessary to work with version 1.21 or I am wrong. I haven't upgraded intentionally mikrok8s version

**Comment by natalian98** [comment]
Hello @jrgirona, thanks for the update.
It looks that something is now broken with your microk8s deloyment, on which both juju and kubeflow rely on.
You can check the certificates validity by running `sudo microk8s refresh-certs -c`.

It would be best to remove the current deployment and start from scratch. I recommend following the [quickstart guide](https://charmed-kubeflow.io/docs/quickstart) which includes steps to deploy both microk8s, juju and kubeflow. Please note that kubeflow 1.4 (current stable version) supports microk8s **v1.21**. 2.9.32 is the version of juju.

Dual boot doesn't impact juju and kubeflow.
Please share your results and let us know if you need any assistance.

**Comment by jrgirona** [comment]
**Following the official documentation**, after uninstalling the model kubeflow and the controller microk8s, and removing the microk8s snap, I found an error and I don't know what's the best fix or workaround

**UNINSTALLING** to start from scratch:

_$ juju destroy-model kubeflow --destroy-storage_
**Errors uninstalling**

_The following resources have not yet been removed:_
_ - 3 application(s)_
_Because the destroy model operation did not finish, there may be cloud resources left behind._
_Run 'destroy-model <model-name> --timeout=0 --force' to clean up the Juju model database records_
_even with potentially orphaned cloud resources._
_ERROR timeout after 30m0s_

_$ juju destroy-model kubeflow --timeout=0 --destroy-storage --force_
...
_Because the destroy model operation did not finish, there may be cloud resources left behind._

_$ juju destroy-controller microk8s-localhost --destroy-storage_

_$ juju controllers_
_ERROR No controllers registered._ 

**Correct, I guess. I didn't uninstall juju**


**INSTALLING**

_$ snap install microk8s --classic --channel=1.21/stable_

**But**
_$ kubectl cluster-info_
_To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'._
_The connection to the server localhost:8080 was refused - did you specify the right host or port?_

**Before adding the cluster to the list of clouds in juju via the add-k8s command, the cloud seems to be already there:**
_$ juju clouds_
_Only clouds with registered credentials are shown._
_There are more clouds, use --all to see them._
_You can bootstrap a new controller using one of these clouds..._

_Clouds available on the client:_
_Cloud      Regions  Default    Type  Credentials  Source    Description_
_localhost  1        localhost  lxd   0            built-in  LXD Container Hypervisor_
_microk8s   1        localhost  k8s   1            built-in  A Kubernetes Cluster_

**Error when using the command add-k8s**
_$ juju add-k8s myk8s_
_ERROR making juju admin credentials in cluster: invalid configuration: no configuration has been provided, try setting __KUBERNETES_MASTER environment variable_

Any advise?

Thanks very much

**Comment by natalian98** [comment]
Hello @jrgirona thank you for your answer.
Very possibly you don’t have a .kube directory with the right microk8s config in it. Could you try below commands before retrying adding k8s to juju?

`mkdir ~/.kube`
`microk8s config > ~/.kube/config`
`sudo chown -f -R $USER ~/.kube`

If you face any issues please provide output of `sudo microk8s inspect`.

**Comment by jrgirona** [comment]
Hi,

I found first an **issue with the $HOSTNAME which INCLUDED CAPITAL LETTERS and it is unsupported by KUBERNETES TO REGISTER THE NAME** (see below)

(kube) ramon@ramon-**XPS**-15-9510:~_$ juju add-k8s myk8s_
_ERROR making juju admin credentials in cluster: ensuring cluster role "juju-credential-35dec7da" in namespace "kube-system":_ 
_Get "https://172.16.1.13:16443/apis/rbac.authorization.k8s.io/v1/clusterroles/juju-credential-35dec7da": x509: certificate has_ _expired or is not yet valid: current time 2022-08-29T11:33:53+02:00 is before 2022-08-29T11:29:26Z_

(kube) ramon@ramon-XPS-15-9510:~_$ microk8s inspect_
_Inspecting Certificates_
...
**WARNING:  This machine's hostname contains capital letters and/or underscores. 
	  This is not a valid name for a Kubernetes node, causing node registration to fail.
	  Please change the machine's hostname or refer to the documentation for more details: 
	  https://microk8s.io/docs/troubleshooting#heading--common-issues** 


**Then, once I change $HOSTNAME. ADDITIONALLY I HAVE TO REINSTALL THE MICROK8S SNAP**
(kube) ramon@ramon-xps-15-9510:~$ juju add-k8s myk8s
This operation can be applied to both a copy on this client and to the one on a controller.
No current controller was detected and there are no registered controllers on this client: either bootstrap one or register one.

**ERROR 	No recommended storage configuration is defined on this cluster.
	Run add-k8s again with --storage=<name> and Juju will use the
	specified storage class or create a storage-class using the recommended
	"hostpath" provisioner.**
(kube) ramon@ramon-xps-15-9510:~$ microk8s inspect
Inspecting Certificates
Inspecting services
...
Building the report tarball
  Report tarball is at /var/snap/microk8s/3410/inspection-report-20220829_125547.tar.gz

Pls find the tarball enclosed

**What's next for the --storage?** Thanks very much again


[inspection-report-20220829_125547.tar.gz](https://github.com/canonical/bundle-kubeflow/files/9444350/inspection-report-20220829_125547.tar.gz)

**Comment by DnPlas** [comment]
Hi @jrgirona, from the `microk8s inspect` output, I see you are missing some important setup steps, in this case you are missing the storage add-on. I recommend you follow [this quickstart](https://charmed-kubeflow.io/docs/quickstart) guide carefully, and try it out. It is very important that you follow this sequence:
* Install and configure Microk8s (ensure dns, storage and metallb are enabled)
* Install juju
* Bootstrap a juju controller and add a model
* Deploy Charmed Kubeflow
* Configure your deployment for accessing the dashboard

The errors you are running into are not related to Charmed Kubeflow, so please ensure your environment is properly setup for deploying the bundle.

For the issue you reported originally (`Error state with this message: task 'file-passing-pipelines-wjvkq.repeat-line' errored: Internal error occurred: failed calling webhook "admission-webhook.kubeflow.org": Post "https://admission-webhook.kubeflow.svc:4443/apply-poddefault?timeout=10s": x509: certificate signed by unknown authority.`) I suggest that if you run into it again, try the workaround suggested by @natalian98 in [this issue](https://github.com/canonical/admission-webhook-operator/issues/26), we are already trying to fix it.
That being said, and because the original issue is already being tracked in the offending charm, I will close this issue. Feel free to file new issues as you work with Charmed Kubeflow.

**Comment by jrgirona** [comment]
Thanks very much Daniela,

I have been following the installation procedure in
https://charmed-kubeflow.io/docs/install you mentioned in the first e-mail:
https://charmed-kubeflow.io/docs/install , Pls notice that It doesn't
include the instructions about activating the storage add-on, so it will be
worthwhile to correct the doc, and also better to have only one page for
the kubeflow installation.

Good news is that when I tested for the first time the day before yesterday
the platform executed one node (see below), no problem with  failed calling
webhook  and yesterday I meet it again and after applying the workaround
you mentioned in
https://github.com/canonical/admission-webhook-operator/issues/26. *Now the
tutorials work correctly*

[image: image.png]


I have been dealing with a few issues during the installation, so I am
going to document my last steps in the ticket you closed to help those who
may experience similar issues.

My only concern after this experience is why the server certificate only
lasts 24 hours. From my point of view it doesn't make any sense. Moreover
there are support tickets about this problem (most of them) recommending to
prune the .local folder in home, when the best way to do it seems to
refresh the certificate. I miss this advice in the installation procedure.


Kind regards,

Ramón.

**Comment by jrgirona** [comment]
Just a few comments when staring from scratch after removing kubeflow, microk8s and juju, and reinstalling kubeflow following the instructions on https://charmed-kubeflow.io/docs/quickstart , taking into account:

- After installing microk8s, check if ~/.kube directory and file conf are present. Otherwise, create the .kube directory and conf file by:

_mkdir ~/.kube_
_microk8s config > ~/.kube/config_
_sudo chown -f -R $USER ~/.kube_ 

When installation is over then:

![image](https://user-images.githubusercontent.com/5008993/188127360-fa2f49a8-9844-4235-a73c-f271d85fa4ff.png)


**When installed and dashboard is available, you may find the following issues:**
 
- Error with server certificate, 24 hours after the deployment of Kubeflow: 

![image](https://user-images.githubusercontent.com/5008993/188125986-0018a41a-2134-4d9d-a331-313a516770e7.png)

Then you may refresh the certificates by typing:

_$sudo microk8s refresh-certs --cert 'server.crt'_

![image](https://user-images.githubusercontent.com/5008993/188126308-207a024d-0e37-44de-b1ab-04b9e9faa222.png)

No more certifictae issues

![image](https://user-images.githubusercontent.com/5008993/188126762-091eb983-2974-4376-9992-f8406f589b84.png)


- Use microk8s kubectl instead of kubectl

_$ kubectl get pods_
_Unable to connect to the server: dial tcp 10.0.1.82:16443: i/o timeout_
 

- When using the tutorials, if you find out an error like

![image](https://user-images.githubusercontent.com/5008993/188127579-84475d32-2264-4701-9a3f-2b0897117462.png)

_"failed calling webhook "admission-webhook.kubeflow.org": Post "admission-webhook.kubeflow.svc:4443/apply-poddefault?_ _timeout=10s": x509:certificate signed by unknown authority_

type (seen in https://github.com/canonical/admission-webhook-operator/issues/26): 
_$microk8s kubectl rollout restart deployment/admission-webhook -n kubeflow_

![image](https://user-images.githubusercontent.com/5008993/188128271-3e72e819-18d0-4121-9585-5a7b25b531f7.png)

and the tutorials will finally work

![image](https://user-images.githubusercontent.com/5008993/188128770-0ff64ebb-e43f-462c-baec-5cc8f7d38d1b.png)

**Comment by DnPlas** [comment]
I am glad you have the example working @jrgirona !
