### ISSUE TITLE
Difficulties access remotely Kubeflow dashboard using socks

### ISSUE THREAD

**Issue by jrgirona** [canonical/bundle-kubeflow#483]
Dear Sir,

I have been looking around a solution to access remotely the dashboard (when using a ubuntu server platform for instance). 

I have been following section 3 of https://charmed-kubeflow.io/docs/dashboard and the hints in tickets https://github.com/canonical/microk8s/issues/1243 and https://github.com/canonical/microk8s/issues/2228, but I am unable to get access, while the connection to the remote kubeflow platform to enable the socks proxy return the following messages while trying to access to: http://172.16.XX.XX.nip.io/, where 172.16.XX.XX is the IP address of the server or http://10.64.140.43.nip.io/

_ssh -D 9999 rgirona@mlearning.networks.imdea.org_
...
_* Documentation:  https://help.ubuntu.com_
_* Management:     https://landscape.canonical.om_
_* Support:        https://ubuntu.com/advantage_ 

_channel 24: open failed: connect failed: open failed_ 
_channel 25: open failed: connect failed: open failed_ 
_channel 25: open failed: connect failed: open failed_ 
_channel 14: open failed: connect failed: open failed_ 
_channel 15: open failed: connect failed: open failed_ 
_channel 9: open failed: connect failed: Connection timed out_ 
_channel 10: open failed: connect failed: Connection timed out_ 
_channel 4: open failed: connect failed: Connection timed out_ 
_channel 12: open failed: connect failed: Connection timed out_ 
_channel 13: open failed: connect failed: Connection timed out_ 
_channel 17: open failed: connect failed: Connection timed out_

Any clues or alternatives?

Thanks very much,

**Comment by DomFleischmann** [comment]
Hello @jrgirona the ip that is used with `nip.io` needs to be the IP of the `istio-ingressgateway` loadbalancer service. You need to set that Ip (with `nip.io` at the end) in both public-url configurations in dex-auth and oidc-gatekeeper. Once that is done you should be able to access the dashboard.  Please let me know if you are still having issues.

**Comment by jrgirona** [comment]
Hi Dom, 

Pls let me an additional question, what's the way to set up the istio-ingressgateway IP? I undertsnad you mean the external-IP which is in pending status

$microk8s kubectl get svc istio-ingressgateway -n kubeflow
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                                                                                                                 AGE
istio-ingressgateway   LoadBalancer   10.152.183.103   **<pending>**     15020:31067/TCP,80:30962/TCP,443:32011/TCP,15029:31769/TCP,15030:32101/TCP,15031:31752/TCP,15032:30819/TCP,15443:30533/TCP,15011:30321/TCP,8060:30189/TCP,853:31059/TCP   67d


Thanks very much,

Ramón

**Comment by DomFleischmann** [comment]
Hey @jrgirona 

Istio-ingressgateway creates a loadbalancer service, this means you are required to have some kind of loadbalancing in your Kubernetes cluster. In microk8s we use metallb for this. If you don't have a way of setting up loadbalancing you can patch the service to NodePort or ClusterIP.

**Comment by DomFleischmann** [comment]
Hello @jrgirona have we been able to unblock you? I will for now close the issue as the initial comment has been addressed.

**Comment by jrgirona** [comment]
Hi Dom,

Unfortunately not. I have decided to start exploring Kubernetes in books so
I am more aware about the services provided and how to change the
configuration.

Regards
