### ISSUE TITLE
Charmed​ kubeflow 1.3 new notebook server need gpu value as string

### ISSUE THREAD

**Issue by jrgirona** [canonical/bundle-kubeflow#484]
Hi,

Regarding issue **https://github.com/canonical/bundle-kubeflow/issues/390**, is there currently a fix?

The problem continues to be:

_[422] Notebook.kubeflow.org "test-jupyter" is invalid: spec.template.spec.containers.resources.limits.nvidia.com/gpu: Invalid value:_ _"integer": spec.template.spec.containers.resources.limits.nvidia.com/gpu in body must be of type string: "integer" http://xxxxx/_

Thanks very much,

**Comment by DomFleischmann** [comment]
Hello @jrgirona, this issue should be fixed in Kubeflow 1.6 which will be released today. Please feel free to try it out in the coming days and let us know if you still are having issues.

**Comment by DomFleischmann** [comment]
@ollienuk You can wait until tomorrow and deploy 1.6 where this should be fixed :)
