### ISSUE TITLE
issues with charmed KF 1.6 beta

### ISSUE THREAD

**Issue by aym-frikha** [canonical/bundle-kubeflow#485]
Hello, 

Trying to deploy charmed KF 1.6 beta on microk8s 1.22. I had crashloopbackoff on some of the components:

kfp-api: [describe](https://pastebin.canonical.com/p/BnNSNxBVTq/) [logs](https://pastebin.canonical.com/p/b36KSmYbpy/) 

seldon-controller-manager: [describe](https://pastebin.canonical.com/p/6MK3tX7bfQ/) [logs](https://pastebin.canonical.com/p/hgsh6ThkzD/)

kfp-persistence: [describe](https://pastebin.canonical.com/p/z4ntxpnw53/) [logs](https://pastebin.canonical.com/p/xBhQnKYK83/)

kubeflow-profiles: [describe](https://pastebin.canonical.com/p/xrRcG9my9G/) [logs](https://pastebin.canonical.com/p/9kShCfBSbb/)

[Juju status:](https://pastebin.canonical.com/p/q6Fbg2SWTy/)

**Comment by DnPlas** [comment]
Hi @aym-frikha, this is a known issue, even in [upstream](https://github.com/kubeflow/manifests/issues/2087). The [workaround](https://github.com/kubeflow/manifests/issues/2087#issuecomment-1101482095) is mentioned in that doc.

**Comment by aym-frikha** [comment]
Thanks a lot @DnPlas , I will try that out.

**Comment by aym-frikha** [comment]
Thanks a lot @DnPlas , the workaround works fine, I just created a [PR](https://github.com/canonical/bundle-kubeflow/pull/487) but not sure if this is the way you want to follow.
