### ISSUE TITLE
Istio-pilot stuck waiting, "installing agent" on baremetal

### ISSUE THREAD

**Issue by asbalderson** [canonical/bundle-kubeflow#496]
On baremetal deployments of kubernetes 1.22 with charmed kubeflow 1.6/stable SQA is seeing istio pilot get stuck with the message "installing agent"

Looking at the logs in the pods, the unit actually seems to have the agent up, the charm is able to finish coming up and idle out, but the status never updates.

Here is a juju crashdump from the Kubernetes, the workers have logs for all the running pods:
https://people.canonical.com/~alexb/juju-crashdump-kubernetes-maas-2022-09-17-04.07.29.tar.gz

**Comment by DomFleischmann** [comment]
Hey @asbalderson, this seems to be an issue related to juju itself, what version of juju where you running? If the charm is at the "installing agent" stage none of our code has been executed yet, so we don't really have much control around that.

**Comment by asbalderson** [comment]
Thanks @DomFleischmann I'll follow up with the juju team then

**Comment by ca-scribner** [comment]
I think this can be closed, but please reopen if I'm incorrect
