### ISSUE TITLE
Kubeflow installation under a corporate proxy

### ISSUE THREAD

**Issue by 8greg8** [canonical/bundle-kubeflow#497]
## Problem
I was following instructions in the [quickstart guide](https://charmed-kubeflow.io/docs/quickstart) on how to deploy kubeflow on my machine. The instructions worked until I had to deploy kubeflow-lite with juju. juju couldn't connect to charmhub.io. By searching the web I found [the tutorial](https://charmed-kubeflow.io/tutorials/deploy-kubeflow-on-microk8s-behind-a-web-proxy#6-deploy-and-bootstrap-juju) on how to deploy Charmed Kubeflow behind a web proxy. The tutorial didn't help as the issue couldn't be resolved. There are also stale issues referring to the same problem:

- [Enabling kubeflow behind a proxy fails](https://github.com/canonical/microk8s/issues/991)
- [Behind Proxy Can't install Kubeflow](https://github.com/canonical/microk8s/issues/1081)

## Fix
Following suggestions from:

- [juju http-proxy and no_proxy settings](https://askubuntu.com/a/431192)
- [juju-2-0-proxy-for-bootstrap](https://askubuntu.com/a/852871)

and some experimenting, I found out that the proper way is to **configure proxy settings during bootstrap** https://juju.is/docs/olm/create-a-controller#heading--set-model-configuration-keys. In that case, proxy settings are also configured for the controller model. If the controller model doesn't have proper proxy configurations, deployment will not work. This should be added in the tutorial [How to deploy Charmed Kubeflow on MicroK8s behind a web proxy](https://charmed-kubeflow.io/tutorials/deploy-kubeflow-on-microk8s-behind-a-web-proxy#6-deploy-and-bootstrap-juju).

## Additional note
If you are using a CNTLM proxy, it should be run as a docker container in order to run it under a subnet instead of the loopback as stated [here](https://github.com/kubernetes-sigs/kind/issues/2009#issuecomment-762012231). 

## My environment
OS Ubuntu 20.04.1
microk8s version 1.22
juju version 2.9.34
docker version 20.10.18
CNTLM proxy as a docker container from image [robertdebock/docker-cntlm](https://hub.docker.com/r/robertdebock/docker-cntlm/)

**Comment by DomFleischmann** [comment]
Hello @8greg8 thank you so much for opening this issue, I will label it as a bug and see if we can update that documentation.

**Comment by NohaIhab** [comment]
Updated the guide: [How to install Charmed Kubeflow on Microk8s behind a web proxy](https://charmed-kubeflow.io/docs/install-on-microk8s-behind-a-web-proxy). Thank you for raising the issue.
