### ISSUE TITLE
issue with gateway setup

### ISSUE THREAD

**Issue by QtMas** [canonical/bundle-kubeflow#500]
I followed your Quick start guide https://charmed-kubeflow.io/docs/quickstart on a freshly installed Ubuntu 22.04.1 Server VM.
After the setup I had a problem with kfp-api that always went into a CrashLoopBackOff but the the tip at the end of the guide (" Applications in an error state") made it run correctly.
I tried accessing the dashboard but i couldn't so I checked the other issue ("Kubeflow Dashboard can’t be accessed") and after `microk8s.kubectl get gateway -A` I get the response `No resources found` after executing the command 
```cat <<EOF | microk8s.kubectl create -f -
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
 labels:
   app.istio-pilot.io/is-workload-entity: "true"
   app.juju.is/created-by: istio-pilot
 name: kubeflow-gateway
 namespace: kubeflow
 resourceVersion: "2203"
 spec:
 selector:
   istio: ingressgateway
 servers:
 - hosts:
   - '*'
   port:
     name: http
     number: 80
     protocol: HTTP
EOF
```

I get this error :
`error: error validating "STDIN": error validating data: [ValidationError(Gateway.metadata): unknown field "selector" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta_v2, ValidationError(Gateway.metadata): unknown field "servers" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta_v2]; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by software-artisan** [comment]
Hi, There is a solution for this issue here: ( https://github.com/canonical/bundle-kubeflow/issues/494 > https://github.com/canonical/istio-operators/issues/113 ) .  After running the specified workaround command ( `juju run --unit istio-pilot/0 -- "export JUJU_DISPATCH_PATH=hooks/config-changed; ./dispatch"`), the gateway got created.

**Comment by DomFleischmann** [comment]
Thank you @software-artisan  for pointing  @QtMas in the right direction. Given that we have an issue for this and the workaround has been added to the above mentioned quickstart guide I will close this issue.
