### ISSUE TITLE
kfp-api in crash loop backoff

### ISSUE THREAD

**Issue by kaskavel** [canonical/bundle-kubeflow#502]
Solutions QA team has a failed test run where kfp-api is in an error state with the message: crash loop backoff: back-off 40s restarting failed container=ml-pipeline-api-server pod=kfp-api-55bcf49ffb-mlp5c_kubeflow(af675e4f-246c-4173-a5ed-53ec3ab180ed)

The run was on a baremetal machine, running  fkb-master-kubernetes-focal-baremetal-kubeflow SKU and the failure appeared in the kubeflow layer, while deploying the bundle.
 
From the logs we see: 

Sep 23 15:20:06 armaldo containerd[191809]: time="2022-09-23T15:20:06.940653442Z" level=error msg="Failed to destroy network for sandbox \"ce7cc618614ab84f4e43b5de7c106671da71e4b37ad64967aa0bcc8e86b8ebd0\"" error="stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/"
Sep 23 15:20:06 armaldo containerd[191809]: time="2022-09-23T15:20:06.940995741Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:metrics-server-v0.5.0-67dcbd6bdb-bshrz,Uid:e1f37d1a-2cf5-4319-a284-31435c4e3a63,Namespace:kube-system,Attempt:0,} failed, error" error="failed to setup network for sandbox \"ce7cc618614ab84f4e43b5de7c106671da71e4b37ad64967aa0bcc8e86b8ebd0\": stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/"
Sep 23 15:20:06 armaldo kubelet.daemon[230014]: E0923 15:20:06.941331  230014 remote_runtime.go:116] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"ce7cc618614ab84f4e43b5de7c106671da71e4b37ad64967aa0bcc8e86b8ebd0\": stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/"
Sep 23 15:20:06 armaldo kubelet.daemon[230014]: E0923 15:20:06.941444  230014 kuberuntime_sandbox.go:70] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"ce7cc618614ab84f4e43b5de7c106671da71e4b37ad64967aa0bcc8e86b8ebd0\": stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/" pod="kube-system/metrics-server-v0.5.0-67dcbd6bdb-bshrz"
Sep 23 15:20:06 armaldo kubelet.daemon[230014]: E0923 15:20:06.941508  230014 kuberuntime_manager.go:819] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"ce7cc618614ab84f4e43b5de7c106671da71e4b37ad64967aa0bcc8e86b8ebd0\": stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/" pod="kube-system/metrics-server-v0.5.0-67dcbd6bdb-bshrz"
Sep 23 15:20:06 armaldo kubelet.daemon[230014]: E0923 15:20:06.941626  230014 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"metrics-server-v0.5.0-67dcbd6bdb-bshrz_kube-system(e1f37d1a-2cf5-4319-a284-31435c4e3a63)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"metrics-server-v0.5.0-67dcbd6bdb-bshrz_kube-system(e1f37d1a-2cf5-4319-a284-31435c4e3a63)\\\": rpc error: code = Unknown desc = failed to setup network for sandbox \\\"ce7cc618614ab84f4e43b5de7c106671da71e4b37ad64967aa0bcc8e86b8ebd0\\\": stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/\"" pod="kube-system/metrics-server-v0.5.0-67dcbd6bdb-bshrz" podUID=e1f37d1a-2cf5-4319-a284-31435c4e3a63

and

./3/baremetal/var/log/pods/controller-foundations-kubernetes_controller-0_0e111649-06c9-42d8-a87e-ebb6ba2b42fe/api-server/0.log.20220923-164216:2022-09-23T16:40:25.798316703Z stderr F 2022-09-23 16:40:25 DEBUG juju.apiserver.controller.caasunitprovisioner provisioner.go:675 unit updates: []params.ApplicationUnitParams{params.ApplicationUnitParams{ProviderId:"c011d289-c1df-421f-9243-d26c13ce493f", UnitTag:"", Address:"192.168.252.139", Ports:[]string(nil), Stateful:false, FilesystemInfo:[]params.KubernetesFilesystemInfo{params.KubernetesFilesystemInfo{StorageName:"juju-data", Pool:"", Size:0x0, MountPoint:"/var/lib/juju", ReadOnly:false, FilesystemId:"juju-data-dir", Status:"attached", Info:"", Data:map[string]interface {}(nil), Volume:params.KubernetesVolumeInfo{VolumeId:"juju-data-dir", Pool:"", Size:0x0, Persistent:false, Status:"attached", Info:"", Data:map[string]interface {}(nil)}}, params.KubernetesFilesystemInfo{StorageName:"juju-data", Pool:"", Size:0x0, MountPoint:"/usr/bin/juju-run", ReadOnly:false, FilesystemId:"juju-data-dir", Status:"attached", Info:"", Data:map[string]interface {}(nil), Volume:params.KubernetesVolumeInfo{VolumeId:"juju-data-dir", Pool:"", Size:0x0, Persistent:false, Status:"attached", Info:"", Data:map[string]interface {}(nil)}}}, Status:"error", Info:"crash loop backoff: back-off 20s restarting failed container=ml-pipeline-persistenceagent pod=kfp-persistence-65649bb9bb-f8r87_kubeflow(c011d289-c1df-421f-9243-d26c13ce493f)", Data:map[string]interface {}(nil)}}

Test run: 

https://solutions.qa.canonical.com/testruns/testRun/31db88c9-c644-44e0-9afa-24ff89a4a3ee

Logs: 

https://oil-jenkins.canonical.com/artifacts/31db88c9-c644-44e0-9afa-24ff89a4a3ee/index.html

**Comment by DomFleischmann** [comment]
Hello @kaskavel looking at these logs it looks to me like something broke on the kubernetes layer underneath, what makes you believe this is an issue on the Kubeflow side?

**Comment by JyothsnaPendyala** [comment]
![image](https://user-images.githubusercontent.com/100350083/193197067-f6ef26b6-17f7-416f-af9d-19f4f9aefa3a.png)
Hi everyone. Even I am getting the same error message. Can anyone help me with this?

**Comment by kaskavel** [comment]
hello @DomFleischmann, 

Thanks for taking a look at this. 

I couldn't tell from the logs where exactly is the problem. Where would you suggest to transfer this?

**Comment by DomFleischmann** [comment]
@JyothsnaPendyala can you please check the logs of the kfp-api pod, to make sure this is the same issue? There can be multiple reasons for a crash loop backoff. 

@kaskavel i would say this is an isssue with the k8s layer underneath, in this case charmed kubernetes?

**Comment by kaskavel** [comment]
closing this and will replicate it in charmed-kubernetes. 

Thanks for taking a look.

**Comment by Basdbruijne** [comment]
I opened a related issue in [LP: #1992987](https://bugs.launchpad.net/charm-kubernetes-worker/+bug/1992987)
