### ISSUE TITLE
AKS installation and some questions

### ISSUE THREAD

**Issue by jruokola** [canonical/bundle-kubeflow#507]
Hi,

I've been testing installing kubeflow-lite bundle locally on microk8s and got it somewhat working on my company macbook. I've now been testing it with Azure AKS but I have some questions about the bundle.
1) The dashboard doesn't seem to be accessible without port forwarding and only the homepage works. /jyputer etc won't load. 

2) The istio-ingressgateway-operator, mentioned in [installation_guide_for_aks](https://ubuntu.com/tutorials/install-kubeflow-on-azure-kubernetes-service-aks#7-final-deployment-steps)  is not deployed with the newest bundle to the cluster. There is a pod running istio-ingressgateway-workload which is a LoadBalancer not an ingress.
All the pods and services are running without errors but definetely something is missing since I'm not able to access the dashboard via the load balancer publicIP. I'm not that familiar with istio yet so I'm not sure if I should try to install the operator manually or what to try as a workaround.

`
`❯ kubectl get pods -n kubeflow

NAME                                             READY   STATUS    RESTARTS      AGE
admission-webhook-6d76dfcf8f-6zf8r               1/1     Running   0             18h
admission-webhook-operator-0                     1/1     Running   0             18h
argo-controller-76f7fb6d65-hzcsr                 1/1     Running   0             18h
argo-controller-operator-0                       1/1     Running   0             18h
argo-server-678f468b4d-7pzpl                     1/1     Running   0             18h
argo-server-operator-0                           1/1     Running   0             18h
dex-auth-0                                       2/2     Running   0             18h
istio-ingressgateway-0                           1/1     Running   0             18h
istio-ingressgateway-workload-7cbf5464b7-zpq74   1/1     Running   0             18h
istio-pilot-0                                    1/1     Running   0             18h
istiod-8f9d76cdb-7d88z                           1/1     Running   0             18h
jupyter-controller-75c98976b4-rt26x              1/1     Running   0             18h
jupyter-controller-operator-0                    1/1     Running   0             18h
jupyter-ui-6b5d948679-4zfrc                      1/1     Running   0             18h
jupyter-ui-operator-0                            1/1     Running   0             18h
katib-controller-5bfbd65967-fbfsp                1/1     Running   0             18h
katib-controller-operator-0                      1/1     Running   0             18h
katib-db-0                                       1/1     Running   0             18h
katib-db-manager-5d9559456b-7lf2w                1/1     Running   0             18h
katib-db-manager-operator-0                      1/1     Running   0             18h
katib-db-operator-0                              1/1     Running   0             18h
katib-ui-5d6985fc4c-mgfwn                        1/1     Running   0             18h
katib-ui-operator-0                              1/1     Running   0             18h
kfp-api-79fbccbd48-dtqt7                         1/1     Running   0             18h
kfp-api-operator-0                               1/1     Running   0             18h
kfp-db-0                                         1/1     Running   0             18h
kfp-db-operator-0                                1/1     Running   0             18h
kfp-persistence-67b7956f55-9pmtd                 1/1     Running   3 (18h ago)   18h
kfp-persistence-operator-0                       1/1     Running   0             18h
kfp-profile-controller-fbfd48f8c-mfpm4           1/1     Running   0             18h
kfp-profile-controller-operator-0                1/1     Running   0             18h
kfp-schedwf-5cf78fdd97-7q4jm                     1/1     Running   0             18h
kfp-schedwf-operator-0                           1/1     Running   0             18h
kfp-ui-7bfb44b6fd-zpp8c                          1/1     Running   0             18h
kfp-ui-operator-0                                1/1     Running   0             18h
kfp-viewer-9449456c9-zfwjt                       1/1     Running   0             18h
kfp-viewer-operator-0                            1/1     Running   0             18h
kfp-viz-784bc7c5df-spqbb                         1/1     Running   0             18h
kfp-viz-operator-0                               1/1     Running   0             18h
kubeflow-dashboard-76c7f47dd-q74j5               1/1     Running   0             18h
kubeflow-dashboard-operator-0                    1/1     Running   0             18h
kubeflow-profiles-79fbf88cd7-x46tm               2/2     Running   0             18h
kubeflow-profiles-operator-0                     1/1     Running   0             18h
kubeflow-roles-0                                 1/1     Running   0             18h
kubeflow-volumes-5497fdb799-xn42d                1/1     Running   0             18h
kubeflow-volumes-operator-0                      1/1     Running   0             18h
metacontroller-operator-0                        1/1     Running   0             18h
metacontroller-operator-charm-0                  1/1     Running   0             18h
minio-0                                          1/1     Running   0             18h
minio-operator-0                                 1/1     Running   0             18h
modeloperator-675d94b4ff-zwj4s                   1/1     Running   0             18h
oidc-gatekeeper-d7f57d8b6-b8p9x                  1/1     Running   0             18h
oidc-gatekeeper-operator-0                       1/1     Running   0             18h
seldon-controller-manager-69d7ffb57f-lm6nl       1/1     Running   0             18h
seldon-controller-manager-operator-0             1/1     Running   0             18h
tensorboard-controller-operator-0                1/1     Running   0             18h
tensorboards-web-app-555749bcc6-z5lff            1/1     Running   0             18h
tensorboards-web-app-operator-0                  1/1     Running   0             18h
training-operator-0                              2/2     Running   0             18h
❯ kubectl get svc/istio-ingressgateway -n kubeflow
NAME                   TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)     AGE
istio-ingressgateway   ClusterIP   10.0.18.255   <none>        65535/TCP   18h
❯ kubectl patch role -n kubeflow istio-ingressgateway-operator -p '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"name":"istio-ingressgateway-operator"},"rules":[{"apiGroups":["*"],"resources":["*"],"verbs":["*"]}]}'

Error from server (NotFound): roles.rbac.authorization.k8s.io "istio-ingressgateway-operator" not found``

**Comment by jruokola** [comment]
As an update since the controller doesn't get installed I tried adding the role to the workload node. It didn't have an effect, also the LoadBalancer setup is a little bit difficult for me to understand. The http traffic is routed from 80 > 8080 and the kubernetes dashboard would internally be using 8082. Is this by design or is the LoadBalancer config bugged on this version?

**Comment by DomFleischmann** [comment]
Hey @jruokola unfortunately we didn't update this tutorial with the latest version of Kubeflow 1.6, therefore the instructions have changed a bit. We will address this as soon as possibel.

For now I would recommend you using the instructions  in our [documentation](https://charmed-kubeflow.io/docs/install).

Regarding your issue, the role is not needed anymore in the latest version, the istio-ingressgateway-workload service is the one you are looking for. It is of type loadbalancer and it's external ip is the one you have to set in dex and oidc. Afterwards you will have to access the dashboard through that ip. All traffic to the dashboard needs to go through istio, else things won't work correctly.

**Comment by Jakedismo** [comment]
Got back on the topic after a pause was wondering this part 
`2. Find the IP address of the Kubeflow dashboard
To find the IP address of the Kubeflow dashboard for your deployment run:

kubectl get services -n kubeflow
where kubeflow is the name you gave to your Juju model, and hence the namespace of your Kubeflow deployment.`

The only exposed IP in my AKS Kubeflow deployment is istio-ingressgateway-workloads pod, the documentation expects that the Kubeflow dashboard has an exposed public URL?

**Comment by Jakedismo** [comment]
Port-forwarding and trying to access Kubeflow results in to this ipv6 error:
`kubectl port-forward -n ${NAMESPACE} svc/istio-ingressgateway-workload 8080:80                                                             ─╯
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080
Handling connection for 8080
E1104 15:25:02.660703   17442 portforward.go:406] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 86085aa40a6d491f25f9dc94f5b7423013d266b0dfcfe53706c6b622a3dd9f89, uid : failed to execute portforward in network namespace "/var/run/netns/cni-4e8e69b5-1876-02ae-3a53-54f8c616cd24": failed to connect to localhost:8080 inside namespace "86085aa40a6d491f25f9dc94f5b7423013d266b0dfcfe53706c6b622a3dd9f89", IPv4: dial tcp4 127.0.0.1:8080: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found
E1104 15:25:02.660708   17442 portforward.go:406] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 86085aa40a6d491f25f9dc94f5b7423013d266b0dfcfe53706c6b622a3dd9f89, uid : failed to execute portforward in network namespace "/var/run/netns/cni-4e8e69b5-1876-02ae-3a53-54f8c616cd24": failed to connect to localhost:8080 inside namespace "86085aa40a6d491f25f9dc94f5b7423013d266b0dfcfe53706c6b622a3dd9f89", IPv4: dial tcp4 127.0.0.1:8080: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found
E1104 15:25:02.663085   17442 portforward.go:234] lost connection to pod
Handling connection for 8080
E1104 15:25:02.663990   17442 portforward.go:346] error creating error stream for port 8080 -> 8080: EOF`

**Comment by Jakedismo** [comment]
Found a fix 
https://github.com/canonical/bundle-kubeflow/issues/494

**Comment by DnPlas** [comment]
Closing as @Jakedismo [found a fix](https://github.com/canonical/bundle-kubeflow/issues/507#issuecomment-1305215703). Feel free to re-open if the issue persists.
