### ISSUE TITLE
[KF v1.6] Cannot setup remote access

### ISSUE THREAD

**Issue by hoangtnm** [canonical/bundle-kubeflow#508]
Hi, I'm installing Charmed Kubeflow v1.6 on my local server and I'd like to access the dashboard remotely via `http://IP:PORT`. I tried to follow [Set up remote access](https://discourse.charmhub.io/t/set-up-remote-access/5606) by [robgibbon](https://discourse.charmhub.io/u/robgibbon) and [Set up remote access
](https://charmed-kubeflow.io/tutorials/setting-up-remote-access#1-overview) by Canonical, both of which seem to have contents. However, I cannot access the dashboard via `http://IP:PORT`. Because I have only one machine, I only followed `Enable MicroK8s ingress addon`, `Reconfigure the Charmed Kubeflow public URL` and skip anything related to Dnsmasq, but it doesn't work as described in the [Set up remote access](https://discourse.charmhub.io/t/set-up-remote-access/5606) by [robgibbon](https://discourse.charmhub.io/u/robgibbon) post, but no one replied. Do you have any idea? Thank you.

**Comment by DnPlas** [comment]
Hi @hoangtnm, I am assuming you are not behind a proxy. If that is the case, then accessing the dashboard should be fairly easy:
1. Deploy Charmed Kubeflow as mentioned [here](https://charmed-kubeflow.io/docs/install). If you are using microk8s, please also [enable metallb](https://microk8s.io/docs/addon-metallb).
2. Once everything is up and running, follow the instructions to [access the dashboard](https://charmed-kubeflow.io/docs/dashboard)
3. After that, do not forget to [configure auth](https://charmed-kubeflow.io/docs/install#heading--set-url-in-authentication-methods-)
4. You should be able to access the dashboard in your web browser.

If after all this you are still running into issues, please let us know.

**Comment by mohamedFaris47** [comment]
Hi, I'm working on a VM and from there I deployed Kubeflow using juju as mentioned [here](https://charmed-kubeflow.io/docs/install#heading--remote-deployments). All pods are working and running no problem, but I'm stuck at the [proxy step](https://charmed-kubeflow.io/docs/install#heading--remote-deployments) to access the KF dashboard.
Is there an easier way to access the dashboard, or could you explain how the proxy steps work? Thanks

**Comment by DnPlas** [comment]
For proxy settings, please follow [this guide](https://charmed-kubeflow.io/docs/install-on-microk8s-behind-a-web-proxy). Let us know if that solves it for you.

**Comment by mohamedFaris47** [comment]
Thanks for the reply. I've deployed it with kustomize and the manifest instead of juju.

**Comment by DnPlas** [comment]
Understood, if you have more questions about juju and charmed kubeflow, feel free to open a new PR. Thanks!
