### ISSUE TITLE
metadata-grpc-operator is in maintainance state

### ISSUE THREAD

**Issue by JyothsnaPendyala** [canonical/bundle-kubeflow#510]
Hi. I have deployed metadata-grpc-operator using the command "juju deploy metadata-grpc". The pod status is not changing from maintainance state. 

![image](https://user-images.githubusercontent.com/100350083/195007347-ffb65caf-9639-4cba-8b61-8167382b7e78.png)

juju version : 2.9.34-ubuntu-amd64

**Comment by ca-scribner** [comment]
Hi @JyothsnaPendyala, sorry for the issue.  I think that is an old charm that is not maintained.  Are you looking to deploy an mlmd store?  [this charm](https://charmhub.io/mlmd) might work, but we haven't been using it lately as it hasn't been in strong use by kubeflow components.

**Comment by ca-scribner** [comment]
I'm going to close this issue as I think the new charm is what you're looking for, but if you run into problems with the mlmd charm please open an issue [in the mlmd repo](https://github.com/canonical/mlmd-operator).  Thanks!
