### ISSUE TITLE
Kubeflow 1.6.1

### ISSUE THREAD

**Issue by pkluska** [canonical/bundle-kubeflow#512]
Dear team!

First of all thank you for your work in bundling Kubeflow!

I was wondering if you are planning to release Kubeflow 1.6.1 
https://groups.google.com/g/kubeflow-discuss/c/amsxyXbY_nk/m/FaWxOd4VBAAJ
which has a bugfix for Notebook Culling - https://github.com/kubeflow/kubeflow/issues/6648

Thank you

**Comment by pkluska** [comment]
Dear Team,

Is there any update on that? Unfortunately, culling makes restarting stopped notebooks impossible via UI, which is a huge issue for using the Notebooks component.

Can I help somehow?

**Comment by ca-scribner** [comment]
Sorry, we do expect to get this out in the next few days.  Some workarounds are also mentioned [here](https://github.com/canonical/notebook-operators/issues/63)

**Comment by pkluska** [comment]
@ca-scribner can we get an update on that please?

**Comment by ca-scribner** [comment]
Sorry for the slow response @pkluska.  Things took longer than we expected, but the fixes are done an being pushed to the `1.6/edge` channels now for testing.  Barring something unexpected, it should be ready this week or beginning of next week and be pushed to `1.6/stable`.

I wouldn't recommend testing anything from the `1.6/edge` channel for a day or two though, as a few are still getting pushed (hopefully done today)

**Comment by pkluska** [comment]
@ca-scribner I am looking forward for release. Thank you for the updates, I really appreciate your work on that!

**Comment by ca-scribner** [comment]
@pkluska you're welcome!  As of ~5 min ago, 1.6.1 is in charmhub's `1.6/stable` track (`juju deploy kubeflow[-lite] --channel 1.6/stable --trust`)!  I'll close this issue, but please reopen if anything is amiss.  Thank you for your patience!
