### ISSUE TITLE
kubeflow deployment is stuck at this level 

### ISSUE THREAD

**Issue by moula** [canonical/bundle-kubeflow#537]
Hi, kubeflow deployment is stuck at this level . 
The problem is related to: istio-pilot
Thanks for your help.
![Capture d’écran du 2023-01-20 10-45-59](https://user-images.githubusercontent.com/1804815/213665283-a41eb304-34d6-44e3-9ede-3f0939e791de.png)

**Comment by misohu** [comment]
Hi @moula thanks for reaching out can you send us `juju debug-log --replay` logs ... also I am interested in `kubectl get po --all-namespaces` state. Can you also let me know what are the available resources in cluster? Also how did you deploy kubeflow? Thanks

**Comment by moula** [comment]
Hi @misohu . I  use cluster 3 Servers ( Ubuntu 22.04 && Ubuntu 20.04 - "same problem ") on promise witch MAAS.  I tested with juju 2.9 and juju 3.1 with cluster microk8s. 
![juju debug-log --replay logs ](https://user-images.githubusercontent.com/1804815/214033555-fc33151d-598f-4fb0-823d-40aaf3316a97.png)
![Cluster-Microk8s+maas](https://user-images.githubusercontent.com/1804815/214033610-a6fe0799-c3c6-4977-b0ba-7a2c088332bd.png)
![kubectl get po --all-namespaces ](https://user-images.githubusercontent.com/1804815/214033658-b9829861-2b18-43a6-bb01-383010ca36c0.png)

**Comment by moula** [comment]
![Capture d’écran du 2023-01-23 13-05-23](https://user-images.githubusercontent.com/1804815/214035668-d73b9f36-6075-4ea3-8ad2-07d83aafb2fd.png)
Merci.

**Comment by Barteus** [comment]
I have a similar case and after some investigation, the relationship between katib-ui and istio-pilot passes incorrect information.
@misohu can it be there is a race condition in the main() method?

**Comment by pprados** [comment]
I suppose, the problem come with the version of microk8s.
Try with:

`sudo snap install microk8s --channel=1.22/stable --classic`

**Comment by Barteus** [comment]
I'm using Charmed Kubernetes with version 1.24 with 3 control plane nodes and 3 workers with GPUs.

**Comment by moula** [comment]
It works with microk8s 1.24 
![Capture d’écran du 2023-01-26 16-40-23](https://user-images.githubusercontent.com/1804815/214880228-c0bd68bf-c204-44c5-b538-7a99be3d2cd5.png)

**Comment by misohu** [comment]
I tried deployment with charmed kubernetes couple of times today and I was not able to replicate ... is it possible to send full dump of logs `juju debug-log --replay > dump.log`. I am also wondering what is the disk space for the nodes in the cluster? Is it possible that some node was running out of disk space?

**Comment by moula** [comment]
hi @misohu Deploying Kubeflow on My microk8s 1.24 + Nvidia GPU cluster works, just one error remains: "Kubeflow-gateway not found". Portainer+Keycloak also work. 
![Capture d’écran du 2023-01-28 16-27-25](https://user-images.githubusercontent.com/1804815/215275011-bae66b0e-bfda-45ea-b9ec-00d766fa86e1.png)
![Capture d’écran du 2023-01-28 16-24-41](https://user-images.githubusercontent.com/1804815/215275025-a12f8e70-0cc7-467e-8d4f-e6fe04eaf66a.png)
![Capture d’écran du 2023-01-28 16-24-03](https://user-images.githubusercontent.com/1804815/215275037-4cff1f83-dccb-418e-8487-c0aaace3661e.png)
![Capture d’écran du 2023-01-28 16-23-28](https://user-images.githubusercontent.com/1804815/215275048-672c2b26-8e66-46f9-a865-42bc106d544b.png)
![Capture d’écran du 2023-01-28 16-22-54](https://user-images.githubusercontent.com/1804815/215275064-2a3954cf-f0e7-4bd2-aa63-ce4b96c920aa.png)

**Comment by moula** [comment]
For hard disks I put 2 for each server (1st of 120G). I will add OpenEBS on the second.

**Comment by Barteus** [comment]
For the gateway issue here is a workaround: 
```
juju run --unit istio-pilot/0 -- "export JUJU_DISPATCH_PATH=hooks/config-changed; ./dispatch"
```

**Comment by Barteus** [comment]
In my case, the katib-ui was not working because it was stuck on downloading the schema for relation from github. More details in this ticket: https://github.com/canonical/bundle-kubeflow/issues/541

**Comment by moula** [comment]
It works on jammy but not on focal!!! 
![Capture d’écran du 2023-01-31 11-09-24](https://user-images.githubusercontent.com/1804815/215765300-7fd5c90a-c49c-4aa6-be7d-023443d077d5.png)
![Capture d’écran du 2023-01-31 11-04-29](https://user-images.githubusercontent.com/1804815/215765305-f800fb81-8518-4094-947f-9d11d8aa68e2.png)
![Capture d’écran du 2023-01-31 10-59-45](https://user-images.githubusercontent.com/1804815/215765312-9179ea19-4a82-4f42-ad01-e1569bd1d6c2.png)

**Comment by moula** [comment]
Bonsoir @ca-scribner.  Sorry on my beremetal platform it just works on jammy. Currently I work on Microstack and Osm... the latest version of microstack also works on Jammy and only with microk8s 1.25 while kubeflow is on microk8s 1.24. I promise I'll finish with microstack-osm and I'll come back to kubeflow to retest with focal. Sorry but I'm working on a lot of projects at the same time :-).

**Comment by moula** [comment]
Hi @ca-scribner Everything works with many other bundles on the same caas. I stayed on Jammy. Thanks.
https://www.linkedin.com/feed/update/urn:li:activity:7033374271213043713/

**Comment by ca-scribner** [comment]
That's great to hear, @moula, thanks for your engagement!  I'm going to close this issue then, but if I'm wrong please reopen.

Also, not exactly related, but thanks for your quick and detailed responses on this issue.  We as a team were just discussing this issue and someone mentioned how they really liked helping you! :)
