### ISSUE TITLE
No guide avilable to install Kubeflow offline on Microk8s in a corporate envirement behind proxy

### ISSUE THREAD

**Issue by vivekjainmaiet** [canonical/bundle-kubeflow#540]

**Comment by ca-scribner** [comment]
Hi @vivekjainmaiet, does [this guide](https://charmed-kubeflow.io/docs/deploy-kubeflow-on-microk8s-behind-a-web-proxy) address what you need?

**Comment by ca-scribner** [comment]
It isn't quite what you're looking for I dont think as it is more aimed at a proxy but still having connectivity

**Comment by DnPlas** [comment]
Duplicate of #497
