### ISSUE TITLE
Unit goes to `BlockedStatus` on conditions that cannot be resolved by a human operator

### ISSUE THREAD

**Issue by misohu** [canonical/bundle-kubeflow#549]
Sidecar charms go into `BlockedStatus` when:

* The charm is attempting to [update layers example](https://github.com/canonical/kubeflow-profiles-operator/blob/main/src/charm.py#L218)
* The workload container is [not ready example](https://github.com/canonical/kubeflow-profiles-operator/blob/main/src/charm.py#L223) (see also [here](https://github.com/canonical/kubeflow-profiles-operator/blob/main/src/charm.py#L240))

A `BlockedStatus` means a human operator is needed for unblocking the unit through certain actions, in the case of the above, there is little to nothing a human operator can do, causing the unit to be in such state without a proper resolution.

**List of infected charms**:
- [KubeflowProfiles](https://github.com/canonical/kubeflow-profiles-operator)
- [KubeflowDashboard](https://github.com/canonical/kubeflow-dashboard-operator/blob/main/src/charm.py#L175)
- [Seldon](https://github.com/canonical/seldon-core-operator/blob/main/src/charm.py#L310)
- [TrainingOperator](https://github.com/canonical/training-operator/blob/main/src/charm.py#L179)
- [MLflow](https://github.com/canonical/mlflow-operator/blob/KF-715-mlflow-v211/src/charm.py#L100)

#### Possible fix

Change the status to `Waiting` or `Error` when needed with appropriate messaging.

**Comment by ca-scribner** [comment]
@beliaev-maksim raised [this training operator code](https://github.com/canonical/training-operator/blob/95f0dd25892b9970c898a0d0f6af48327f80534a/src/charm.py#L150) as a candidate
