### ISSUE TITLE
Documentation - Kubeflow Install Guide, expand option is empty

### ISSUE THREAD

**Issue by Barteus** [canonical/bundle-kubeflow#551]
we are missing something here (empty expand) - https://charmed-kubeflow.io/docs/get-started-with-charmed-kubeflow
![image](https://user-images.githubusercontent.com/20493786/222714083-b5d978fd-5357-4801-981b-ae9b95475f85.png)

Same in the "Expand to troubleshoot: The Kubeflow dashboard can't be accessed"

Browser: Chrome, OS: Ubuntu

**Comment by andreeamun** [comment]
![image](https://user-images.githubusercontent.com/77149394/227192803-b76c80a6-b437-414e-8e22-cd100965776b.png)
This has been fixed
