### ISSUE TITLE
istio-pilot   waiting for ip address

### ISSUE THREAD

**Issue by wizardrshah** [canonical/bundle-kubeflow#559]
Stuck with istio-pilot on installating agent 

Unit stuck at waiting for ip address

<img width="794" alt="image" src="https://user-images.githubusercontent.com/91518196/225688992-002930e4-6278-4344-895f-c3329adb3863.png">

**Comment by moula** [comment]
Me too ( he always wants to have a separate room :-) ) 
![Capture d’écran du 2023-03-17 09-36-38](https://user-images.githubusercontent.com/1804815/225862325-fbbde631-252f-4a28-8ec7-c9e5daf75772.png)

**Comment by Barteus** [comment]
Can you share the microk8s status? Check if you have MetalLB enabled.

**Comment by h-mactavish** [comment]
Hi @Barteus ..Yes we have metallb enabled
![metallb](https://user-images.githubusercontent.com/52399098/225910345-fa36893b-0b24-4782-b554-faeba7bbfb7d.png)

**Comment by moula** [comment]
The problem comes from the image of Metallb 
![Capture d’écran du 2023-03-17 14-46-26](https://user-images.githubusercontent.com/1804815/225924958-dfab7fc9-f8db-4ab5-b299-982775ff0fd6.png)

**Comment by wizardrshah** [comment]
@ca-scribner  I am unable to find the microk8s add-on configuration file where I can change the image link.

**Comment by wizardrshah** [comment]
A workaround is posted here in microk8s repository:

https://github.com/canonical/microk8s/issues/3855#issue-1629716570

**Comment by NohaIhab** [comment]
Fix is now in microk8s 1.24/stable
