### ISSUE TITLE
Basic dashboard has invalid queries

### ISSUE THREAD

**Issue by facundofc** [canonical/bundle-kubeflow#567]
The only two graphs the basic dashboard has, "Total number of notebook running" and "Total number of notebook created," are sending wrong queries causing them to show "no data." The query is:

```
notebook_running{juju_application="()",juju_model="(kubeflow|cos)",juju_model_uuid="()",juju_unit="()"}
```

If I remove all the `juju_*` filters except for the `juju_model` one, the panel starts showing data.

**Comment by i-chvets** [comment]
Tested using [this](https://github.com/canonical/kubeflow-examples/tree/main/kubeflow-cos-integration)
Correct values are displayed.

**Comment by nishant-dash** [comment]
Its not exactly clean to me, what the fix for this is? Are you saying that the kf cos integration repo you referred to has no issues when viewing kubeflow related dashboards etc... in cos?

**Comment by facundofc** [comment]
FTR I belie [this](https://github.com/canonical/grafana-k8s-operator/commit/c827a1ae0ea284409dd19f8af8fe0cf1b8fdb89a#diff-69ab969563d8e0133c6a9e31a0a235f99a626617c456bc84bb1bd25899e36170) commit is the one which fixes this issue.
