### ISSUE TITLE
Configuring Charmed Kubeflow 1.7 with SSL removes all authentication

### ISSUE THREAD

**Issue by ca-scribner** [canonical/bundle-kubeflow#570]
Tracking bug from [here](https://discourse.charmhub.io/t/kubeflow-1-7-ssl-and-dex-auth/9574).  All discussion will be done in the original charmhub thread.

**Comment by beliaev-maksim** [comment]
@ca-scribner @i-chvets were you able to reproduce it?
or we have not touch it yet?

**Comment by ca-scribner** [comment]
I don't think I reproduced it.  I think by looking at the code I was pretty sure it was a legit bug, but didn't go further.  

This might have been fixed by canonical/istio-operators#261, so first step would be to check whether it is still a bug.

**Comment by beliaev-maksim** [comment]
@ca-scribner and need to add an integration (or bundle test) to ensure that it will not happen
