### ISSUE TITLE
JWT stays valid even after logout

### ISSUE THREAD

**Issue by nishant-dash** [canonical/bundle-kubeflow#579]
After a user logs out from the Kubeflow dashboard the JWT token stays valid.
it is not invalidated by placing it in a revoked/invalid state/list, so not only can it be reused by a malicious actor, 
but when the user opens the dashboard URL it is still logs the user in, and if the user wants to log back as a different user perhaps, it requires a manual deletion of the web token.

### Env
```console
Charm                      Channel           Revision
-------------------------  --------------  ----------
admission-webhook          1.6/stable              60
argo-controller            3.3/stable              99
argo-server                3.3/stable              45
dex-auth                   2.31/stable            129
grafana-agent-k8s          latest/edge             31
istio-ingressgateway       1.11/stable            285
istio-pilot                1.11/stable            302
jupyter-controller         1.6/stable             163
jupyter-ui                 1.6/stable             124
katib-controller           0.14/stable             92
katib-db                   latest/stable           35
katib-db-manager           0.14/stable             66
katib-ui                   0.14/stable            151
kfp-api                    2.0/stable             144
kfp-db                     latest/stable           35
kfp-persistence            2.0/stable             141
kfp-profile-controller     2.0/stable             125
kfp-schedwf                2.0/stable             155
kfp-ui                     2.0/stable             144
kfp-viewer                 2.0/stable             152
kfp-viz                    2.0/stable             134
kubeflow-dashboard         1.6/stable             183
kubeflow-profiles          1.6/stable              94
kubeflow-roles             1.6/stable              49
kubeflow-volumes           1.6/stable              84
metacontroller-operator    2.0/stable              48
minio                      ckf-1.6/stable          99
namespace-node-affinity    0.1/beta                 5
oidc-gatekeeper            ckf-1.6/stable          76
seldon-controller-manager  1.14/stable             92
tensorboard-controller     1.6/stable              69
tensorboards-web-app       1.6/stable              71
training-operator          1.5/stable              65
```

**Comment by kimwnasptd** [comment]
Hi @nishant-dash, indeed the logout functionality was not working as expected in Charmed KF 1.6, but this is fixed in Charmed KF 1.7.

On a technical note, I think JWTs are unrelated though. The CentralDashboard should be using a cookie on the browser itself, to persist the information of whether the user is logged in or not. Do you confirm? If not where did you see a JWT?

Again this should be fixed in KF 1.7, but will keep open for a bit to confirm we have the same understanding

**Comment by nishant-dash** [comment]
Hi @kimwnasptd, im seeing a _xsrf token that still stays valid even after I logout

**Comment by beliaev-maksim** [comment]
xsrf is a cross site reference token that ensure that XS attack cannot be performed.

If user session is terminated then xsrf token is useless

**Comment by nishant-dash** [comment]
Hello,

sorry I meant to say that all I see is just my xsrf token. I dont see any JWT's from the browser POV in terms of authenticatin to dex, atleast not directly without looking at all the query and response headers.

I can check and let you know, but in the meantime, are there any JWTs at play inside the cluster itself that are tied to a user?

**Comment by ah548455** [comment]
> On a technical note, I think JWTs are unrelated though. The CentralDashboard should be using a cookie on the browser itself, to persist the information of whether the user is logged in or not. Do you confirm? If not where did you see a JWT?

We are seeing this token "go to kubeflow "-> Developers Tools-> Cookies -> authservice_session. For your reference, attaching screenshot here with.
Also, when we hit logout, it will expire "authservice_session" when its time to live, time should be expired, and it's suppose to be revoke when you logout.
![Screenshot from 2023-05-18 13-09-59](https://github.com/canonical/bundle-kubeflow/assets/11343967/4bbdf036-3ccb-4aa9-99ab-938190e9c1f4)

**Comment by beliaev-maksim** [comment]
@ah548455 and can you reuse this cookie to login again?

because I expect server to compare cookie value and not pass you through
