### ISSUE TITLE
kserve-webhook-server-service: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by sergii-bond** [canonical/bundle-kubeflow#587]
Versions: microk8s 1.24, kubeflow 1.7. 

I was following a User Guide of KServe, and my test according to the top of the page https://kserve.github.io/website/0.10/modelserving/v1beta1/tensorflow/ failed.
```
kubectl apply -n my_namespace -f tensorflow.yaml 
Error from server (InternalError): error when creating "tensorflow.yaml": Internal error occurred: failed calling webhook "inferenceservice.kserve-webhook-server.defaulter": failed to call webhook: Post "https://kserve-webhook-server-service.kubeflow.svc:443/mutate-serving-kserve-io-v1beta1-inferenceservice?timeout=10s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "127.0.0.1")
```

Following https://kserve.github.io/website/0.10/developer/developer/#deploy-kserve-from-master-branch, during deployment  kserve needs either `cert-manager` present, or `KSERVE_ENABLE_SELF_SIGNED_CA` environment variable set to `true` for self-signed certificates. 

I chose to try the first option. According to microk8s docs, `cert-manager` is included as core add-on starting from version 1.25, which is not officially supported to work with kubeflow 1.7. So I installed it with kubectl according to https://cert-manager.io/docs/installation/kubectl/.

The installation of `cert-manager` by itself didn't resolve the issue, because kubeflow and kserve-controller have been already installed. After running `juju remove-application kserve-controller`, waiting until it gets removed, and following by `juju deploy --trust kserve-controller --channel=0.10/stable`, the command succeeded:
```
kubectl apply -n my_namespace -f tensorflow.yaml 
inferenceservice.serving.kserve.io/flower-sample created
```

**Comment by DnPlas** [comment]
Hi @sergii-bond, the [**charmed kserve-controller**](https://github.com/canonical/kserve-operators) does not really require any extra components deployed or enabled other than the ones listed in the [README](https://github.com/canonical/kserve-operators#usage). In fact, we do not use `cert-manager` for any of the Charmed Kubeflow components that this team maintains. Please also note that the charmed kserve-controller is different from any component you may deploy from the [KServe website](https://kserve.github.io/website/0.10/developer/developer/#deploy-kserve-from-master-branch). 

That being said, I'd expect the `kserve-controller` to be properly configured and set everything up so you can just run your workloads, in this case your `inferenceservice.serving.kserve.io/flower-sample`. 
It doesn't look like there is an issue with the charmed `kserve-controller`, so I am closing this issue. Please feel free to re-open if you run into the same error while using the charmed `kserve-controller` or if you have more questions.
