### ISSUE TITLE
MetalLB never gets up and ready in Microk8s 1.22

### ISSUE THREAD

**Issue by DnPlas** [canonical/bundle-kubeflow#595]
Due to MetalLB's image registry being removed from Dockerhub, the containers that pull those images never get up and ready (with `Error: ErrImagePull` messages). Although Charmed Kubeflow is not responsible for this issue, we should take care of it as Microk8s 1.22 is not supported anymore by Microk8s.

#### Proposed solution
Patch MetalLB in the cluster so it points to the new registry (quay.io). This should be added in CKF's documentation.

**Comment by ca-scribner** [comment]
For reference, a working deployment uses the images listed in [this yaml](https://github.com/canonical/microk8s-core-addons/blob/main/addons/metallb/metallb.yaml#L426)

**Comment by beliaev-maksim** [comment]
we should not support 1.22 as well
