### ISSUE TITLE
tensorboard-controller blocked waiting for gateway info relation

### ISSUE THREAD

**Issue by asbalderson** [canonical/bundle-kubeflow#597]
Deploying charmed Kubeflow onto charmed k8s on AWS, tensorboard-controller stays blocked waiting for the gateway info relation.  Digging into the pod logs, the kubeflow_istio-pilot unit says that its unable to find the kubeflow-gateway and skipping the gateway relation.

2023-05-10T12:30:00.776801721Z stdout F 2023-05-10T12:30:00.776Z [container-agent] 2023-05-10 12:30:00 ERROR juju-log gateways.networking.istio.io "kubeflow-gateway" not found
2023-05-10T12:30:00.781944756Z stdout F 2023-05-10T12:30:00.781Z [container-agent] 2023-05-10 12:30:00 INFO juju-log Gateway is not created yet. Skip sending gateway relation data.

The deployment is running kubeflow bundle 1.7/stable:336 and running ontop of k8s 1.24.
is it possible that we are missing a configuration somewhere to enable kubeflow-gateway when running ontop of k8s on aws?

I uploaded the kubernetes crashdump here, the logs can be found under the k8s workers in /var/log/pods/
https://people.canonical.com/~alexb/juju-crashdump-kubernetes-aws-2023-05-10-12.29.43.tar.gz

**Comment by i-chvets** [comment]
Please verify if gateway is created:
`microk8s.kubectl -n kubeflow get gateways`

If not, run the following to trigger gateway creation:
`juju run --unit istio-pilot/0 -- "export JUJU_DISPATCH_PATH=hooks/config-changed; ./dispatch"`

**Comment by beliaev-maksim** [comment]
this will be fixed by the next patch
