### ISSUE TITLE
Specifying a nodeselector when creating a notebook with kf 1.6

### ISSUE THREAD

**Issue by nishant-dash** [canonical/bundle-kubeflow#599]
1. What do you want to do?

- We want to able to specify a nodeselector when creating a new notebook. Certain nodes have pvcs or rather requirements, and when spawning notebooks for certain use cases, we would like to specify the node that notebook can fall on.

2. Numbered list of steps that you tried

- Nothing tried as this is more of a request. Is this a feature purely needed in jupyter ui? or can this be applied to k8s in the form of labels to ndoes and then a simple update to the `spawner_ui_config.yaml`  to expose this.

3. What (unexpected) ends up happening?

- N/A

## Environment:
Kubeflow `1.6/stable` (not the current latest stable) on top of k8s `1.24.6` using juju `2.9.42`
```console
Charm                      Channel           Revision
-------------------------  --------------  ----------
admission-webhook          1.6/stable              60
argo-controller            3.3/stable              99
argo-server                3.3/stable              45
dex-auth                   2.31/stable            129
grafana-agent-k8s          latest/edge             31
istio-ingressgateway       1.11/stable            285
istio-pilot                1.11/stable            302
jupyter-controller         1.6/stable             163
jupyter-ui                 1.6/stable             124
katib-controller           0.14/stable             92
katib-db                   latest/stable           35
katib-db-manager           0.14/stable             66
katib-ui                   0.14/stable            151
kfp-api                    2.0/stable             144
kfp-db                     latest/stable           35
kfp-persistence            2.0/stable             141
kfp-profile-controller     2.0/stable             125
kfp-schedwf                2.0/stable             155
kfp-ui                     2.0/stable             144
kfp-viewer                 2.0/stable             152
kfp-viz                    2.0/stable             134
kubeflow-dashboard         1.6/stable             183
kubeflow-profiles          1.6/stable              94
kubeflow-roles             1.6/stable              49
kubeflow-volumes           1.6/stable              84
metacontroller-operator    2.0/stable              48
minio                      ckf-1.6/stable          99
namespace-node-affinity    0.1/beta                 5
oidc-gatekeeper            ckf-1.6/stable          76
seldon-controller-manager  1.14/stable             92
tensorboard-controller     1.6/stable              69
tensorboards-web-app       1.6/stable              71
training-operator          1.5/stable              65
```

**Comment by kavita1205** [comment]
Hi @kimwnasptd ,

1. Yes, I have selected storage class "direct-csi-min-io" as workspace volume(PVC) before launching the notebook.
2. Also, in order to pass nodeselector in notebook pod, I have taken below action :
a) firstly modified configmap "jupyter-ui-config-config" with below configuration value:
```
configurations:
value:
- access-ml-pipeline
- use-nvme-disk
readOnly: false
```
b) Secondly created podDefault.yaml in order to inject nodeSelector in notebook pod during its creation time:
podDefault.yaml
```
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
name: use-nvme-disk
namespace: automative
spec:
selector:
matchLabels:
use-nvme-disk: "true"
desc: "enable direct pv nvme disk"
nodeSelector:
mlgpunode: "true"
```

After running above 2 steps , still I am not seeing nodeSelector being injected into notebook pod. However, the label "use-nvme-disk: "true"" is being shown in notebook pod. But As per my understanding, notebook pod should show nodeselector as "mlgpunode: true".
Kindly suggest here .

Thanks,
Kavita

**Comment by kimwnasptd** [comment]
@Hi @kavita1205, thanks for the context!

First of all the reason you don't see the `nodeSelector` set is because the current PodDefaults API does not support specifying `nodeSelector` 
https://github.com/kubeflow/kubeflow/blob/master/components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go#L27-L89

What I don't understand is why did the Notebook not end up in the "correct" node. I can think of 2 scenarios:
1. There is another Pod using the RWO (is it indeed RWO?) PVC
2. The node itself has taints, which is a common pattern (from what I've seen) for GPU nodes

If it's taints then you could try to create a PodDefault with `tolerations` so that the Notebook Pod can get scheduled in that node.

**Comment by canonikamal** [comment]
Found the limit range for the affected namespace set to:
```
{
  "apiVersion": "v1",
  "kind": "LimitRange",
  "metadata": {
    "annotations": {
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"LimitRange\",\"metadata\":{\"annotations\":{},\"name\":\"resources-limit-range\",\"namespace\":\"automative\"},\"spec\":{\"limits\":[{\"default\":{\"cpu\":1,\"memory\":\"1G\"},\"defaultRequest\":{\"cpu\":0.1,\"memory\":\"100M\"},\"max\":{\"nvidia.com/gpu\":8},\"min\":{\"nvidia.com/gpu\":2},\"type\":\"Container\"},{\"max\":{\"storage\":\"50Gi\"},\"type\":\"PersistentVolumeClaim\"}]}}\n"
    },
    "creationTimestamp": "2023-04-19T12:20:47Z",
    "name": "resources-limit-range",
    "namespace": "automative",
    "resourceVersion": "123992616",
    "uid": "d2c6beca-f06b-4472-b3e5-6b71e62e9acc"
  },
  "spec": {
    "limits": [
      {
        "default": {
          "cpu": "1",
          "memory": "1G",
          "nvidia.com/gpu": "8"
        },
        "defaultRequest": {
          "cpu": "100m",
          "memory": "100M",
          "nvidia.com/gpu": "8"
        },
        "max": {
          "nvidia.com/gpu": "8"
        },
        "min": {
          "nvidia.com/gpu": "2"
        },
        "type": "Container"
      },
      {
        "max": {
          "storage": "50Gi"
        },
        "type": "PersistentVolumeClaim"
      }
    ]
  }
}

```

**Comment by nishant-dash** [comment]
Since the env is using limitrange with the default set to `8` gpus, the 2 istio sidecar containers, init and proxy each add their own request of 8 gpus to a total of 16. This is why a failure to schedule the pod is seen.

Would it be possible to have a charm config for something like this? to use/obey limitranges or to ignore it and have a separate one for istio sidecar injections. (can branch into a different github issue if needed)

**Comment by kimwnasptd** [comment]
@nishant-dash @canonikamal thank you both for the context!

My understanding from the above is that the current situation is unrelated to (Charmed) Kubeflow and it's on how to manage a K8s cluster and do resource management. To my best understanding, there's nothing the Kubeflow Charms can do to block the K8s LimitRange object from modifying specific containers' requests/limits.

Looking at the [spec of the LimitRange](https://github.com/kubernetes/design-proposals-archive/blob/main/resource-management/admission_control_limit_range.md) object I see that there's a `Type: {Pod,Container}` field. What about trying to use the Pod type in the LimitRange object? I understand that the intention behind it is to ensure we limit how many resources are consumed by a specific Pod in the namespace

**Comment by canonikamal** [comment]
Hey @kimwnasptd Your understanding is absolutely correct and custom limitranges created by the user is totally out of the scope of charmed kubeflow. Issue has been resolved and this issue can be closed marking it "resolved". Thanks.
