### ISSUE TITLE
Unable to access Dashboard following install to bare metal

### ISSUE THREAD

**Issue by BenPashley** [canonical/bundle-kubeflow#609]
Hi,

I've spent 2 weeks trying to install Charmed Kubeflow locally on bare metal on 2 different machines and I'm having the same issue.  I follow the following instructions installing the recommended versions.

When I try to access the Kubeflow dashboard via the exposed metallb IP address at http://10.64.140.43.nip.io I get a blank page?  I can access the dashboard using the internal IP address and port but like others have reported, this does not allow me to access any of the deep links for Notebook, Pipeline etc.

Any help would be much appreciated as I've been pulling my hair out trying to get this to work?

Ben

**Comment by kimwnasptd** [comment]
Hi @BenPashley, have you followed a specific guide for this? 

I'd like to have some steps that we could follow in order to reproduce the issue.

Could you also provide us the the outputs from:
```
kubectl get pods -A
kubectl get svc -A
```
As well as
```
juju status --relations
```

**Comment by BenPashley** [comment]
I finally solved the issue!! It was due to my UK internet provider’s router (Virgin Media Hub) interfering with the 10.*.*.* IP address.  There was no obvious reason as firewalls etc the disabled.  Having replaced the router I has no issues.  I hope this helps others setting up their own local installations in the UK as I spent weeks troubleshooting this.

**Comment by kimwnasptd** [comment]
Glad to hear @BenPashley. These kinds of bugs are the toughest to actually debug.

Closing this issue
