### ISSUE TITLE
rocks.canonical.com:5000/kubeflow/examples/mnist-test:latest

### ISSUE THREAD

**Issue by tiansiyuan** [canonical/bundle-kubeflow#629]
It is difficult for me to pull rocks.canonical.com:5000/kubeflow/examples/mnist-test:latest while running pipeline example.

May I have the Docerfile to build it by myself?

Thanks

**Comment by tiansiyuan** [comment]
Is it the following one?

https://github.com/canonical/bundle-kubeflow/blob/main/tests/Dockerfile.mnist

**Comment by orfeas-k** [comment]
Hi Tian, could you give us more information on what you are trying to do exactly and in what context do you try to pull the image? Note that in case you are trying to run the experiments from our [tests](https://github.com/canonical/bundle-kubeflow/tree/0b06bf138c77e74d77d71beef02dcdc4ba0c473a/tests/pipelines) directory, these are not up to date at the moment. You could however try [this fix](https://github.com/canonical/bundle-kubeflow/issues/607#issuecomment-1621202929).

**Comment by tiansiyuan** [comment]
> Hi Tian, could you give us more information on what you are trying to do exactly and in what context do you try to pull the image? Note that in case you are trying to run the experiments from our [tests](https://github.com/canonical/bundle-kubeflow/tree/0b06bf138c77e74d77d71beef02dcdc4ba0c473a/tests/pipelines) directory, these are not up to date at the moment. You could however try [this fix](https://github.com/canonical/bundle-kubeflow/issues/607#issuecomment-1621202929).

Hi, 

Google domains are blocked by the GFW.

**Comment by tiansiyuan** [comment]
> GFW?

Great Firewall

**Comment by i-chvets** [comment]
> Is it the following one?
> 
> https://github.com/canonical/bundle-kubeflow/blob/main/tests/Dockerfile.mnist

@tiansiyuan Yes, you can use that Dockefile to build your own container and push it to registry that will be accessible for you.
Please let us know, if you were successful with this.

**Comment by DnPlas** [comment]
I believe that @tiansiyuan's original question was resolved. Closing this issue, but please feel free to re-open if needed.
