### ISSUE TITLE
Enhanced Depends Issue with Kubeflow Pipelines (task result 'Omitted' for task ... is invalid) 

### ISSUE THREAD

**Issue by Naegionn** [canonical/bundle-kubeflow#632]
Hello everyone,
as described on charmhub https://discourse.charmhub.io/t/upgrade-argo-to-3-3-9-to-support-enhanced-depends/10795/3 I have an issue using argos enhanced depends with KFP.

I did update the argo-controller and server to 3.3.9 and also tried using argo-controller --channel 3.3/edge. nevertheless it still does not work.
and I still get the error same error: 

```
ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'x-powered-by': 'Express', 'content-type': 'application/json', 'date': 'Thu, 06 Jul 2023 08:12:13 GMT', 'x-envoy-upstream-service-time': '10', 'server': 'envoy', 'transfer-encoding': 'chunked'})
HTTP response body: {"error":"Internal error: templates.example templates.example.tasks.another-func task result 'Omitted' for task 'succeed-func-2' is invalid\nFailed to create a new run.
...
```

I created a notebook with all necessary code to reproduce the error:
* https://gist.github.com/Naegionn/66a1bf93172f70891adf2eb214f8d21d#file-simple-issue-ipynb

In the notebook I use the external KFP endpoint annd hence I am using a function to do the authentication:
* https://gist.github.com/Naegionn/1f76814ce48d5a42aa812bfa043bc0b9#file-dex_login-py

As described in the notebook when applying the generated and updated workflow manifest through `run_result = client.run_pipeline(experiment.id, run_name, "example-updated.yaml") ` it does not work and complain about the use of `.Omitted`.

Whereas if I apply the manifest through kubectl apply it does not complain and execute the argo workflow. But now it is side stpping kfp entirely and kfp does not show/monitor the pipeline.

Thanks in advance for your Help.

**Comment by Naegionn** [comment]
Does anyone have an Idea or does this seems to be more of a problem with KFP tyhan Charmed Kubeflow?

**Comment by NohaIhab** [comment]
Just updating the issue here
Based on the conversation on [Mattermost](https://chat.charmhub.io/charmhub/pl/3djosjaq8pb9t8trwiwnouxuze), an investigation is needed on whether this is an upstream or charmed kubeflow specifc issue.
