### ISSUE TITLE
knative-serving  installation failed  with missing domainmapping-webhook-cert

### ISSUE THREAD

**Issue by jcheungca** [canonical/bundle-kubeflow#642]
I am new  to kubeflow and hope this is a simple issue. Installl with Juju and all components running fine but knative-serving,

from the log, see the  following

{"severity":"ERROR","timestamp":"2023-07-17T20:20:10.346455091Z","logger":"domainmapping-webhook","caller":"webhook/webhook.go:148","message":"failed to fetch secret","commit":"e82287d","knative.dev/pod":"domainmapping-webhook-7d79fb547-jlwg4","error":"secret \"domainmapping-webhook-certs\" not found","stacktrace":"knative.dev/pkg/webhook.New.func2\n\tknative.dev/pkg@v0.0.0-20221011175852-714b7630a836/webhook/webhook.go:148\ncrypto/tls.(*Config).getCertificate\n\tcrypto/tls/common.go:1064\ncrypto/tls.(*serverHandshakeStateTLS13).pickCertificate\n\tcrypto/tls/handshake_server_tls13.go:363\ncrypto/tls.(*serverHandshakeStateTLS13).handshake\n\tcrypto/tls/handshake_server_tls13.go:55\ncrypto/tls.(*Conn).serverHandshake\n\tcrypto/tls/handshake_server.go:54\ncrypto/tls.(*Conn).handshakeContext\n\tcrypto/tls/conn.go:1460\ncrypto/tls.(*Conn).HandshakeContext\n\tcrypto/tls/conn.go:1403\nnet/http.(*conn).serve\n\tnet/http/server.go:1848"}
2023/07/17 20:20:10 http: TLS handshake error from 172.18.188.137:46110: tls: no certificates configured

Please help.

**Comment by i-chvets** [comment]
@jcheungca Could you provide exact steps you followed (or link to the guide) to get to the stage where knative-serving is failing for you?
