### ISSUE TITLE
[CKF 1.8] Define components, dependencies and infrastructure versions

### ISSUE THREAD

**Issue by DnPlas** [canonical/bundle-kubeflow#643]
Hi everyone, here is the list of components and dependencies versions that the Charmed Kubeflow team is targeting for the next bundle release. Please leave a comment if you agree or have suggestions on the proposed versions.

#### Kubernetes version

|            | Previous version(s) | New version(s) |
|------------|---------------------|----------------|
| Kubernetes |       1.24/1.25              |       1.25/1.26         |

#### Juju version

|            | Previous version(s) | New version(s) |
|------------|---------------------|----------------|
| Juju |      2.9/stable              |       3.1/stable         |

#### Kubeflow dependencies

| Component    | Previous version | New version |
|--------------|------------------|-------------|
| Knative      |      1.8            |      1.10       |
| Istio        |        1.16          |       1.17      |
| Dex          |        2.31          |      2.36       |
| Argo         |        3.3.8          |      3.3.10       |
| Oidc         |           e236439       |    e236439      |

#### Kubeflow projects

| Component                      | Previous version | New version |
|--------------------------------|------------------|-------------|
| training-operator              |      1.6            |       1.7      |
| katib-operators                |        0.15          |       0.16      |
| notebook-operators             |      1.7            |      1.8       |
| kubeflow-dashboard-operator    |      1.7            |       1.8      |
| kubeflow-profiles-operator     |      1.7            |      1.8       |
| kubeflow-tensorboard-operators |        1.7          |       1.8      |
| kubeflow-volumes-operator      |       1.7           |     1.8        |
| kubeflow-roles-operator        |          1.7        |      1.8       |
| kfp-operators                  |        2.0.0-alpha.7          |      2.0       |
| admission-webhook-operator     |       1.7           |     1.8        |
| kserve-operators               |         0.10         |       0.11      |

The following versions are either extracted from the upstream project or decided by the Charmed Kubeflow team:

#### Charmed Kubeflow specific

| Component                      | Previous version | New version |
|--------------------------------|------------------|-------------|
| minio                          |                  |      same as 1.7       |
| katib-db (mysql-k8s)                       |       N/A           |      8.0/stable       |
| kfp-db (mysql-k8s)                         |           N/A       |        8.0/stable     |
| metacontroller-operator        |        2.0          |       3.0      |
| seldon-core-operator           |        1.15          |      1.17       |

#### Discussion
* ~~oidc-gatekeeper (oidc-authservice) - this component will likely stay the same as no new versions for KF 1.8 will be released.~~
  * will remain the same
* ~~seldon-core-operator - the latest v1 is 1.17, but in the past release we supported v1.15. Can we make that jump?~~
  * According to upstream, we'll have version 1.17 for the upcoming release.
* ~~metacontroller-operator - the latest is v4, but we have used v2 in the past, should we upgrade?~~
  * Upgrade to 3.0
* minio - we have been using a version from 2021, should we move to a more recent version?
  * Due to its LICENSE, we cannot upgrade any further. No change needed. https://blog.min.io/from-open-source-to-free-and-open-source-minio-is-now-fully-licensed-under-gnu-agplv3/

#### Useful links
* https://github.com/kubeflow/manifests/issues/2450
* [Supported minio version in charmed minio](https://github.com/canonical/minio-operator/blob/track/ckf-1.7/metadata.yaml#L16) vs [minio releases](https://github.com/minio/minio/releases)
* [metacontroller](https://github.com/metacontroller/metacontroller/releases) releases
* [seldon core releases](https://github.com/SeldonIO/seldon-core/releases)

**Comment by DnPlas** [comment]
Just a note, investigating a bit more with people from seldon, it seems like versions above 1.16 are compatible with Kubernetes 1.24 and 1.25. Also, they are planning to add v1.17 in `kubeflow/manifests`, so to keep consistency with upstream, we should go with that version.

**Comment by kimwnasptd** [comment]
cc @marowid @Barteus @nishant-dash on the above versions that we target for CKF 1.8

**Comment by nishant-dash** [comment]
Thanks for laying this out!

IMO, It would be nice to also see what (major and possibly minor) versions of juju are recommended/tested.

**Comment by DnPlas** [comment]
Since the work for 1.8 is completed, we can close this issue.
