### ISSUE TITLE
Notebook selection or a list of running notebooks shows a number instead of an image.

### ISSUE THREAD

**Issue by boggyuk** [canonical/bundle-kubeflow#652]
Notebook selection and notebook list show a number instead of an icon. 
Can we show the image of the relevant application as we have with jupyter notebook, please? 
<img width="906" alt="Kubeflow_Central_Dashboard1" src="https://github.com/canonical/bundle-kubeflow/assets/33030569/930444d8-bde0-47ad-9f9a-aaf1f596f720">
<img width="1051" alt="Kubeflow_Central_Dashboard" src="https://github.com/canonical/bundle-kubeflow/assets/33030569/d17b828f-9299-4cf2-9820-1d45a4b10b1b">

**Comment by orfeas-k** [comment]
This is an issue regarding the upstream. Upstream doesn't provide the icons due to copyright issues (licenses) with the logos. See https://github.com/kubeflow/kubeflow/issues/7069#issuecomment-1494704716.
Closing this as this is not something Charmed Kubeflow team can solve.
