### ISSUE TITLE
CVE reports incorrectly report images that are no longer deployed with CKF

### ISSUE THREAD

**Issue by i-chvets** [canonical/bundle-kubeflow#674]
# Bug Description

Current CVE reporting tools incorrectly report images that are not deployed in the final product. These images should be reviewed and removed from reporting.

# To Reproduce
Run `tools/get-images.sh` scripts in each charm repository (on track branches) to get the list of images related to that charm. In some cases, this list might contain images that are no longer deployed/used. Example: https://github.com/canonical/seldon-core-operator/blob/track/1.15/tools/get-images.sh
Example of image in the report that is not actually deployed is `docker.io/seldonio/engine:1.12.0`. It it set in static list [here](https://github.com/canonical/seldon-core-operator/blob/track/1.15/tools/get-images.sh#L8). This should be removed from that script/list.

# Environment
Charm repositories, `tools/` directory on track branches.

# Relevant Log Output
N/A

# Additional Context
Related issues and PRs in charm repositories:
https://github.com/canonical/seldon-core-operator/issues/197
https://github.com/canonical/seldon-core-operator/pull/186

Related PRs in CI and bundle repositories:
https://github.com/canonical/bundle-kubeflow/pull/666
https://github.com/canonical/kubeflow-ci/pull/105

**Comment by kimwnasptd** [comment]
Thanks @i-chvets! Let's use this issue to add the full list of images that are currently reported, and should not.

So until now we have:
`docker.io/seldonio/engine:1.12.0`
`kserve/models-web-app:v0.8.0`

I'd propose that we should also consider including the images defined in https://github.com/canonical/katib-rocks/issues/17#issuecomment-1688060234. But before we commit to removing those, let's double check where they were used in the first place.

**Comment by i-chvets** [comment]
@i-chvets to take a look at `katib-operators` images to identify not deployed images.

**Comment by i-chvets** [comment]
In `katib-controller` on `track/0.15` there are multiple ConfigMaps are deployed that contain a number of default container images.
On `main` those images are specified in the charm's code as default images due to [recent changes](https://github.com/canonical/katib-operators/pull/98) that were done to support custom image lists. In addition to already identified images for Katib the following 3 seem to be used as default AND can possibly be deployed:
- kubeflowkatib/enas-cnn-cifar10-cpu
- kubeflowkatib/mxnet-mnist
- kubeflowkatib/pytorch-mnist-cpu
I've updated spreadsheet foir latest/edge
@kimwnasptd @andreeamun ^^^

**Comment by i-chvets** [comment]
@kimwnasptd `kserve/models-web-app:v0.8.0` image is in 1.7 branch for kserve (it is not in main). However, I don't think we deploy that application in 1.7. So, it looks like it is false positive and we can remove it from the list.

**Comment by i-chvets** [comment]
Another note. In order to remove incorrectly reported image `docker.io/seldonio/engine:1.12.0` the following issue/PR need to be addressed.

https://github.com/canonical/seldon-core-operator/issues/199
https://github.com/canonical/seldon-core-operator/pull/186

**Comment by kimwnasptd** [comment]
@i-chvets what's the overall state at this point? Could you add a follow-up comment with all the images that we need to remove?

**Comment by i-chvets** [comment]
1. Kserve: After fixing other issues in Kserve repo (approved this morning EST), last PR is in review https://github.com/canonical/kserve-operators/pull/155 and after that it is all done - kserve images will be all good.
2. Seldon: Requires the following issue/PR to be resolved in order to properly skip invalid image:
https://github.com/canonical/seldon-core-operator/issues/199
https://github.com/canonical/seldon-core-operator/pull/186
3. Katib: No PR and it looks like we cannot get rid of all those example images after all on `track/0.15`. They are used as default images in trial templates. It will be different story for `main`, because we

**Comment by i-chvets** [comment]
Katib issues that need to be handled to ensure reliable handling of default images:
https://github.com/canonical/katib-operators/issues/130
https://github.com/canonical/katib-operators/issues/131

**Comment by kimwnasptd** [comment]
While not directly related, I'll add a link here regarding our effort to also remove the default template images for Katib https://github.com/canonical/katib-operators/issues/132

**Comment by kimwnasptd** [comment]
Will close this one once we back-port the changes to CKF 1.7 as well
- https://github.com/canonical/katib-operators/issues/162
- https://github.com/canonical/kserve-operators/pull/185

**Comment by kimwnasptd** [comment]
Closing this issue since we merged both PRs
