### ISSUE TITLE
Image gathering scripts for main branches

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/bundle-kubeflow#679]
Following our effort to test CKF on airgapped environments https://github.com/canonical/bundle-kubeflow/issues/678 we'll need to make sure our image gathering scripts work for `main` branches as well. The goal is to be able to automatically gather all the images of a `latest` bundle.

Right now our scripts expect specific metadata to be present in a bundle 
https://github.com/canonical/kubeflow-ci/blob/c0913a5962611eb3accd4d4ec174cd04fb78b76c/scripts/images/get-all-images.sh#L10

This information, right now, is only present in our 1.7 bundle and specifically in the `stable` risk 
https://github.com/canonical/bundle-kubeflow/blob/47cfb9fe337afba4cd64c1262e2a4192c6d69c60/releases/1.7/stable/kubeflow/bundle.yaml#L10

We'll need to extend the rest of the bundle definitions, in `latest` to make sure we can grab images list from the edge bundles automatically

List of repositories and corresponding PRs:
- [x] https://github.com/canonical/admission-webhook-operator https://github.com/canonical/admission-webhook-operator/pull/106
- [x] https://github.com/canonical/knative-operators https://github.com/canonical/knative-operators/pull/141
- [x] https://github.com/canonical/argo-operators https://github.com/canonical/argo-operators/pull/124
- [x] https://github.com/canonical/dex-auth-operator https://github.com/canonical/dex-auth-operator/pull/163
- [x] https://github.com/canonical/istio-operators https://github.com/canonical/istio-operators/pull/319
- [x] https://github.com/canonical/seldon-core-operator https://github.com/canonical/seldon-core-operator/pull/204
- [x] https://github.com/canonical/notebook-operators https://github.com/canonical/notebook-operators/pull/289
- [x] https://github.com/canonical/katib-operators https://github.com/canonical/katib-operators/pull/134
- [x] https://github.com/canonical/kfp-operators https://github.com/canonical/kfp-operators/pull/312
- [x] https://github.com/canonical/kubeflow-dashboard-operator https://github.com/canonical/kubeflow-dashboard-operator/pull/159
- [x] https://github.com/canonical/kubeflow-roles-operator - NO IMAGES
- [x] https://github.com/canonical/kubeflow-volumes-operator https://github.com/canonical/kubeflow-volumes-operator/pull/108
- [x] https://github.com/canonical/metacontroller-operator https://github.com/canonical/metacontroller-operator/pull/79
- [x] https://github.com/canonical/minio-operator https://github.com/canonical/minio-operator/pull/145
- [x] https://github.com/canonical/oidc-gatekeeper-operator https://github.com/canonical/oidc-gatekeeper-operator/pull/106
- [x] https://github.com/canonical/kubeflow-tensorboards-operator https://github.com/canonical/kubeflow-tensorboards-operator/pull/90
- [x] https://github.com/canonical/training-operator https://github.com/canonical/training-operator/pull/127
- [x] https://github.com/canonical/kserve-operators https://github.com/canonical/kserve-operators/pull/164

Related issues:
Katib issues to resolve for images scripts:
https://github.com/canonical/katib-operators/issues/130
https://github.com/canonical/katib-operators/issues/131
https://github.com/canonical/katib-operators/issues/132

Kserve issue to resolve for images scripts:
https://github.com/canonical/kserve-operators/issues/161
https://github.com/canonical/kserve-operators/issues/162

**Comment by kimwnasptd** [comment]
Also, we'll need to ensure we copy the `get-images.sh` scripts, that leave in each charm repo, to the `main` branches.

Right now those scripts only live in the track branches:
https://github.com/canonical/notebook-operators/blob/track/1.7/tools/get-images.sh

**Comment by i-chvets** [comment]
For updating bundle with repository references and branch names plan is to update `releases/lates/edge/bundle.yaml` and `releases/lates/beta/bundle.yaml`
Branch names in all cases will be either `main` or `master` depending on what upstream is using.

**Comment by i-chvets** [comment]
Most of the scripts are completed and PRs created.
Some PRs are faling in integration tests, this is not related to the changes introduced (image retrieval script does not affect any tests). However, this concerning and new issues for failing integration tests should be created.

The following repositories will require more work to get all images retrieved due to recent changes in how default images are handled in charms:
- https://github.com/canonical/seldon-core-operator
- https://github.com/canonical/notebook-operators
- https://github.com/canonical/katib-operators
- https://github.com/canonical/mlflow-operator

**Comment by i-chvets** [comment]
PRs failing CI:
- https://github.com/canonical/istio-operators/pull/319
- https://github.com/canonical/kfp-operators/pull/312
- https://github.com/canonical/metacontroller-operator/pull/79
- https://github.com/canonical/minio-operator/pull/145

**Comment by i-chvets** [comment]
Katib issues to resolve for images scripts:
https://github.com/canonical/katib-operators/issues/130
https://github.com/canonical/katib-operators/issues/131
https://github.com/canonical/katib-operators/issues/132

Kserve issue to resolve for images scripts:
https://github.com/canonical/kserve-operators/issues/161
https://github.com/canonical/kserve-operators/issues/162

**Comment by NohaIhab** [comment]
This needs to be done for Katib as well. Instead of using a static list in the script as mentioned in https://github.com/canonical/bundle-kubeflow/issues/689 , we can create a similar strategy as kserve https://github.com/canonical/kserve-operators/pull/163

**Comment by kimwnasptd** [comment]
Marking this as done as we merged all scripts in `main` and generated the full list of images
