### ISSUE TITLE
Deploy KServe in `Serverless` mode

### ISSUE THREAD

**Issue by phoevos** [canonical/bundle-kubeflow#685]
Currently, we are deploying KServe in `RawDeployment` mode. However, this is not working as expected at the moment:
* https://github.com/canonical/kserve-operators/issues/148

### Goal

Replace `RawDeployment` with `Serverless` as the default deployment mode for the `kserve-controller` charm.

**Comment by kimwnasptd** [comment]
Closing this, since we've switched to serverless
