### ISSUE TITLE
Prometheus latest/edge requires juju >= 3.0.3

### ISSUE THREAD

**Issue by NohaIhab** [canonical/bundle-kubeflow#688]
Prometheus recently got a patch causing it to assume juju >= 3.0.3.
That results in our integration tests breaking in multiple repos, some of those being `notebook-operators` and `metacontroller`.
See [this comment](https://github.com/canonical/notebook-operators/pull/291#issuecomment-1700849980) where we bumped into the issue.

**Comment by NohaIhab** [comment]
This can be handled temporarily by pinning Prometheus to a revision, and unpinning it once we migrate to Juju 3.1.

**Comment by phoevos** [comment]
Currently, only charms deploying Prometheus from `latest/edge` are affected. However, the Observability team will soon bump the rest of the `latest` tracks, which will affect even more of our repos. We have decided to pin the Prometheus revision when deploying from `latest` to avoid fetching recent patches of the charm which assume `juju >= 3.0.3`. This is a temporary patch until we migrate to Juju 3.1.

Revision 137 was the last one seen working properly in our [CI integration tests](https://github.com/canonical/notebook-operators/actions/runs/5904696558/job/16017327250#step:4:212), so it will be used for all of our charms that rely on some `latest` track of the Prometheus charm.

A list of the affected charms is provided below:
| **Charms** | **Prometheus Version** |
|:---:|:---:|
| **[metacontroller](https://github.com/canonical/metacontroller-operator/blob/15330f29fb86774349c945f231dcbebfdc21b046/tests/integration/test_charm.py#L60)<br>[minio](https://github.com/canonical/minio-operator/blob/54a1cd0a30f16c2cee59bb56639d0c9faa9dc4cf/tests/integration/test_charm.py#L213)<br>[notebooks](https://github.com/canonical/notebook-operators/blob/1649903d6cbebd902398375008e6c19c2dcd1745/tests/test_charms.py#L282)<br>[training-operators](https://github.com/canonical/training-operator/blob/577ea255f8f7064d91566daad217396f5c5f9db4/tests/integration/test_charm.py#L139)** | `latest/edge` |
| **[argo](https://github.com/canonical/argo-operators/blob/3c600d0c7186a6653a94dfdda3e816276dedac3a/charms/argo-controller/tests/integration/test_charm.py#L140)<br>[istio](https://github.com/canonical/istio-operators/blob/9f310bf236aed640f84d1562141cfa12503b1046/tests/test_cos_integration.py#L56)<br>[kfp](https://github.com/canonical/kfp-operators/blob/38fd0f0d8ae5a6195930add44543700986bfc891/charms/kfp-api/tests/integration/test_charm.py#L188)<br>[knative](https://github.com/canonical/knative-operators/blob/b0965b8c13f9e3b22d54cb5a345e0ef63154243a/tests/test_cos_integration.py#L79)<br>[mlflow](https://github.com/canonical/mlflow-operator/blob/328b5f76d1e2b6964c296811d0439f0714717058/tests/integration/test_charm.py#L379)** | `latest/stable` |
| **[dex](https://github.com/canonical/dex-auth-operator/blob/7a3e606368995ece8b2260802d15632067060abf/tests/integration/test_charm.py#L189)** | `latest/beta` |

**Comment by i-chvets** [comment]
Just a quick comment. We have exactly same issue before 1.7 release. Prometheus/Grafana updates breaks us from time to time. Possible approach is to in our tests pin everything to revisions when we cut a track branch. This is a proper way to "freeze" branch in time to avoid extra work in the future.

**Comment by DnPlas** [comment]
The most recent version of the CI for all Charmed Kubeflow owned repositories use juju 3.x for both client and controller. This should not be an issue anymore.
