### ISSUE TITLE
Grafana `latest/edge` fails to install

### ISSUE THREAD

**Issue by phoevos** [canonical/bundle-kubeflow#690]
### Bug Description

Grafana from `latest/edge` fails to install on Juju 2.9.44, with an error stating that the Grafana unit is not assigned to a machine. This is the case following [revision 90](https://github.com/canonical/grafana-k8s-operator/releases/tag/rev90) of the charm, which among other things introduces the use of `open_port` instead of the K8s service patch. Pinning to a previous revision fixes the problem.

Although this does not directly affect our charms, it does break our CI across repos that deploy Grafana as part of their integration tests (e.g. [here](https://github.com/canonical/notebook-operators/actions/runs/6014993343/job/16315940903))

### To Reproduce

To reproduce, you can try deploying Grafana from latest/edge (revision >= 90) on Juju 2.9.44.

### Environment

Juju Agent: 2.9.44
MicroK8s: 1.24/stable
Grafana: latest/edge (rev: 90)

### Relevant log output
```shell
unit-grafana-k8s-0: 14:40:41 ERROR juju.worker.uniter.context cannot apply changes: cannot retrieve ports for unit "grafana-k8s/0": unit "grafana-k8s/0" is not assigned to a machine
unit-grafana-k8s-0: 14:40:41 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: cannot apply changes: cannot retrieve ports for unit "grafana-k8s/0": unit "grafana-k8s/0" is not assigned to a machine
```

### Additional context

Grafana is tested on (and most probably developed for) [Juju 3.1](https://github.com/canonical/grafana-k8s-operator/blob/84db84027979d9daeb9c28a9df7d5fc7dc7582a4/tox.ini#L94). Given that we will be switching to Juju 3.1 very soon and that this issue blocks a number of time-critical PRs, we could pin Grafana to revision 89 for now and revert as soon as the migration has been completed.

**Comment by i-chvets** [comment]
Just a quick comment. We have exactly same issue before 1.7 release. Prometheus/Grafana updates break us from time to time. Possible approach is to pin everything that we depend on to revisions when we cut a track branch. This is a proper way to "freeze" branch in time to avoid extra work in the future. There is no point having edge in track branches.

**Comment by orfeas-k** [comment]
Closing this since we use Juju 3.1 now.
