### ISSUE TITLE
In image scan workflow naming of report files is missing release and risk

### ISSUE THREAD

**Issue by i-chvets** [canonical/bundle-kubeflow#695]
### Bug Description

After the update to the workflow done in https://github.com/canonical/bundle-kubeflow/pull/686 variables that are used to generate filenames have been changed. This causesd unset variables to be used when generating report file names.

For example this ` path: trivy-reports-2023-09-11-01-49-07---1.tar.gz` from [here](https://github.com/canonical/bundle-kubeflow/actions/runs/6140822553/job/16660290545#step:9:4) should have been ` path: trivy-reports-2023-09-11-01-49-07-1.7-stable-1.tar.gz`

The following lines need to be addressed and proper file name should be generated:
https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/scan-images.yaml#L59
https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/scan-images.yaml#L62
https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/scan-images.yaml#L67
https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/scan-images.yaml#L72

### To Reproduce

Refer to image scan workflow execution, eg. https://github.com/canonical/bundle-kubeflow/actions/runs/6140822553

### Environment

Image scan workflow in Github Runner.

### Relevant Log Output

```shell
Run tar zcvf trivy-reports-2023-09-11-01-49-07---1.tar.gz ./trivy-reports
  tar zcvf trivy-reports-2023-09-11-01-49-07---1.tar.gz ./trivy-reports
```

### Additional Context

N/A

**Comment by kimwnasptd** [comment]
Closing since we merged https://github.com/canonical/bundle-kubeflow/pull/697
