### ISSUE TITLE
CFK 1.8 Upgrade Notes

### ISSUE THREAD

**Issue by i-chvets** [canonical/bundle-kubeflow#701]
# Description

Charmed Kubeflow release 1.8 upgrade notes are summarizing details of upgrading charms and the whole deployment.

Please add all relevant notes below along with the links to issues, docs, and Jira tickets.

# Notes

## MariaDB to MySQL migration guide
Migration guide (WIP) https://github.com/canonical/bundle-kubeflow/blob/doc-db-migration-guide/docs/db-migration-guide.ipynb

## Seldon 1.15 incompatibility with k8s 1.25
see issue https://github.com/canonical/seldon-core-operator/issues/211

**Comment by DnPlas** [comment]
When the Charmed Kubeflow release happened, we published a number of guides and release notes:
* [Release notes](https://charmed-kubeflow.io/docs/release-notes-1-8)
* [Mariadb to MySQL migration](https://charmed-kubeflow.io/docs/databases-migration-guide)
* [Upgrade 1.7 to 1.8](https://charmed-kubeflow.io/docs/upgrade-17-18)

These guides should cover what's described in this issue.
