### ISSUE TITLE
Make 1.7/stable work in an airgap environment

### ISSUE THREAD

**Issue by DnPlas** [canonical/bundle-kubeflow#705]
### Bug Description

The goal of this task is to make the CKF 1.7/stable work in airgap environments, which means that the CKF deployment should work on an environment without internet access.

This issue will help tracking all the required changes on individual charms, as well as ensuring when integrated as a bundle, everything can be deployed and tested.

## What needs to be done?

- [x] Make sure images are configurable for all charms in the track/\<versio>
- [x] Make sure all charms are promoted to \<version\>/edge and \<version\>/stable
- [x] Test the bundle in an airgap environment (steps here https://github.com/canonical/bundle-kubeflow/pull/682)
- [x] Replicate [this structure](https://github.com/canonical/bundle-kubeflow/tree/main/releases/latest/edge/airgap) in the `releases/1.7/edge` directory

## State of charms

|                                          | Status                                                                | State of the CI |
|------------------------------------------|-----------------------------------------------------------------------|-----------------|
| canonical/admission-webhook-operator     | https://github.com/canonical/admission-webhook-operator/issues/113   |  [Green](https://github.com/canonical/admission-webhook-operator/actions/runs/5786664673/job/15681891934)               |
| canonical/argo-operators                 | canonical/argo-operators#136                |      [Green](https://github.com/canonical/argo-operators/actions/runs/6327753856/job/17184340654)           |
| canonical/dex-auth-operator              | https://github.com/canonical/dex-auth-operator/issues/167             |   [Green](https://github.com/canonical/dex-auth-operator/actions/runs/6322309177/job/17167688795)              |
| canonical/istio-operators                | https://github.com/canonical/istio-operators/issues/332               |    [Green](https://github.com/canonical/istio-operators/actions/runs/6328608991/job/17187159529)             |
| canonical/katib-operators                | https://github.com/canonical/katib-operators/issues/144               |     [Green](https://github.com/canonical/katib-operators/actions/runs/6326312697/job/17179611834)            |
| canonical/kfp-operators                  | https://github.com/canonical/kfp-operators/issues/335                 |      [Green](https://github.com/canonical/kfp-operators/actions/runs/6324974614/job/17177370565)           |
| canonical/knative-operators              | https://github.com/canonical/knative-operators/issues/159             |       [Green](https://github.com/canonical/knative-operators/actions/runs/6327454265/job/17183310783)          |
| canonical/kserve-operators               | https://github.com/canonical/kserve-operators/issues/179              |      [Green](https://github.com/canonical/kserve-operators/actions/runs/6325303568/job/17176533700)           |
| canonical/kubeflow-dashboard-operator    | https://github.com/canonical/kubeflow-dashboard-operator/issues/165   |  [Green](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/6337376346)              |
| canonical/kubeflow-profiles-operator     | https://github.com/canonical/kubeflow-profiles-operator/issues/152    |     [Green](https://github.com/canonical/kubeflow-profiles-operator/actions/runs/5700473292/job/15450332996)            |
| canonical/kubeflow-roles-operator        | https://github.com/canonical/kubeflow-roles-operator/issues/72        |       [Green](https://github.com/canonical/kubeflow-roles-operator/actions/runs/5786676778/job/15681933941)          |
| canonical/kubeflow-tensorboards-operator | https://github.com/canonical/kubeflow-tensorboards-operator/issues/94 | [Failing to publish](https://github.com/canonical/kubeflow-tensorboards-operator/actions/runs/5554212130/job/15047084554)                 |
| canonical/kubeflow-volumes-operator      | https://github.com/canonical/kubeflow-volumes-operator/issues/116     |      [Green](https://github.com/canonical/kubeflow-volumes-operator/actions/runs/5786662363/job/15681883141)           |
| canonical/metacontroller-operator        | https://github.com/canonical/metacontroller-operator/issues/90        |  [Green](https://github.com/canonical/metacontroller-operator/actions/runs/6322904364/job/17169393905)               |
| canonical/minio-operator                 | https://github.com/canonical/minio-operator/issues/149                |     [Green](https://github.com/canonical/minio-operator/actions/runs/5786656887/job/15681864564)            |
| canonical/notebook-operators             | https://github.com/canonical/notebook-operators/issues/307            |      [Green](https://github.com/canonical/notebook-operators/actions/runs/6325120746/job/17177351941)           |
| canonical/oidc-gatekeeper-operator       | https://github.com/canonical/oidc-gatekeeper-operator/issues/113      |      [Green](https://github.com/canonical/oidc-gatekeeper-operator/actions/runs/6146419843/job/16675755106)           |
| canonical/seldon-core-operator           | https://github.com/canonical/seldon-core-operator/issues/212          |       [Green](https://github.com/canonical/seldon-core-operator/actions/runs/6322017778/job/17166912549)          |
| canonical/training-operator              | https://github.com/canonical/training-operator/issues/141             |       [Green](https://github.com/canonical/training-operator/actions/runs/6144420635/job/17093854950)          |

## Potential issues

https://github.com/canonical/bundle-kubeflow/issues/688
https://github.com/canonical/bundle-kubeflow/issues/690

**Comment by orfeas-k** [comment]
Looks like knative-operator telemetry image is not configurable at the moment neither in `main` nor `track/1.8` https://github.com/canonical/knative-operators/issues/161.

**Comment by DnPlas** [comment]
> Looks like knative-operator telemetry image is not configurable at the moment neither in `main` nor `track/1.8` [canonical/knative-operators#161](https://github.com/canonical/knative-operators/issues/161).

These two patches should fix that:
* https://github.com/canonical/knative-operators/pull/162
* https://github.com/canonical/knative-operators/pull/163

**Comment by orfeas-k** [comment]
Adding the note here as well that during #709, the following image `172.17.0.2:5000/knative-releases/knative.dev/serving/cmd/default-domain:2b3e4074f951dd6b6fa5018047e97a5cb10b6a6ecbb554ed77c9a8dc01011f3b` was the only image (between the ones produced by the scripts) that wasn't used in the charms' configuration. We could not find a container that needs that and this is not configured in [latest/edge bundle-airgap.yaml](https://github.com/canonical/bundle-kubeflow/blob/main/releases/latest/edge/airgap/bundle-airgap.yaml#L129-L138) neither. This can be OK since we could fetch an image we don't need [in our script](https://github.com/canonical/knative-operators/blob/track/1.8/tools/get-images.sh#L18-L32). We should though keep it in the back of our minds in case we see something's off with `knative-serving`'s deployments. 
Note that I also do not see it anywhere in the [serving's manifests](https://github.com/knative/operator/tree/knative-v1.10.3/cmd/operator/kodata/knative-serving/1.8.0).

**Comment by NohaIhab** [comment]
sent a fix for kubeflow dashboard CI in https://github.com/canonical/kubeflow-dashboard-operator/pull/169

**Comment by DnPlas** [comment]
## Current status

#### Charms
All charms have been updated and are now published to their <version>/edge tracks in Charmhub. In the case of `kubeflow-tensorboards-operator` the version in `track/1.7` should be compatible with arigap environments.

#### Bundle and scripts

https://github.com/canonical/bundle-kubeflow/pull/709 is introducing the bundle definition for `1.7/edge` airgap, but pending things to check on that PR are:
1. The `knative-operator` should include the otel-collector image
2. We have to confirm that the charm names are accurate to what is downloaded by juju in both `bundle-airgap.yaml` and `podspec_script.sh`

#### Testing
Not started

## MLFLow integration
Not started, but we need to do a similar effort in the MLFlow bundle: https://github.com/canonical/mlflow-operator/blob/main/releases/2.1/edge/mlflow/bundle.yaml.

**Comment by DnPlas** [comment]
Based on a discussion with @kimwnasptd , we decided to add a "MLOps" bundle definition in this repository to help integrate with MLFlow and other charms required for a deployment with CKF and MLFlow. Please make sure you take a look at #712.

**Comment by DnPlas** [comment]
> Based on a discussion with @kimwnasptd , we decided to add a "MLOps" bundle definition in this repository to help integrate with MLFlow and other charms required for a deployment with CKF and MLFlow. Please make sure you take a look at #712.

This effort is not going to be considered for this effort.

**Comment by orfeas-k** [comment]
Deployed the bundle using files from PR https://github.com/canonical/bundle-kubeflow/pull/709 and everything went to green without issues. We cannot run the UATs at the moment since they need connection to download some extra images that may not be present in the cluster at the moment and also to `pip install` stuff (similar reason we could not run them in self-hosted runners). Once @NohaIhab checks that UATs run successfully in a non-airgapped `1.7/edge` cluster, then we could check "Test the bundle in an airgap environment" and consider this issue task.

**Comment by orfeas-k** [comment]
I forgot to mention that during testing:
- we noticed this issue https://github.com/canonical/istio-operators/issues/336 which is unrelated to airgap
- we observed the same issue with `activator` deployment in `knative-serving` namespace that we had also seen in airgap `latest/edge` https://github.com/canonical/bundle-kubeflow/issues/680#issuecomment-1705065278

**Comment by orfeas-k** [comment]
I think we could close this @DnPlas

**Comment by DnPlas** [comment]
Closing as all the required work has been completed. Thanks everyone!
