### ISSUE TITLE
CKF 1.8 tracking issue

### ISSUE THREAD

**Issue by DnPlas** [canonical/bundle-kubeflow#720]
### Bug Description

This issue is for tracking the status of the CKF beta and stable releases, as well as their known issues and blockers.

### Known issues

* https://github.com/canonical/notebook-operators/issues/309 this issue should be fixed by https://github.com/kubeflow/kubeflow/pull/7310
* https://github.com/canonical/istio-operators/issues/336
* https://github.com/canonical/admission-webhook-operator/issues/110 this issue should be fixed by https://github.com/canonical/admission-webhook-operator/pull/116
* https://github.com/canonical/kfp-operators/issues/343 - this issue is blocking the kfp-operators upgrade for 1.8, because of this issue for 1.8/beta we will be using kfp-operators from the latest/edge track.
* https://github.com/canonical/kserve-operators/issues/182 - this is partially an issue because inference can be done manually from a Pod, we'll need to investigate more
* https://github.com/canonical/seldon-core-operator/issues/218 - issue that affects seldon upgrades from 1.15 -> 1.17
* https://github.com/canonical/seldon-core-operator/issues/211 - because seldon-core in 1.8/beta is not going to be updated (see https://github.com/canonical/seldon-core-operator/issues/218) seldon cannot be used in deployments on k8s>1.24. Since CKF 1.8 is targeting 1.25 and 1.26, this should be communicated until we have a stable version.
* https://github.com/canonical/resource-dispatcher/issues/30 - this issue should be fixed by https://github.com/canonical/kfp-operators/pull/342
* https://github.com/canonical/pvcviewer-operator/issues/11 - this issue should be fixed by https://github.com/canonical/pvcviewer-operator/pull/12
* https://github.com/canonical/katib-operators/issues/108
* https://github.com/canonical/kserve-operators/issues/188

#### UATs
e2e-wine - FAILED (requires seldon to be updated)
katib - PASSED
kfp - FAILED due to issue https://github.com/canonical/argo-operators/issues/143
kserve - PASSED
minio - PASSED
mlflow  - PASSED
training - PASSED

#### UI
* Notebooks - Can’t connect to notebook server, issue: https://github.com/canonical/notebook-operators/issues/309
* Tensorboards - PASSED

##### TODO UI testing:
* Pipelines
* PVCViewer
* Katib

### WIP should be merged before releasing

* https://github.com/canonical/argo-operators/pull/141 - for 1.8/stable
* https://github.com/canonical/argo-operators/pull/141 - for 1.8/beta
* https://github.com/canonical/istio-operators/pull/338 - for 1.8/stable
* https://github.com/canonical/kfp-operators/pull/331 - for 1.8/stable
* https://github.com/canonical/seldon-core-operator/pull/216 - for 1.8/stable
* https://github.com/canonical/pvcviewer-operator/pull/10 - for 1.8/beta
* https://github.com/canonical/admission-webhook-operator/pull/116 - for 1.8/beta
* https://github.com/canonical/pvcviewer-operator/pull/13 - for 1.8/stable

### Charmhub status

* WIP means the charm hasn't been released to the corresponding channel
* Released means the charm has been released to the corresponding channel

|                                          | latest/beta | latest/edge | 1.8/stable | 1.8/edge |
|------------------------------------------|-------------|-------------|------------|----------|
| canonical/admission-webhook-operator     | Released         | Released         | WIP        | WIP      |
| canonical/argo-operators                 | WIP         | WIP         | WIP        | WIP      |
| canonical/dex-auth-operator              | Released         | Released         | WIP        | WIP      |
| canonical/istio-operators                | Released         | Released         | WIP        | WIP      |
| canonical/katib-operators                | Released         | Released         | WIP        | WIP      |
| canonical/kfp-operators                  | WIP         | WIP         | WIP        | WIP      |
| canonical/knative-operators              | Released         | Released         | WIP        | WIP      |
| canonical/kserve-operators               | Released         | Released         | WIP        | WIP      |
| canonical/kubeflow-dashboard-operator    | Released         | Released         | WIP        | WIP      |
| canonical/kubeflow-profiles-operator     | WIP         | WIP         | WIP        | WIP      |
| canonical/kubeflow-roles-operator        | Released         | Released         | WIP        | WIP      |
| canonical/kubeflow-tensorboards-operator | Rleased         | Released         | WIP        | WIP      |
| canonical/kubeflow-volumes-operator      | Released         | Released        | WIP        | WIP      |
| canonical/metacontroller-operator        | Released         | Released         | WIP        | WIP      |
| canonical/minio-operator                 | Released         | Released         | WIP        | WIP      |
| canonical/notebook-operators             | Released         | Released         | WIP        | WIP      |
| canonical/oidc-gatekeeper-operator       | Released         | Released         | WIP        | WIP      |
| canonical/seldon-core-operator           | WIP         | WIP         | WIP        | WIP      |
| canonical/training-operator              | Released         | Released         | WIP        | WIP      |
| canonical/pvcviewer-operator              | Released         | Released         | WIP        | WIP      |

**Comment by DnPlas** [comment]
Because of some issues in kfp, seldon, and kubeflow-profiles, we had to stick with previous versions of those components for the beta release. Before moving on and releasing 1.8/stable, we must ensure that the changes introduced by https://github.com/canonical/bundle-kubeflow/pull/721 are reverted back to the correct channel.

**Comment by DnPlas** [comment]
I believe all of the work for 1.8 has been completed. No need for this issue anymore.

**Comment by Vamshi1271** [comment]
Hello,
I'm encountering an issue while installing CKF 1.9/stable using Juju. The istio-pilot unit enters an error state with the following message:

hook failed: "ingress-relation-changed"

Could someone please help diagnose and resolve this problem? Any guidance or debugging tips would be greatly appreciated.
`Model     Controller  Cloud/Region  Version  SLA          Timestamp
kubeflow  uk8sx1      k8s           3.4.6    unsupported  07:43:49+05:30

App                      Version                  Status   Scale  Charm                    Channel          Rev  Address         Exposed  Message
admission-webhook                                 active       1  admission-webhook        1.9/stable       344  10.106.182.164  no       
argo-controller                                   active       1  argo-controller          3.4/stable       617  10.102.157.53   no       
dex-auth                                          active       1  dex-auth                 2.39/stable      588  10.107.198.141  no       
envoy                                             active       1  envoy                    2.2/stable       310  10.107.211.111  no       
istio-ingressgateway                              active       1  istio-gateway            1.22/stable     1280  10.96.165.223   no       
istio-pilot                                       waiting      1  istio-pilot              1.22/stable     1169  10.110.229.19   no       installing agent
jupyter-controller                                active       1  jupyter-controller       1.9/stable      1083  10.104.225.129  no       
jupyter-ui                                        active       1  jupyter-ui               1.9/stable       961  10.99.97.132    no       
katib-controller                                  active       1  katib-controller         0.17/stable      813  10.101.28.69    no       
katib-db                 8.0.39-0ubuntu0.22.04.1  active       1  mysql-k8s                8.0/stable       210  10.96.92.11     no       
katib-db-manager                                  active       1  katib-db-manager         0.17/stable      713  10.106.115.22   no       
katib-ui                                          active       1  katib-ui                 0.17/stable      713  10.104.161.104  no       
kfp-api                                           active       1  kfp-api                  2.3/stable      1743  10.99.163.128   no       
kfp-db                   8.0.39-0ubuntu0.22.04.1  active       1  mysql-k8s                8.0/stable       210  10.108.170.194  no       
kfp-metadata-writer                               active       1  kfp-metadata-writer      2.3/stable       960  10.106.248.124  no       
kfp-persistence                                   active       1  kfp-persistence          2.3/stable      1756  10.100.250.220  no       
kfp-profile-controller                            active       1  kfp-profile-controller   2.3/stable      1715  10.105.67.185   no       
kfp-schedwf                                       active       1  kfp-schedwf              2.3/stable      1765  10.103.169.62   no       
kfp-ui                                            active       1  kfp-ui                   2.3/stable      1752  10.106.197.62   no       
kfp-viewer                                        active       1  kfp-viewer               2.3/stable      1781  10.103.2.193    no       
kfp-viz                                           active       1  kfp-viz                  2.3/stable      1700  10.103.22.102   no       
knative-eventing                                  active       1  knative-eventing         1.12/stable      645  10.106.225.196  no       
knative-operator                                  active       1  knative-operator         1.12/stable      610  10.100.136.58   no       
knative-serving                                   active       1  knative-serving          1.12/stable      646  10.96.99.183    no       
kserve-controller                                 active       1  kserve-controller        0.13/stable      655  10.106.98.173   no       
kubeflow-dashboard                                active       1  kubeflow-dashboard       1.9/stable       659  10.106.222.214  no       
kubeflow-profiles                                 active       1  kubeflow-profiles        1.9/stable       522  10.107.55.143   no       
kubeflow-roles                                    active       1  kubeflow-roles           1.9/stable       240  10.110.43.232   no       
kubeflow-volumes                                  active       1  kubeflow-volumes         1.9/stable       348  10.108.87.62    no       
metacontroller-operator                           active       1  metacontroller-operator  3.0/stable       352  10.97.159.255   no       
minio                    res:oci-image@220b31a    active       1  minio                    ckf-1.9/stable   383  10.107.11.42    no       
mlmd                                              active       1  mlmd                     ckf-1.9/stable   213  10.107.130.97   no       
oidc-gatekeeper                                   active       1  oidc-gatekeeper          ckf-1.9/stable   423  10.109.156.3    no       
pvcviewer-operator                                active       1  pvcviewer-operator       1.9/stable       204  10.106.157.184  no       
tensorboard-controller                            active       1  tensorboard-controller   1.9/stable       355  10.106.65.169   no       
tensorboards-web-app                              active       1  tensorboards-web-app     1.9/stable       343  10.103.43.246   no       
training-operator                                 active       1  training-operator        1.8/stable       545  10.111.84.70    no       

Unit                        Workload  Agent  Address        Ports          Message
admission-webhook/0*        active    idle   172.28.5.52                   
argo-controller/0*          active    idle   172.23.88.157                 
dex-auth/0*                 active    idle   172.28.5.54                   
envoy/0*                    active    idle   172.23.88.154                 
istio-ingressgateway/0*     active    idle   172.28.5.53                   
istio-pilot/0*              error     idle   172.23.88.152                 hook failed: "ingress-relation-changed"
jupyter-controller/0*       active    idle   172.23.88.151                 
jupyter-ui/0*               active    idle   172.28.5.55                   
katib-controller/0*         active    idle   172.21.214.49                 
katib-db-manager/0*         active    idle   172.28.5.56                   
katib-db/0*                 active    idle   172.21.214.50                 Primary
katib-ui/0*                 active    idle   172.23.88.150                 
kfp-api/0*                  active    idle   172.21.214.51                 
kfp-db/0*                   active    idle   172.23.88.140                 Primary
kfp-metadata-writer/0*      active    idle   172.23.88.139                 
kfp-persistence/0*          active    idle   172.23.88.148                 
kfp-profile-controller/0*   active    idle   172.21.214.52                 
kfp-schedwf/0*              active    idle   172.21.214.54                 
kfp-ui/0*                   active    idle   172.28.5.58                   
kfp-viewer/0*               active    idle   172.28.5.59                   
kfp-viz/0*                  active    idle   172.21.214.55                 
knative-eventing/0*         active    idle   172.21.214.53                 
knative-operator/0*         active    idle   172.23.88.144                 
knative-serving/0*          active    idle   172.28.5.57                   
kserve-controller/0*        active    idle   172.21.214.60                 
kubeflow-dashboard/0*       active    idle   172.28.5.60                   
kubeflow-profiles/0*        active    idle   172.28.5.63                   
kubeflow-roles/0*           active    idle   172.23.88.141                 
kubeflow-volumes/0*         active    idle   172.23.88.142                 
metacontroller-operator/0*  active    idle   172.21.214.56                 
minio/0*                    active    idle   172.21.214.58  9000-9001/TCP  
mlmd/0*                     active    idle   172.28.5.32                   
oidc-gatekeeper/0*          active    idle   172.21.214.59                 
pvcviewer-operator/0*       active    idle   172.23.88.153                 
tensorboard-controller/0*   active    idle   172.21.214.61                 
tensorboards-web-app/0*     active    idle   172.28.5.27                   
training-operator/0*        active    idle   172.28.5.61        `
