### ISSUE TITLE
Update the docs for CKF 1.8

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/bundle-kubeflow#744]
### What needs to get done

For the upcoming 1.8 release we'll need to ensure we update at least our docs in 
https://charmed-kubeflow.io/docs/tutorial
https://charmed-kubeflow.io/docs/supported-versions

DoD:
* Updated for CKF 1.8, MicroK8s and juju versions
* Have updated images

### Why it needs to get done

To make sure users can use the latest release out of the box

**Comment by kimwnasptd** [comment]
A note here is that out of the box the juju snap is going to complain if try to bootstrap juju 3.1 in a non-strict microk8s.

But we can't go with strict MicroK8s right now because it doesn't work with the NVIDIA Operator. A way we could boostrap the Juju controller is by adding the MicroK8s cluster to juju as a regular K8s cluster

```bash
snap install juju
snap install microk8s --channel 1.26 --classic

microk8s enable dns hostpath-storage
microk8s config | juju add-k8s my-k8s --client

juju bootstrap my-k8s controller-1
```

**Comment by NohaIhab** [comment]
docs were updated
