### ISSUE TITLE
Cut track branches on all repos for CKF 1.8

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/bundle-kubeflow#745]
### What needs to get done

We'll need to make sure we have created the corresponding tracks for all components used currently in our bundle
https://github.com/canonical/bundle-kubeflow/blob/main/releases/latest/edge/bundle.yaml

This will need to happen after we've first merged
- [x] https://github.com/canonical/kserve-operators/pull/191
- [x] https://github.com/canonical/katib-operators/pull/151
- [x] https://github.com/canonical/kubeflow-tensorboards-operator/pull/98
- [x] https://github.com/canonical/kubeflow-volumes-operator/pull/119
- [x] https://github.com/canonical/istio-operators/pull/348
- [x] https://github.com/canonical/minio-operator/pull/154
- [x] Merge KFP PRs
  - https://github.com/canonical/kfp-operators/pull/362
  - https://github.com/canonical/kfp-operators/pull/385
  - https://github.com/canonical/kfp-operators/pull/386
  - https://github.com/canonical/kfp-operators/pull/387
- [x] https://github.com/canonical/envoy-operator/issues/66

### Why it needs to get done

In order for us to update the bundle for the 1.8 release, and have automations just for 1.8

**Comment by orfeas-k** [comment]
Closing since all branches were cut
