### ISSUE TITLE
Update the scanning scripts to also run on 1.8/stable

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/bundle-kubeflow#753]
### What needs to get done

We'll need to include the scripts for scanning images to also include `1.8/stable`
https://github.com/canonical/bundle-kubeflow/blob/f6ec5237bb57a457be5397c06f35e659460924a7/.github/workflows/scan-images.yaml#L14

### Why it needs to get done

To make sure we have reports for this supported version

**Comment by NohaIhab** [comment]
closed by #754
