### ISSUE TITLE
Extend EKS tests to also run UATs

### ISSUE THREAD

**Issue by orfeas-k** [canonical/bundle-kubeflow#802]
### Context

At the moment, [deploy-eks.yaml](https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/deploy-eks.yaml) only deploys and checks that the deployment is active. It doesn't run any other tests.

### What needs to get done

We will probably need to update the tox environment ran to also run the UATs after run the deploy_and_check_is_active test.

### Definition of Done

EKS workflow runs UATs after deploying the bundle

**Comment by misohu** [comment]
I started working on this. There is a problem with juju 3+ to setup cloud on EKS cluster (tested with 3.1, 3.5).This setup is working with juju 2.9 but not with 3. I have [reached to juju team](https://matrix.to/#/!xzmWHtGpPfVCXKivIh:ubuntu.com/$yd2J12o7zeXm0I3TlRqxUPxmlZF_EfkHiMFK1hFIKzI?via=ubuntu.com&via=matrix.org&via=mx.aouss.it) asking for resolution.

**Comment by misohu** [comment]
I have managed to resolve this by installing juju 3.5 from binary in the PR above.
