### ISSUE TITLE
select kubeflow pods by node selectors

### ISSUE THREAD

**Issue by nishant-dash** [canonical/bundle-kubeflow#805]
### Bug Description

I would like to make sure my charmed kubeflow pods only land on certain nodes (selected by some label on the k8s nodes).  How can I achieve this given that the charms can re-render the pod manifests on a variety of hooks?

### To Reproduce

N/A

### Environment

N/A

### Relevant Log Output

```shell
N/A
```

### Additional Context

N/A

**Comment by nishant-dash** [comment]
btw @ca-scribner pointed me to https://github.com/canonical/namespace-node-affinity-operator

**Comment by orfeas-k** [comment]
Closing since [namespace-node-affinity](https://github.com/canonical/namespace-node-affinity-operator) charm is responsible for this functionality. In the future, this should move to `juju` as mentioned in https://github.com/canonical/namespace-node-affinity-operator/issues/31.
