### ISSUE TITLE
Update and run AKS tests for the 1.9 release

### ISSUE THREAD

**Issue by ca-scribner** [canonical/bundle-kubeflow#809]
### Context

We should update our AKS test suite and execute the tests for the charmed kubeflow 1.9 release

### What needs to get done

1. update AKS test suite for the 1.9 release
2. execute the tests

### Definition of Done

1. tests are executed and passing

**Comment by NohaIhab** [comment]
PR #986 updates the tests for beta release

Pending as part of this task:

1. We should re-run the test on aks for 1.9/beta after https://github.com/canonical/charmed-kubeflow-uats/issues/73 is closed
2. Once we cut the branches, we should send another PR to point the 1.9 tests to 1.9/edge and re-run the tests.
3. When 1.9/stable is released, we should send a PR to point the tests to 1.9/stable bundle.
