### ISSUE TITLE
Explore/document shortcomings, pain points and similarities of observability integration testing 

### ISSUE THREAD

**Issue by orfeas-k** [canonical/bundle-kubeflow#823]
### Context

Explore current observability tests in order to evaluate what is needed in order to have better tests. After this task,  we should be able to answer what good observability bundle testing means and evaluate the work needed to achieve this.

This includes, but is not limited to, evaluating the below points, plus the work needed for:
* What abstractions we need to add in Chisme? (including the K8s Service, for the `/metrics` endpoint configuration)
* How do tests ensure alert rules are working as expected?
* How tests check the dasbhoards?

### What needs to get done

Explore the above questions and document findings

### Definition of Done

Above exploration has been done

**Comment by orfeas-k** [comment]
While working on this, I also created this spin off issue about #838 that raises questions and concerns in a higher level about what exactly we would like to test and how should we achieve this.

**Comment by orfeas-k** [comment]
Added this comment too https://github.com/canonical/bundle-kubeflow/issues/838#issuecomment-1961189070 about alerts testing tools, which could affect what we end up adding in chisme.

**Comment by orfeas-k** [comment]
# Common charm code (apart from testing)

What each charm that is integrated to COS needs to do is:

* Defining a `MetricsEndpoint` provider e.g.
	```
	        self.prometheus_provider = MetricsEndpointProvider(
            charm=self,
            relation_name="metrics-endpoint",
            jobs=[
                {
                    "metrics_path": METRICS_PATH,
                    "static_configs": [{"targets": ["*:{}".format(METRICS_PORT)]}],
                }
            ],
        )
	```

* Defining `GrafanaDashboardProvider` e.g.
	```
	self.dashboard_provider = GrafanaDashboardProvider(self)
	```

* [Exposing metrics port](https://github.com/canonical/dex-auth-operator/pull/185/files#diff-b9ed39bbc9c0387bd3e07da31d13373745534a1cd723d3e292c73496b12e307cR36-R45) e.g.
	```
	    dex_port = ServicePort(int(self.model.config["port"]), name="dex")
        metrics_port = ServicePort(int(METRICS_PORT), name="metrics-port")

        self.service_patcher = KubernetesServicePatch(
            self,
            [dex_port, metrics_port],
            service_name=f"{self.model.app.name}",
        )
	```
What we could standardize is omitting the `relation_name` argument from `MetricsEndpointProvider` since this `metrics-endpoint` is the default one. I'm not sure about adding something to chisme since they all just require importing a lib and using it, but I 'm open to discussion if something like the one below makes sense:
```
def create_metrics_endpoint(charm_self, metrics_path, metrics_port)
	        return MetricsEndpointProvider(
            charm=charm_self,
            jobs=[
                {
                    "metrics_path": metrics_path,
                    "static_configs": [{"targets": ["*:{}".format(metrics_port)]}],
                }
            ],
        )

# example usage
# self.prometheus_provider = create_metrics_endpoint(self, METRICS_PATH, METRICS_PORT)
```

and similiarly for exposing service port. The above example about metrics endpoint could go a bit further and support tuples of metrics path and metrics port in order to cover cases with multiple scrape endpoints like [MLflow's one](https://github.com/canonical/mlflow-operator/blob/main/src/charm.py#L94-L96).

**Comment by orfeas-k** [comment]
# Testing prometheus and prometheus alerts

## Summary of current testing workflow

At the moment, we could say that the most extensive testing is done in [argo-controller](https://github.com/canonical/argo-operators/blob/main/charms/argo-controller/tests/integration/test_charm.py#L133-L247) and maybe [seldon-core-operator](https://github.com/canonical/seldon-core-operator/blob/main/tests/integration/test_charm.py#L151-L284), where we also reproduce the state where one alert should fire. Summarizing how testing COS integration in our charms looks like (when fully implemented):

- Define a retry_for_5_attempts function using `tenacity.Retrying`. In other places like Seldon, we use decorator `@tenacity.retry`.
- Define constants (cos charms' names and `scrape_config`).
- Deploy cos charms (not through bundle) from `latest/stable`.
	+ prometheus
	+ grafana
	+ prometheus_scrape
- Add relations
  * app - prometheus_scrape 
  * app - grafana
  * prometheus - grafana
  * prometheus - prometheus_scrape
- Assert everything is green/active.
- Get prometheus unit IP
- Test prometheus deployment (5 attempts):
	+ request at `http://{prometheus_unit_ip}:9090/api/v1/query?query=up{{juju_application="{APP_NAME}"}}`
	+ assert `request=successful`, `juju_application==app_name`, `juju_model=model_name`
- Test prometheus targets (5 attempts) (Verify that Prometheus receives the same set of targets as specified):
	+ request at `http://{prometheus_unit_ip}:9090/api/v1/targets`
	+ assert `response=successful`, `discovered_labels["juju_application"] == "APP_NAME"`
- Test prometheus alert rules (Verify that Prometheus receives the same set of alert rules as specified):
	+ request at `http://{prometheus_unit_ip}:9090/api/v1/rules`
	+ assert `response=successful` plus parse response[data] and assert it contains each alert rule under `/src/prometheus_alert_rules/*` yaml

Now, the above is what is implemented in all of our charms. In most cases, there are discrepancies between our charms though which summarized are:

* While we may split tests between parts `Test prometheus deployment`, `Test prometheus targets` and `Test prometheus alert rules`, we are not consistent with what each part includes which could mean that we include under `Test prometheus deployment` things that in another charm are done under `Test prometheus alert rules`.
* testing the same things but in different order.
* testing the same things but in some places have slightly different assertions.
* Charms include different helper functions.
* Not all the same parts are tested in all charms

You can view the discrepancy for each specific charm's testing code below:

<details> <summary> Detailed list of discrepancies</summary>

* [dex](https://github.com/canonical/dex-auth-operator/blob/main/tests/integration/test_charm.py#L197) implements the same logic with argo-controller (copy-paste). Differences are:
	- in test prometheus deployment part, it also asserts the alert's value after `model_name` (checking that unit is available)
	- it doesn't test none of:
		+ prometheus targets
		+ prometheus alert rules (verify their yamls are returned from prometheus)
* [seldon-core-operator](https://github.com/canonical/seldon-core-operator/blob/main/tests/integration/test_charm.py#L151-L284) differences are:
	- there's a check_alert_propagation that uses `@tenacity.retry` decorator and encapsulates logic for checking alerts that are firing
	- this skips the part of **Test prometheus deployment** and starts by saying Testing prometheus alerts rules (Verify that Prometheus receives the same set of rules as specified.) That being said, it first does the same checks with **Test prometheus targets**
	- Then Does the same with **Test prometheus deployment**
	- Then it indeed goes and **Test prometheus alert rules**
		+ Verifies number of alert rules
		+ loads many alert rules from same file
	- Tries to simulate the situation where `SeldonReconcileError` should be firing, by creating SeldonDeployment and then deleting is `Deployment`.
* [training-operator](https://github.com/canonical/training-operator/blob/main/tests/integration/test_charm.py#L131-L210)
	- uses `ops_test.juju` instead of `ops_test.model.deploy()`
	- Follows argo-controller but has only `Test prometheus deployment` part.
* [envoy](https://github.com/canonical/envoy-operator/blob/main/tests/integration/test_charm.py#L96)
	- deploys cos charms and asserts everything is active
	- there is a `test_correct_observability_setup` test that does similar assertions to `Test prometheus deployment` part
* [istio-pilot](https://github.com/canonical/istio-operators/blob/main/tests/test_cos_integration.py#L49): same as argo-controller
* [jupyter-controller](https://github.com/canonical/notebook-operators/blob/main/charms/jupyter-controller/tests/integration/test_charm.py#L65): same as argo-controller. Has those [different assertions](https://github.com/canonical/notebook-operators/blob/main/charms/jupyter-controller/tests/integration/test_charm.py#L107-L108) and [those](https://github.com/canonical/notebook-operators/blob/main/charms/jupyter-controller/tests/integration/test_charm.py#L146)
* [katib-controller](https://github.com/canonical/katib-operators/blob/main/charms/katib-controller/tests/integration/test_charm.py): Has no tests at all
* [kfp-api](https://github.com/canonical/kfp-operators/blob/main/charms/kfp-api/tests/integration/test_charm.py#L182-L241): tests only prometheus deployment (also exposes attempt number)
* [knative charms](https://github.com/canonical/knative-operators/blob/main/tests/test_cos_integration.py): Deploys and asserts prometheus bundle
* [metacontroller](https://github.com/canonical/metacontroller-operator/blob/main/tests/integration/test_charm.py#L52): Has only `test prometheus deployment` part
* minio:
  * [unit test](https://github.com/canonical/minio-operator/blob/main/tests/unit/test_charm.py#L388-L412): relates to a mock app and tests the targets exposed in the relation
  * [integration tests](): Has only `test prometheus deployment` part.

</details>

Thus:

## How do tests ensure alert rules are working as expected?
They:
* Send a request to prometheus "charm's unit is available" endpoint and ensure "charm is included" in the response metrics and unit is up (in some cases)
* Send a request prometheus' targets endpoint and ensure charm's label is included in labels returned.
* Send a request to prometheus alert rules endpoint and confirms that alerts are included there
* (Seldon): Reproduces the state where one of its rules should be firing and asserts that it is firing. 

## Chisme work
Helper functions that we could have in chisme (if we decide we need those, see Concerns below):
* Deploy (and assert?) COS charms bundle that would include sth like [this](https://github.com/canonical/argo-operators/blob/main/charms/argo-controller/tests/integration/test_charm.py#L135-L156)
* [Test prometheus deployment](https://github.com/canonical/argo-operators/blob/main/charms/argo-controller/tests/integration/test_charm.py#L162-L178) (or [better wording here](https://github.com/canonical/envoy-operator/blob/main/tests/integration/test_charm.py#L118-L131))
* [Test prometheus targets](https://github.com/canonical/argo-operators/blob/main/charms/argo-controller/tests/integration/test_charm.py#L180-L193)
* Assert prometheus has scraped anything which would block tests to move further until prometheus has actually scraped something. This could be reworded to "Wait for prometheus to scrape" and could possibly remove the need to have retries on every different part. (from a discussion we had with @DnPlas). This should take into account that Prometheus scrapes every 1 minute and it also depends on specific alerts, since some alerts (range queries) could require at least 2 scraped data points.
* [assert unit is available](https://github.com/canonical/seldon-core-operator/blob/main/tests/integration/test_charm.py#L167-L178)
* generic assert_alert function
* [Assert prometheus receives all rules under `src/prometheus_alert_rules`](https://github.com/canonical/argo-operators/blob/main/charms/argo-controller/tests/integration/test_charm.py#L197-L239). This should take into account that [many alerts can be included in one alert rule file](https://github.com/canonical/seldon-core-operator/blob/main/tests/integration/test_charm.py#L225-L229).

## Concerns/issues
* In all of our charms, the tests are named `test_prometheus_grafana_integration`. Problem with that is that:
  * we could split testing those two to separate tests (and the different test cases too) 
  * such test deploys Grafana but it doesn't include any tests for it apart from asserting its status
* We hit directly `prometheus`** instead of using `grafana-agent-k8s` which is how we deploy CKF-COS in a real world scenario.

** (Most of the time) We don't hit directly prometheus but rather using [prometheus-scrape-config-k8s-operator](https://github.com/canonical/prometheus-scrape-config-k8s-operator) in order to define the scrape_interval.

### Open implementation questions
I thought of adding those under #838 but they were a bit more technical so I kept them here for now:
* Should we be testing that metrics port is accessible in an integration or unit test (like minio does)?
* What assertions should we be making on an alert request? Are [all of those](https://github.com/canonical/dex-auth-operator/blob/e4495753fc34106596621c78bbf0797046d68dcf/tests/integration/test_charm.py#L238-L248) needed?
* Scrape interval at the moment is configured to 30 seconds. Should we reduce this even more in order to speed up tests, considering always if no specific configuration is done, this will default to 1 minute in CKF-COS integration (need to verify this).

**Comment by DnPlas** [comment]
>I'm not sure about adding something to chisme since they all just require importing a lib and using it, but I 'm open to discussion if something like the one below makes sense:
> 
> ```
> def create_metrics_endpoint(charm_self, metrics_path, metrics_port)
> 	        return MetricsEndpointProvider(
>             charm=charm_self,
>             jobs=[
>                 {
>                     "metrics_path": metrics_path,
>                     "static_configs": [{"targets": ["*:{}".format(metrics_port)]}],
>                 }
>             ],
>         )
> 
> # example usage
> # self.prometheus_provider = create_metrics_endpoint(self, METRICS_PATH, METRICS_PORT)
> ```
> 
> and similiarly for exposing service port. The above example about metrics endpoint could go a bit further and support tuples of metrics path and metrics port in order to cover cases with multiple scrape endpoints like [MLflow's one](https://github.com/canonical/mlflow-operator/blob/main/src/charm.py#L94-L96).

@ca-scribner and I were discussing about this re-usable code, and I think it would be worth having somewhere. Maybe something that exposes the metrics endpoint in the `Service` and also creates the `MetricsEndpointProvider` object is worth having.

**Comment by NohaIhab** [comment]
Thanks @orfeas-k for looking into this in depth, great exploration!
some comments:
1. in regards to https://github.com/canonical/bundle-kubeflow/issues/823#issuecomment-1963636841, I do see some value in having an API in chisme with some common attributes as the default such as the relation name and the `metrics_path. Have you considered to have the helper also include creating the service port?
2. For integration tests, I believe we should deploy and hit `grafana-agent-k8s` either in every charm integration, or possibly as a bundle test to cover what a CKF deployment would have.
3. About testing dashboards, how about looking at the relation data for grafana? if possible, that can work to assert on the content of the dashboard and that it is indeed populated. iirc @nishant-dash was doing that during a debugging session.

**Comment by DnPlas** [comment]
> ## Concerns/issues
> 
>     * In all of our charms, the tests are named `test_prometheus_grafana_integration`. Problem with that is that:
>       
>       * we could split testing those two to separate tests (and the different test cases too)

Agreed, we definitely need to have more explicit test cases that perhaps just run one or two assertions instead of embedding everything in a test case.
Also agree on splitting the testing between prometheus scraping integration and grafana.

>       * such test deploys Grafana but it doesn't include any tests for it apart from asserting its status
> 
>     * We hit directly `prometheus`** instead of using `grafana-agent-k8s` which is how we deploy CKF-COS in a real world scenario.
> 

I think we should get closer to what the real-life scenario would be.

> 
> ** (Most of the time) We don't hit directly prometheus but rather using [prometheus-scrape-config-k8s-operator](https://github.com/canonical/prometheus-scrape-config-k8s-operator) in order to define the scrape_interval.
> ### Open implementation questions
> 
> I thought of adding those under #838 but they were a bit more technical so I kept them here for now:
> 
>     * Should we be testing that metrics port is accessible in an integration or unit test (like minio does)?

I think that it is worth it to avoid issues with the endpoint not being reachable.

> 
>     * What assertions should we be making on an alert request? Are [all of those](https://github.com/canonical/dex-auth-operator/blob/e4495753fc34106596621c78bbf0797046d68dcf/tests/integration/test_charm.py#L238-L248) needed?

I see what you mean, perhaps asserting the name of the app and its model is not really necessary as the query itself has this information, making it redudant and kind of pointless. I think though the actual content of the result of the query is what matters and then compare that to what you'd expect. For instance, if you are testing that some alert is firing or not under a controlled scenario.

> 
>     * Scrape interval at the moment is configured to 30 seconds. Should we reduce this even more in order to speed up tests? We should always consider if no specific configuration is done, this will default to 1 minute in CKF-COS integration.

I think this is worth asking the Observability team.

**Comment by orfeas-k** [comment]
@NohaIhab 
1. Agreed, and this is according to @DnPlas point too.
2. Agreed too that we should have grafana-agent-k8s in our charms' tests too, as also @DnPlas pointed.
3. I messaged Nishant and played around a bit with that and it turns out that:
  * I can actually get the relation's data from grafana-agent-k8s and decode them afterwards with
	```
	juju show-unit grafana-agent-k8s/0 --format json | jq -r '.[] | ."relation-info" | .[] ."application-data" | .dashboards' | jq -r '.templates | .[] | .content' | base64 -d | xz -d
	# would need to implement something to be able to select which charm's data we 're looking at
	```
	However, the data there doesn't include the data's current value, rather only how it is generated e.g.
	```
	...
	      "targets": [
        {
          "datasource": "${prometheusds}",
          "exemplar": false,
          "expr": "argo_workflows_count{origin_prometheus=~\"^$dc$\",kubernetes_namespace=~\"$ns\",status=\"Failed\"}",
          "instant": true,
          "interval": "",
          "legendFormat": "",
          "queryType": "randomWalk",
          "refId": "A"
        }
      ],
      "title": "WF Failed",
      "transparent": true,
      "type": "stat"
    },
	```

**Comment by orfeas-k** [comment]
@DnPlas 

> * Should we be testing that metrics port is accessible in an integration or unit test (like minio does)?
>
> I think that it is worth it to avoid issues with the endpoint not being reachable.

Do you mean that it is worth testing this in integration tests, right?

**Comment by DnPlas** [comment]
> @DnPlas
> 
> > * Should we be testing that metrics port is accessible in an integration or unit test (like minio does)?
> > 
> > I think that it is worth it to avoid issues with the endpoint not being reachable.
> 
> Do you mean that it is worth testing this in integration tests rather than just unit, right?

Yes, I believe this will fit correctly in an integration test.
