### ISSUE TITLE
Bump the supported Juju version

### ISSUE THREAD

**Issue by ca-scribner** [canonical/bundle-kubeflow#825]
### Context

Kubeflow 1.8 was released supporting (and tested on) Juju 3.1.  [3.1 is near end of life](https://juju.is/docs/juju/roadmap#heading--juju-release-schedule) - we need to bump the supported version for future releases (1.9+).

Open questions:
1. Which version of Juju do we target?
2. Do we also backport support to Charmed Kubeflow 1.8?
3. Should our CI support exactly one version of Juju, or should we support a matrix?
  a. Maybe repo CI supports a specific version, while bundle integration tests support a matrix? 

### What needs to get done

1. Decide all open questions and add additional DoD/tasks as appropriate
2. Test and release Charmed Kubeflow 1.9 for an appropriate Juju version

### Definition of Done

1. Charmed Kubeflow 1.9 released and tested for an appropriate Juju version

**Comment by nishant-dash** [comment]
Just wanted to add that **if** you do target a single version of juju at a time rather than a matrix of releases, it would make sense to me that LTS versions of juju are targeted

**Comment by ca-scribner** [comment]
agreed!  I think when we implement this should be just after 3.5 is released, so that'll work out perfectly

**Comment by DnPlas** [comment]
Closing as we are tracking this effort in https://github.com/canonical/bundle-kubeflow/issues/944
