### ISSUE TITLE
Charms to be integrated with grafana

### ISSUE THREAD

**Issue by orfeas-k** [canonical/bundle-kubeflow#834]
This is a tracker issue to document progress with CKF charms that can be integrated with Grafana (aka provide a functional and useful grafana dashboard) 

- [ ] [admission-webhook](https://github.com/canonical/admission-webhook-operator)
- [x] [argo-controller](https://github.com/canonical/argo-operators/tree/main/charms/argo-controller/src) There is a grafana dashboard that looks to be working well.
- [ ] [dex](https://github.com/canonical/dex-auth-operator)
- [x] [envoy](https://github.com/canonical/envoy-operator) Some metrics in the dashboard are working. There are a handful of metrics configures there which I 'm not sure if all are needed in our envoy case. Issue https://github.com/canonical/envoy-operator/issues/73
- [ ] [istio-gateway](https://github.com/canonical/istio-operators/blob/main/charms/istio-gateway/src/charm.py)
- [ ] [istio-pilot](https://github.com/canonical/istio-operators/tree/main/charms/istio-pilot/src)
- [x] [jupyter-controller](https://github.com/canonical/notebook-operators/tree/main/charms/jupyter-controller) Its dashboard doesn't seem to work. Exposes two metrics saying "No data".
- [ ] [jupyter-ui](https://github.com/canonical/notebook-operators/tree/main/charms/jupyter-ui)
- [x] [katib-controller](https://github.com/canonical/katib-operators/tree/main/charms/katib-controller) There is a dashboard that shows current experiments and trials. However, it could be improved depending on what decision we will take about grafana dashboards and given that katib-controller provides adequate metrics.
- [ ] [katib-db-manager](https://github.com/canonical/katib-operators/tree/main/charms/katib-db-manager)
- [ ] [katib-ui](https://github.com/canonical/katib-operators/tree/main/charms/katib-ui)
- [ ] [kfp-api](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-api)
- [ ] [kfp-metadata-writer](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-metadata-writer)
- [ ] [kfp-persistence](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-persistence)
- [ ] [kfp-profile-controller](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-profile-controller)
- [ ] [kfp-schedwf](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-schedwf)
- [ ] [kfp-ui](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-ui)
- [ ] [kfp-viewer](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-viewer)
- [ ] [kfp-viz](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-viz)
- [ ] [knative-eventing](https://github.com/canonical/knative-operators/tree/main/charms/knative-eventing)
- [ ] [knative-operator](https://github.com/canonical/knative-operators/tree/main/charms/knative-operator)
- [ ] [knative-serving](https://github.com/canonical/knative-operators/tree/main/charms/knative-serving)
- [ ] [kserve-controller](https://github.com/canonical/kserve-operators/blob/main/charms/kserve-controller/src/charm.py)
- [ ] [kubeflow-dashboard](https://github.com/canonical/kubeflow-dashboard-operator)
- [ ] [kubeflow-rofiles(kfam)](https://github.com/canonical/kubeflow-profiles-operator/blob/main/src/charm.py)
- [ ] [kubeflow-roles](https://github.com/canonical/kubeflow-roles-operator/)
- [ ] [kubeflow-volumes](https://github.com/canonical/kubeflow-volumes-operator/blob/main/src/charm.py)
- [ ] [metacontroller](https://github.com/canonical/metacontroller-operator/blob/main/src/charm.py)
- [x] [minio](https://github.com/canonical/minio-operator/) There's a grafana dashbaord that only shows N/A under all metrics.
- [ ] [mlmd](https://github.com/canonical/mlmd-operator)
- [ ] [oidc-gatekeeper](https://github.com/canonical/oidc-gatekeeper-operator/blob/main/src/charm.py)
- [ ] [pvcviewer-operator](https://github.com/canonical/pvcviewer-operator/)
- [x] [seldon-controller-manager](https://github.com/canonical/seldon-core-operator) The grafana dashboard doesn't seem to work. I applied two SeldonDeployments and the `Models` metric showed "No Data"
- [ ] [tensorboard-controller](https://github.com/canonical/kubeflow-tensorboards-operator/tree/main/charms/tensorboard-controller)
- [ ] [tensorboard-web-app](https://github.com/canonical/kubeflow-tensorboards-operator/blob/main/charms/tensorboards-web-app/src/charm.py)
- [ ] [training-operator](https://github.com/canonical/training-operator/blob/main/src/charm.py)

Update: There is also MLflow that its dashboard presents `No data`.

**Comment by natalytvinova** [comment]
I can confirm that jupyter notebooks, minio and seldon controller are missing data, while katib-controller and argo-controller work on the current deployment. If we could also include MLflow to that list: MLflow metrics Dashboard is also missing data.

**Comment by orfeas-k** [comment]
#### MinIO

The issue there is that we have a label `job=scrabe_jobs` which is making the panel not rendering anything. Also, metrics `minio_cluster_capacity` is not provided by MinIO (anymore I guess).

**Comment by orfeas-k** [comment]
Closing since these are now tracked in [spreadsheet](https://docs.google.com/spreadsheets/d/1FnBtkJb2VeQSF1FLF38-yu3bdDzfMTp4q164_cBP550/edit?gid=0#gid=0)
