### ISSUE TITLE
Make namespaces configurable

### ISSUE THREAD

**Issue by nishant-dash** [canonical/bundle-kubeflow#844]
### Context

Is it possible to make the k8s namespace (and in turn the juju model name) configurable? so that its not hard coded to kubeflow? 

### What needs to get done

N/A

### Definition of Done

Be able to deploy kubeflow with a namespace other then kubeflow

**Comment by ca-scribner** [comment]
Love the idea, but we'd need to do changes upstream.  Agreed it should be configurable, but there are places in the upstream project that assume the namespace is always `kubeflow`

**Comment by kimwnasptd** [comment]
Marking as duplicate of https://github.com/canonical/bundle-kubeflow/issues/698
