### ISSUE TITLE
Upgrade from CKF 1.7 to CKF 1.7 Patch 1 do not work

### ISSUE THREAD

**Issue by Barteus** [canonical/bundle-kubeflow#847]
### Bug Description

The section [Upgrade charms](https://charmed-kubeflow.io/docs/upgrade-17-171#heading--upgrade--charms) does not work. 
1. Missing mentioning the scaling down to 0 before refresh
2. Some charms return ERROR when refresh
```
ERROR Juju on containers does not support updating deployment info for services.
The new charm's metadata contains updated deployment info.
You'll need to deploy a new charm rather than upgrading if you need this change.
 not supported (not supported)
charm "kfp-profile-controller": already up-to-date
Added charm-hub charm "kfp-schedwf", revision 1052 in channel 2.0/stable, to the model
ERROR Juju on containers does not support updating deployment info for services.
The new charm's metadata contains updated deployment info.
You'll need to deploy a new charm rather than upgrading if you need this change.
 not supported (not supported)
charm "kfp-ui": already up-to-date
Added charm-hub charm "kfp-viewer", revision 1064 in channel 2.0/stable, to the model
ERROR Juju on containers does not support updating deployment info for services.
The new charm's metadata contains updated deployment info.
You'll need to deploy a new charm rather than upgrading if you need this change.
 not supported (not supported)
```

### To Reproduce

Follow the upgrade guide to the step - [Upgrade charms](https://charmed-kubeflow.io/docs/upgrade-17-171#heading--upgrade--charms)

### Environment

ubuntu@ip-172-31-31-138:~/workspace$ snap list
Name              Version        Rev    Tracking         Publisher   Notes
amazon-ssm-agent  3.2.1630.0     7628   latest/stable/…  aws✓        classic
core18            20231027       2812   latest/stable    canonical✓  base
core20            20231123       2105   latest/stable    canonical✓  base
juju              2.9.46         25672  2.9/stable       canonical✓  classic
kubectl           1.29.2         3180   latest/stable    canonical✓  classic
lxd               5.0.3-51452c3  26881  5.0/stable/…     canonical✓  -
microk8s          v1.24.17       5872   1.24/stable      canonical✓  classic
snapd             2.61.1         20671  latest/stable    canonical✓  snapd

### Relevant Log Output

Output: [output.log](https://github.com/canonical/bundle-kubeflow/files/14585995/output.log)

### Expected

Upgrade procedure works and/or bundle 1.7.1 provided.

**Comment by misohu** [comment]
Added the information into the doc about scaling down and up for charms. Plus I have updated channels for kfp components. Before the components were pointing to channel `2.0/stable` instead of the correct `2.0-alpha.7/stable`.
