### ISSUE TITLE
Add `cosl` to `requirements.in`, remove `juju_topology`, when bumping prometheus-scrape charm lib to revision 40

### ISSUE THREAD

**Issue by ca-scribner** [canonical/bundle-kubeflow#849]
### Context

the prometheus-scrape charm lib added a requirement for the `cosl` package to be installed by the charm.  When we bump the library, we need to add this package otherwise the charm will be inoperable.

### What needs to get done

[here](https://github.com/canonical/envoy-operator/pull/74/files) is an example of the changes required.  Steps to fix this are:
```
charmcraft fetch-lib
tox -e update-requirements
rm lib/charms/observability_libs/v0/juju_topology.py
```

### Definition of Done

When all charms we have are using the updated libs.  This likely will occur during the 1.9 release cycle

**Comment by orfeas-k** [comment]
In that PR, my understanding is that the following comment is wrong and cosl comes from prometheus scrape as the issue describes
```
# from observability_libs.v0.juju_topology.py
cosl
```

**Comment by orfeas-k** [comment]
We can use this as a reference for instructions when we need to update more charms' libraries but closing it, since it doesn't serve any purpose being open.
