### ISSUE TITLE
Specify the versions of Juju that we support on Charmed Kubeflow's supported versions page

### ISSUE THREAD

**Issue by ca-scribner** [canonical/bundle-kubeflow#853]
### Context

Our [support versions](https://charmed-kubeflow.io/docs/supported-versions) docs page lists kubernetes versions but not Juju versions.  We do have requirements on what Juju version can be used, so we should include that here as well.  

### What needs to get done

1. add juju versions to [supported versions](https://charmed-kubeflow.io/docs/supported-versions), perhaps starting with the next ckf release

### Definition of Done

see above

**Comment by orfeas-k** [comment]
Done
