### ISSUE TITLE
Investigate which CKF charms provide metrics by default

### ISSUE THREAD

**Issue by orfeas-k** [canonical/bundle-kubeflow#855]
### Context

In order to evaluate better the work for integrating CKF charms with Observability charms, we need to investigate which CKF charms provide metrics by default. The state right now with charms alerts is documented in https://github.com/canonical/bundle-kubeflow/issues/837.

At the same time, we will document also the metrics that those charms provide.

### What needs to get done

Document for every charm:
1. If it provides metrics by default
2. If yes, what are those metrics? 

### Definition of Done

We know for all CKF charms what they expose.

**Comment by orfeas-k** [comment]
#### [argo-controller](https://github.com/canonical/argo-operators/tree/main/charms/argo-controller/src)
* Upstream docs on metrics exposed https://argo-workflows.readthedocs.io/en/latest/metrics 
* [argo-controller.txt](https://github.com/canonical/bundle-kubeflow/files/14822657/argo-controller.txt)

#### [dex](https://github.com/canonical/dex-auth-operator) 
* Code in upstream implementing metrics https://github.com/dexidp/dex/blob/088339fc287a24de23ffcfe7985287cef2a3b2fa/cmd/dex/serve.go#L26-L30
* [dex-auth.txt](https://github.com/canonical/bundle-kubeflow/files/14822668/dex-auth.txt)

#### [envoy](https://github.com/canonical/envoy-operator) 

- Metrics include (they call them statistics) [https://www.envoyproxy.io/docs/envoy/v1.15.0/configuration/upstream/cluster_manager/cluster_stats](https://www.envoyproxy.io/docs/envoy/v1.15.0/configuration/upstream/cluster_manager/cluster_stats) [https://www.envoyproxy.io/docs/envoy/v1.15.0/configuration/http/http_conn_man/stats](https://www.envoyproxy.io/docs/envoy/v1.15.0/configuration/http/http_conn_man/stats)
-  [envoy.txt](https://github.com/canonical/bundle-kubeflow/files/14822696/envoy.txt)


#### [istio-gateway](https://github.com/canonical/istio-operators/blob/main/charms/istio-gateway/src/charm.py)

- charm endpoint: [https://github.com/canonical/istio-operators/blob/e0d2c0261a3760366b87e7be27100393009967ac/charms/istio-gateway/src/manifest.yaml#L39-L40](https://github.com/canonical/istio-operators/blob/e0d2c0261a3760366b87e7be27100393009967ac/charms/istio-gateway/src/manifest.yaml#L39-L40) [](https://github.com/canonical/istio-operators/blob/e0d2c0261a3760366b87e7be27100393009967ac/charms/istio-gateway/src/manifest.yaml#L39-L40)
- Upstream docs on metrics (it's an envoy): [https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/statistics.html](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/statistics.html) [https://istio.io/latest/docs/ops/configuration/telemetry/envoy-stats/](https://istio.io/latest/docs/ops/configuration/telemetry/envoy-stats/)
- [istio-gateway.txt](https://github.com/canonical/bundle-kubeflow/files/14822699/istio-gateway.txt)

#### [istio-pilot](https://github.com/canonical/istio-operators/tree/main/charms/istio-pilot/src) 
* upstream docs [https://istio.io/latest/docs/concepts/observability/](https://istio.io/latest/docs/concepts/observability/)
* [istio-pilot.txt](https://github.com/canonical/bundle-kubeflow/files/14822704/istio-pilot.txt)

**Comment by orfeas-k** [comment]
### Upstream apps that do not already expose metrics
* jupyter-ui
* katib-ui
* kfp-metadata-writer
* kfp-persistence
* kfp-profile-controller
* kubeflow-volumes
* tensorboards-web-app

**Comment by kimwnasptd** [comment]
Regarding all the K8s Controllers from `kubeflow/kubeflow` (notebooks, profiles, tensorboards) they will get some quite useful metrics by default because of `controller-runtime` golang package, that comes with Kubebuilder
https://book.kubebuilder.io/reference/metrics-reference

Those are perfect for capturing if the controllers are working as expected, and it's great it will be handled by default.

In order for this to happen though, someone upstream will need to bump the [`controller-runtime`](https://github.com/kubeflow/kubeflow/blob/bd7f250df22e144b114177536309d28651b4ddbb/components/notebook-controller/go.mod#L14) package from 0.11 to 0.16.3

**Comment by orfeas-k** [comment]
[Related sheet](https://docs.google.com/spreadsheets/d/1FnBtkJb2VeQSF1FLF38-yu3bdDzfMTp4q164_cBP550/edit#gid=0)
