### ISSUE TITLE
bump `juju` in all gh `workflows` 

### ISSUE THREAD

**Issue by DnPlas** [canonical/bundle-kubeflow#862]
### Context

To support juju 3.4, we need to bump the channel that is used for installing `juju` in the integration testing environment of all our repositories.

Optional: bump the versions of `ops`, `pytest-operator` and `python-libjuju` if it is necessary for the tests to pass.

### What needs to get done

Do a cannon run that replaces `juju-channel: 3.1` with `juju-channel: 3.4` in all the repositories maintained by the CKF team. This has to be done in both `main` and `track/<version>` (only the corresponding version to CKF 1.8) branches.

### Definition of Done

The CI for integration tests runs with juju 3.4.

**Comment by DnPlas** [comment]
Failing CIs due to podspec charms going into waiting state `waiting for container`:

* https://github.com/canonical/argo-operators/pulls
* https://github.com/canonical/envoy-operator/pulls
* https://github.com/canonical/istio-operators/pulls

Failing CIs due to another reasons:

* https://github.com/canonical/notebook-operators/pull/348
* https://github.com/canonical/ngc-integrator-operator/pull/9
* https://github.com/canonical/metacontroller-operator/pull/105
* https://github.com/canonical/kubeflow-roles-operator/pull/80
* https://github.com/canonical/pvcviewer-operator/pull/32

**Comment by orfeas-k** [comment]
Need to send PRs also for 
* MLflow https://github.com/canonical/mlflow-operator/pulls
* bundle tests:
  * full bundle tests https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/full-bundle-tests.yaml#L37
  * AKS https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/deploy-to-aks.yaml#L28
  * EKS https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/deploy-to-eks.yaml#L49

I 'll try to do it in the coming days.

**Comment by DnPlas** [comment]
This work was completed in several PRs, all CIs should now be running with juju 3.5. Closing.
