### ISSUE TITLE
bump version of `ops` used by all charms as part of the Charmed Kubeflow 1.9 release

### ISSUE THREAD

**Issue by ca-scribner** [canonical/bundle-kubeflow#868]
### Context

There have been a number of bugfixes and other changes to `ops` recently.  As part of the Charmed Kubeflow 1.9 release, we should bump `ops` to the most recent working version at time of release.  

While doing this task, it likely makes sense to bump other packages as well.  For example, this task could be completed by ensuring `ops` is unpinned in `requirements.in` and then merging the most recent Renovate PR for every repo

As part of this task, should we pin `ops<3` or leave it unpinned?

### What needs to get done

1. `ops` version in all charmed kubeflow charms is bumped to the most recent working version (ideally the most recent version, but if there's a blocker we can pin it lower and file issues)
2. CI is passing for these charms

### Definition of Done

see above

**Comment by DnPlas** [comment]
All PRs are now merged, we can close this issue.
