### ISSUE TITLE
Update the Kubeflow notebook creation page docs for Kubeflow 1.9

### ISSUE THREAD

**Issue by ca-scribner** [canonical/bundle-kubeflow#873]
### Context

[This task](https://warthogs.atlassian.net/browse/KF-5435) implemented an [updated doc](https://discourse.charmhub.io/t/configure-the-kubeflow-notebook-creation-page/13901) for configuring the jupyter-ui charm.  As part of the 1.9 release, we should replace the [existing doc](https://charmed-kubeflow.io/docs/dynamically-configure-the-notebook-images-list) with this updated version.  

### What needs to get done

1. update the published documentation to use the new doc

### Definition of Done

see above

**Comment by mvlassis** [comment]
The new documentation page has been updated and can be found [here](https://charmed-kubeflow.io/docs/configure-the-kubeflow-notebook-creation-page).

The old documentation page has been archived as it contains a subset of the sections found in the new page. It can be found [here](https://discourse.charmhub.io/t/dynamically-configure-the-notebook-images-list/11130).
