### ISSUE TITLE
`ModuleNotFoundError: No module named 'markupsafe'` error at build time

### ISSUE THREAD

**Issue by DnPlas** [canonical/bundle-kubeflow#883]
### Bug Description

Charms that list `jinja2` as a requirement could result in a build failure with the following message:

```
::    :: Collecting jinja2==3.1.2
::    ::   Using cached Jinja2-3.1.2.tar.gz (268 kB)
::    ::     ERROR: Command errored out with exit status 1:
...
::    ::       File "/tmp/pip-install-jf2rwxln/jinja2/src/jinja2/environment.py", line 14, in <module>
::    ::         from markupsafe import Markup
::    ::     ModuleNotFoundError: No module named 'markupsafe'
::    ::     ----------------------------------------
```

The issue is due to https://github.com/pallets/jinja/issues/1496 and https://github.com/canonical/charmcraft/issues/1664.

#### Potential fixes

1. Use `ubuntu 22.04` as base for `build-on` since this OS version will have a newer version of `setuptools`
2. List the packages that depend on `jinja2` in the `charm-binary-python-packages` to avoid building them from source. For example `charm-binary-python-packages: [charmed-kubeflow-chisme]`
3. If `jinja2` is a direct dependency of a charm, use the above method

### To Reproduce

Try building any of the packages that list `jinja2` in the requirements file:

1. Any of the `kfp-operators`
2. `istio-pilot`

### Environment

* Ubuntu 20.04
* Charmcraft latest/candidate (2.6.0)

### Relevant Log Output

Logs: https://pastebin.canonical.com/p/DhpBRNn7pz/

### Workaround
Install `jinja2` from binary as we do in https://github.com/canonical/kfp-operators/pull/443

**Comment by ca-scribner** [comment]
I see istio-pilot listed here, but I don't see the CI that is breaking.  Is istio-pilot blocked by this too?

**Comment by DnPlas** [comment]
I have seen it intermittently in `istio-operator`'s CI: [here](https://github.com/canonical/istio-operators/actions/runs/8703753304/job/23870604559#step:4:276) is an example of this.

**Comment by ca-scribner** [comment]
of course it has to be intermittent ... :/

**Comment by orfeas-k** [comment]
I see that in katib-controller as well, although the charm is packed after all and running.

**Comment by DnPlas** [comment]
> The resolution is to bump `markupsafe` from version 2.1.3 to version 2.1.5. This issue is happening in multiple charms. You can update the lib:
> 
>     1. Update `jinja2` if you have it in all requirements
> 
> 
> ```
> for pattern in "requirements.in" "requirements-fmt.in" "requirements*.in"; do find . -type f -name "$pattern" -exec bash -c "cd \$(dirname "{}") && pip-compile \$(basename "{}") -P jinja2 --upgrade" \;; done
> ```
> 
>     2. Update `charmed-kubeflow-chisme` if you don't have `jinja2` it in all requirements
> 
> 
> ```
> for pattern in "requirements.in" "requirements-fmt.in" "requirements*.in"; do find . -type f -name "$pattern" -exec bash -c "cd \$(dirname "{}") && pip-compile \$(basename "{}") -P charmed-kubeflow-chisme --upgrade" \;; done
> ```

While @misohu's suggestion is accurate, I have found out that bumping just jinja2 everywhere should resolve the issue as long as we get v3.1.4 or above. I did it for several repositories and in combination with charmcraft 3.1 (from latest/candidate) it is working.

**Comment by DnPlas** [comment]
Closing this as the `jinja2` bump worked for all charms. The only missing repository is `kfp-operators`, but the error in the CI seems unrelated to this.

**Comment by orfeas-k** [comment]
We need to backport this to 1.8 related track branches.

**Comment by DnPlas** [comment]
> We need to backport this to 1.8 related track branches.

All 1.8 related github branches have been updated with the proposed changes. Feel free to re-open if anything is missing or if the issue is still present.
