### ISSUE TITLE
Update our track strategy for the Kubeflow 1.9 release

### ISSUE THREAD

**Issue by ca-scribner** [canonical/bundle-kubeflow#895]
### Context

In recent releases we have not promoted charms to `latest/stable` in the charm repositories, leading to confusion.  This was in part because we discussed removing the `latest` track entirely from our charms, instead opting to update our default track to whatever is the most recent release (say `1.8`). 

 We should define what we want (do we use `latest` at all?  do we promote to `latest/stable`? etc) before the 1.9 release

### What needs to get done

1. define and document our track strategy for charms

### Definition of Done

1. track strategy for charms is defined and documented

**Comment by orfeas-k** [comment]
Discussed in https://docs.google.com/document/d/1WYWf8BEbB_nPasVwBWaDhhmnu461hZdFNVSAA4an1-s/edit#heading=h.lfxtpxci0bkl

**Comment by orfeas-k** [comment]
#### Context
(a) What should we do with the latest/stable track? Where should it point to and if it should even exist?
(b) What would be the default track when deploying a charm?
#### Options
For (a), options are:
1. latest/stable → <version>/stable - should we do this just for the bundle or for charms as well?
1. get rid of latest/stable - means we will have to update the default one
1. latest/stable → latest/edge
For (b), options are:
1. `<version>/stable` is default
1. keep `latest/stable` as default
1. `latest/edge` is default

#### Conclusions:
1. Hide `latest/stable` in both bundle and charms
1. Change the default track to be a version
1. Expect `latest/candidate` and `latest/beta` only for testing (SolQA), but we do NOT expect anyone to use it in our docs
1. Let’s deprecate/remove/hide the 1.7 (and previous unmaintained) tracks for both bundle and corresponding charms

**Comment by NohaIhab** [comment]
thanks for the summary from tech topics @orfeas-k 

I've requested to change the default tracks for the bundle and charms. They are now in effect. The default tracks for the kubeflow bundle and charms have been changed to those corresponding to `1.9`.

**Comment by NohaIhab** [comment]
I have filed https://github.com/canonical/bundle-kubeflow/issues/1126 to track closing the 1.7 channels once we check it is not being used, this issue can be closed now.
