### ISSUE TITLE
Bump K8s version to 1.29 on our CI

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/bundle-kubeflow#903]
### Context

Upstream will support K8s up to 1.29 https://github.com/canonical/bundle-kubeflow/issues/900

We'll need to update the CI everywhere to use MicroK8s 1.29 as part of our 1.9 release

### What needs to get done

Update the CI on all our repos to use K8s 1.29

### Definition of Done

1. Tests are passing in each repo with newest K8s
2. The CI is updated to use K8s 1.29

**Comment by DnPlas** [comment]
All PRs have been merged, we can close this PR.
