### ISSUE TITLE
Test the upgrade path from CKF 1.8 to latest/edge (1.9)

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/bundle-kubeflow#913]
### Context

Start testing the upgrade from CKF 1.8 to 1.9, by doing the upgrade to `latest/edge`.

### What needs to get done

1. Deploy CKF 1.8
2. Prepare a document with all the steps for upgrading to `latest/edge`
3. Create issues on the way, with anything that blocked us

### Definition of Done

1. We have a document that tracks the steps for the upgrade, or a list of issues that blocked us

**Comment by misohu** [comment]
**Note for release notes**

In this PR https://github.com/canonical/notebook-operators/pull/372 we are adding config options to notebook controller

- cluster-domain: Specifies the base domain name of the Kubernetes cluster, which is used in culling to correctly resolve and address the services and resources within the cluster.
- cull-idle-time: The amount of time (in seconds) that a Jupyter notebook server can remain idle before it is automatically shut down.
- idleness-check-period: Interval (in minutes) at which the system checks for idle Jupyter notebook servers to determine if they should be culled.

**Comment by orfeas-k** [comment]
Closing due to https://docs.google.com/document/d/1Wg32O5PF8RMy7ng7hY9gX37lHnwmszyBt4D2lI_MSjQ/edit#heading=h.gkp9mi5dbjw
