### ISSUE TITLE
Update terminology of ROCKs to rocks

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/bundle-kubeflow#916]
### Context

We want to clean-up all our references for ROCKs to be rocks

Our rocks repos include as of today
- https://github.com/canonical/kubeflow-rocks
- https://github.com/canonical/katib-rocks
- https://github.com/canonical/pipelines-rocks/
- https://github.com/canonical/kserve-rocks
- https://github.com/canonical/seldonio-rocks
- https://github.com/canonical/metacontroller-rock
- https://github.com/canonical/argo-workflows-rocks
- https://github.com/canonical/dex-auth-rocks
- https://github.com/canonical/resource-dispatcher-rock
- https://github.com/canonical/filebrowser-rock
- https://github.com/canonical/oidc-authservice-rock

### What needs to get done

1. Merge existing renaming PRs
    * https://github.com/canonical/pipelines-rocks/pull/88/
    * https://github.com/canonical/kubeflow-rocks/pull/92/
2. Go to the rest of the repos mentioned and update ROCKs to rocks

### Definition of Done

There are no mentions of ROCKs in our rocks repos

**Comment by DnPlas** [comment]
All PRs have been merged, closing.
