### ISSUE TITLE
Create Gtihub branches for all rocks repositories (CKF 1.8 versions)

### ISSUE THREAD

**Issue by DnPlas** [canonical/bundle-kubeflow#924]
### Context

With the CKF 1.9 release coming soon, the rocks repositories are being updated to match the newer component versions. This is problematic because the code for CKF 1.8 components will be lost, making it impossible to maintain CKF 1.8 rocks.

### What needs to get done

Create a `track/<version>`** Github branch in each rocks repository. The `HEAD` of the branch should be the last change made before upgrading the rock to its CKF 1.9 version.

** Format TBC

### Definition of Done

1. The rock repository has a `track/<version>` Github branch
2. The `main` Github branch is not altered
3. The publish job from the branch is not altered and can continue to publish rocks

**Comment by DnPlas** [comment]
Comment from @orfeas-k:

It may also be required to update the CI files, like [this](https://github.com/canonical/seldonio-rocks/blob/e09072a9ebaa901227cd6e11aee43bcbd469525e/seldon-core-operator/tox.ini#L13) as the branch name would now be different.

**Comment by mvlassis** [comment]
The relevant branches for CKF 1.8 for all rocks repositories are:
- `argo-workflows-rocks`: `track/3.3`
- `dex-auth-rocks`: `track/2.36.0`
- `filebrowser-rock`: `track/2.27.0`
- `katib-rocks`: `track/0.16`
- `kserve-rocks`: `track/0.11.2`
- `kubeflow-rocks`: `track/1.8.0`
- `metacontroller-rock`: `track/3.0.0`
- `oidc-authservice-rock`: `track/cfk-1.8`
- `pipelines-rocks`: `track/2.0`
- `resource-displatcher-rock`: `track/1.0`

**Comment by DnPlas** [comment]
> The relevant branches for CKF 1.8 for all rocks repositories are:
> 
>     * `argo-workflows-rocks`: `track/3.3`
> 
>     * `dex-auth-rocks`: `track/2.36.0`
> 
>     * `filebrowser-rock`: `track/2.27.0`
> 
>     * `katib-rocks`: `track/0.16`
> 
>     * `kserve-rocks`: `track/0.11.2`
> 
>     * `kubeflow-rocks`: `track/1.8.0`
> 
>     * `metacontroller-rock`: `track/3.0.0`
> 
>     * `oidc-authservice-rock`: `track/cfk-1.8`
> 
>     * `pipelines-rocks`: `track/2.0`
> 
>     * `resource-displatcher-rock`: `track/1.0`

Hey @mvlassis thanks for making the list, just a note, usually for charms we have the standard of `track/<major>.<minor>, and I think we should follow this format here as well. For the ones that have the `patch` version, let's remove it:

- `dex-auth-rocks`: `track/2.36.0`
- `filebrowser-rock`: `track/2.27.0`
- `kserve-rocks`: `track/0.11.2`
- `kubeflow-rocks`: `track/1.8.0`
- `metacontroller-rock`: `track/3.0.0`

**Comment by mvlassis** [comment]
@DnPlas Thanks for the input, the updated version list is:
- `argo-workflows-rocks`: `track/3.3`
- `dex-auth-rocks`: `track/2.36`
- `filebrowser-rock`: `track/2.27`
- `katib-rocks`: `track/0.16`
- `kserve-rocks`: `track/0.11`
- `kubeflow-rocks`: `track/1.8`
- `metacontroller-rock`: `track/3.0`
- `oidc-authservice-rock`: `track/cfk-1.8`
- `pipelines-rocks`: `track/2.0`
- `resource-displatcher-rock`: `track/1.0`

**Comment by mvlassis** [comment]
@orfeas-k Did the following:
- `argo-workflow-rocks`: created (this PR) [https://github.com/canonical/argo-workflows-rocks/pull/26] for backporting the updating of `argoexec`.
- `dex-auth-rock`: deleted the PR, deleted `track/2.36.0`, and recreated `track/2.36` with the proper commits.
- `filebrowser-rock`: deleted `track/2.27.0`.
- `kserve-rocks`: deleted `track/0.11.2`.
- `kubeflow-rocks`: deleted `track/1.8.0`.
- `metacontroller-rock`: deleted `track/3.0.0`.

**Comment by orfeas-k** [comment]
Regarding that comment above:
>It may also be required to update the CI files, like [this](https://github.com/canonical/seldonio-rocks/blob/e09072a9ebaa901227cd6e11aee43bcbd469525e/seldon-core-operator/tox.ini#L13) as the branch name would now be different.

This is right since it is what is being used for integration tests in the CI. But at the moment, only seldonio-rocks repository has integration tests implemented, which was not part of this effort. Thus, we can omit this part since at the moment, we do not run any integration tests for the ROCKs.

Good job @mvlassis , LGTM
