### ISSUE TITLE
Improve airgapped setup and testing scripts

### ISSUE THREAD

**Issue by NohaIhab** [canonical/bundle-kubeflow#933]
### Context

The airgapped setup and testing scripts need to be refactored for a better user and development experience.
This task is to track the areas that we think need refactoring.

### What needs to get done

Refactor the scripts to:
1. Be more generic (no hardcoding images/charms/pkgs versions) so that they work for any bundle version.
2. Add different modes for running the scripts for development and test, for example the development mode should not pull the test images.
3. Make the airgapped enviroment more persistent and the testing process more time-effective, because at the moment every time we bring up the VM the step for extracting the images and pushing them to the private registry needs to run.

### Definition of Done

The above refactoring is implemented and merged to the `bundle-kubeflow` repository.

**Comment by mvlassis** [comment]
The short code snippet at [No internet in the LXC container when starting](https://github.com/canonical/bundle-kubeflow/blob/main/tests/airgapped/README.md#common-bugs) maybe could be incorporated into `setup.sh` or `airgap.sh`, if users are very likely to encounter this issue.

**Comment by kimwnasptd** [comment]
> 1. Be more generic (no hardcoding images/charms/pkgs versions) so that they work for any bundle version.
> 2. Add different modes for running the scripts for development and test, for example the development mode should not pull the test images.

Regarding the first 2, now the `scripts/get-images.py` has an `--append-images` argument for parsing a file with extra images. So those 2 points, regarding OCI images at least, should be covered

**Comment by NohaIhab** [comment]
thanks @kimwnasptd for the update
to better break the suggested improvements down:
* to track `1.` I filed #959 and updated the description there on the tackled and remaining parts
* `2.` was indeed covered by #1038
* to track `3.`, I split it into 2 parts. For the persistence of the lxc instance I filed #1081, and for the time consumed by moving the images around I filed #1082

Closing this issue in favour of the above, for better tracking of the smaller tasks.
