### ISSUE TITLE
Run the UATs for CKF 1.9 on Charmed K8s

### ISSUE THREAD

**Issue by NohaIhab** [canonical/bundle-kubeflow#937]
### Context

This is part of the pre-release testing for CKF 1.9.
We need to deploy and run the UATs on Charmed K8s.

### What needs to get done

1. Run the UATs on Charmed K8s for CKF 1.9
2. Report any bugs that we hit

### Definition of Done

CKF 1.9 is tested on Charmed K8s

**Comment by kimwnasptd** [comment]
We'll rely on SolQA testing for this in the end
