### ISSUE TITLE
Cannot deploy Kubeflow with Juju 3.1

### ISSUE THREAD

**Issue by gustavosr98** [canonical/bundle-kubeflow#949]
### Bug Description

Supported version of Juju for Kubeflow 1.8 says on the documentation to be 3.1
https://charmed-kubeflow.io/docs/supported-versions

However, a new change in mysql-k8s charm breaks this deploying the usual way

### To Reproduce

juju deploy kubeflow --trust --channel=1.8/stable

### Environment

Juju 3.1
Kubeflow 1.8

mysql-k8s (8.0/stable rev 153)
https://github.com/canonical/mysql-k8s-operator/commit/7273a25e494bfa448980eb5b41c9d75e041ef569
https://github.com/canonical/mysql-k8s-operator/blob/main/metadata.yaml#L87-L98

### Relevant Log Output

```shell
ERROR cannot deploy bundle: cannot deploy application "katib-db": Charm feature requirements cannot be met:
  - charm requires at least one of the following:
    - charm requires all of the following:
      - charm requires feature "juju" (version < 3.0.0) but model currently supports version 3.1.8
    - charm requires all of the following:
      - charm requires feature "juju" (version >= 3.4.3) but model currently supports version 3.1.8
    - charm requires all of the following:
      - charm requires feature "juju" (version >= 3.5.2) but model currently supports version 3.1.8

Feature descriptions:
  - "juju": the version of Juju used by the model
```

### Additional Context

One possible workaround would be to add a Juju overlay to pin mysql-k8s to an older revision
https://github.com/canonical/mysql-k8s-operator/releases

Another possible workaround would be to add `--force` to the deploy command

**Comment by DnPlas** [comment]
Hi @gustavosr98, the `mysql-k8s` charm (which for us is used as the `katib-db` and `kfp-db`) is not compatible with juju 3.1 anymore, only with the versions that the error message mentions. This team is not maintainer of the `mysql-k8s` charm, so we cannot change it. Please use juju 3.4/stable (3.4.3 or 3.4.4) for fixing this.

We are going to roll a communication about the supported juju version for CKF 1.8 and later. For now we can close this issue.
