### ISSUE TITLE
Exploration for GPU spot instances on Azure how-to guide

### ISSUE THREAD

**Issue by orfeas-k** [canonical/bundle-kubeflow#954]
### Context

Explore the implementation needed for https://warthogs.atlassian.net/browse/KF-5664.

### What needs to get done

Explore how the implementation needed can be achieved in order to be able then to write a how-to guide

### Definition of Done

Exploration has been done and findings are documented in the issue.

**Comment by misohu** [comment]
Thanks @DnPlas for the work I am adding some ideas.

I went through the [guide](https://charmed-kubeflow.io/docs/aks-spot). Agree with you that we can move this to done. There are some key things I want to mention. 
- I think gpu spot instances for azure will be limited to certain regions. I am also having some hard time finding information about GPU spot instances setup on internet. 
- The aks setup guide https://ubuntu.com/tutorials/install-kubeflow-on-azure-kubernetes-service-aks#1-overview  not sure if is still valid. If it will not work I recommend checking the ci with aks [setup](https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/deploy-to-aks.yaml#L67) we use for uats. 
- The [example](https://github.com/Barteus/kubeflow-examples/tree/main/aks-spot-instances) from kubeflow examples is really old I dont think it will work out of the box. We should consider this during planning.

**Comment by orfeas-k** [comment]
@misohu We also have this AKS kubeflow setup guide https://charmed-kubeflow.io/docs/deploy-charmed-kubeflow-to-aks

**Comment by DnPlas** [comment]
Thanks @misohu for your input!

> I think gpu spot instances for azure will be limited to certain regions. I am also having some hard time finding information about GPU spot instances setup on internet.

Yeah, it was also the case for me, but from what I saw we just have to make sure to use the N series https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/ and configure them accordingly when we create the pool of VMs.

As for the regions, I guess that depends more on the user than on us, so not sure if we need to do anything about it. wdyt?

> The aks setup guide https://ubuntu.com/tutorials/install-kubeflow-on-azure-kubernetes-service-aks#1-overview not sure if is still valid. If it will not work I recommend checking the ci with aks [setup](https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/deploy-to-aks.yaml#L67) we use for uats.

We need to update those guides you are mentioning + the one @orfeas-k linked, they both seem outdated.

> The [example](https://github.com/Barteus/kubeflow-examples/tree/main/aks-spot-instances) from kubeflow examples is really old I dont think it will work out of the box. We should consider this during planning.

Agreed.

**Comment by DnPlas** [comment]
After reading https://charmed-kubeflow.io/docs/aks-spot , I do not think there is much more exploration we have to do. This document covers all the settings already, from the AKS configuration to the workload configuration. Perhaps the work we’ll have to do is:

* Probably add more examples of how to configure workloads to be scheduled in the spot instances (right now we only have pipelines). I have in mind the following:

  * Training with GPU

  * Pipelines (already covered)

* Perhaps a pipeline with specific steps going to the GPU spot instance and others staying in different node(s)

* Revisit the format and the contents just to make sure it is what we want and users can find it useful

**Comment by misohu** [comment]
Thanks @DnPlas looking good ... if we will write about the GPU training we just might have an explanation mentioning the n series instances plus a little note that not all regions might have them. Approving the issue thanks :)

**Comment by DnPlas** [comment]
Closing this issue as we have all the required information now.
