### ISSUE TITLE
Exploration for Bundle Terraform provider automation

### ISSUE THREAD

**Issue by orfeas-k** [canonical/bundle-kubeflow#956]
### Context

Explore the implementation needed for https://warthogs.atlassian.net/browse/KF-5658.

### What needs to get done

Explore how the implementation needed can be achieved in order to be able then to write a how-to guide

### Definition of Done

Exploration has been done and findings are documented in the issue.

**Comment by kimwnasptd** [comment]
We'll start directly by implementing the terraform modules for each charm repo, instead of this exploration task

**Comment by kimwnasptd** [comment]
^^
