### ISSUE TITLE
`charming-actions/upload-charm` action is uploading images incorrectly and affecting charms' functionality

### ISSUE THREAD

**Issue by DnPlas** [canonical/bundle-kubeflow#962]
### Bug Description

It appears that https://github.com/canonical/charming-actions/issues/139 is affecting some charms' functionality:

* https://github.com/canonical/envoy-operator/issues/114
* https://github.com/canonical/kubeflow-dashboard-operator/issues/194

We need to investigate how this issue is affecting us:

* How images get attached to charms?
* How is this affecting tracks?
* How can we be sure about which image is attached to a certain charm revision?

### To Reproduce

https://github.com/canonical/charming-actions/issues/139 contains all the necessary information.

### Environment

CI environment.

### Relevant Log Output

```shell
https://github.com/canonical/charming-actions/issues/139 contains all the necessary information.
```

**Comment by orfeas-k** [comment]
Doing some investigation after https://github.com/canonical/charming-actions/issues/139#issuecomment-2208781283 comment where they suggest that this change took place back in November 2023, I think I 've found another place where this has bitten us (and probably there is more)

#### Kserve-controller
Looking at repo's [releases](https://github.com/canonical/kserve-operators/releases), I see the following:

Revision 561
> resources:
> 
> - kube-rbac-proxy-image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
> resource-revision: 441
> - kserve-controller-image: charmedkubeflow/kserve-controller:0.13.0-e151c86
> resource-revision: 446

Revision 558
> resources:
> 
> - kube-rbac-proxy-image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
> resource-revision: 441
> - kserve-controller-image: kserve/kserve-controller:v0.13.0
> resource-revision: 446

and taking a look at the CI runs: 
* https://github.com/canonical/kserve-operators/actions/runs/9581873366/job/26420750570#step:5:101
* https://github.com/canonical/kserve-operators/actions/runs/9582230062/job/26421955811#step:5:63

they have images with different hash but they are being released with the same resource-revision.

**Comment by DnPlas** [comment]
It looks like this issue is also affecting the PR tracks and the "stable" tracks (e.g. `track/2.0` -> `2.0/stable`)
