### ISSUE TITLE
Update public documentation with juju 3.4

### ISSUE THREAD

**Issue by DnPlas** [canonical/bundle-kubeflow#965]
### Context

Based on the discussion in https://github.com/canonical/bundle-kubeflow/issues/940, we want to make sure the public documentation for Charmed Kubeflow shows the right version of juju to use.

### What needs to get done

1. Go into charmed-kubeflow.io and check for places where juju 3 is mentioned
2. Make sure each entry mentions the support for juju 3.4 for CKF 1.8
3. Remove any traces of juju 3.1 and/or 3.5 

### Definition of Done

Public documentation in charmed-kubeflow.io does not make any reference to an unsupported version of juju.

**Comment by DnPlas** [comment]
The most important guides that should be updated are:

* [Upgrade 1.7 -> 1.8](https://charmed-kubeflow.io/docs/upgrade-17-18)
* [Get started](https://charmed-kubeflow.io/docs/get-started-with-charmed-kubeflow)

**Comment by orfeas-k** [comment]
Updated the above plus:
* [Deploy Charmed Kubeflow to EKS | Documentation | Charmed Kubeflow](https://charmed-kubeflow.io/docs/deploy-charmed-kubeflow-to-eks)  
* [Deploy Charmed Kubeflow to AKS | Documentation | Charmed Kubeflow](https://charmed-kubeflow.io/docs/deploy-charmed-kubeflow-to-aks)
