### ISSUE TITLE
Update the install guide for CKF 1.9

### ISSUE THREAD

**Issue by NohaIhab** [canonical/bundle-kubeflow#972]
### Context

As part of the 1.9 release epic, our documentation needs to be updated to work with the new release version and dependencies versions.

### What needs to get done

Update the [install guide](https://discourse.charmhub.io/t/how-to-install-charmed-kubeflow-on-kubernetes/3670) for CKF 1.9/stable release

### Definition of Done

The install guide is updated for 1.9/stable

**Comment by DnPlas** [comment]
This item was completed by @mvlassis in https://charmed-kubeflow.io/docs/install.
