### ISSUE TITLE
Write the how-to guide for Blob storage integration

### ISSUE THREAD

**Issue by NohaIhab** [canonical/bundle-kubeflow#974]
### Context

Users use Kubeflow Namespace together with Azure Blob Storage (on AKS and MicroK8s). We will improve their experience, by providing a how-to guide which enables them to quickly do it, without any hassle.

### What needs to get done

Write the Blob storage integration how-to guide in discourse to meet the acceptance criteria:

- As a user, I can connect with Azure Blob Storage from Kubeflow Notebook and access artefacts stored there. 
- As a user, I know what kind of artefacts can be stored in Azure blob storage (and where I could learn more about it through linking).
- As a user, I know what kind of deployment can benefit from such an integration.
- As a user, I can read which versions of Kubeflow can be used for such an integration.
- As a user, I am informed which type of  storage account can be used.
- As a user, I can read about the possible constraints (e.g., Azure blob storage works only on Azure).
- As a user, I am informed on how to access data from Azure blob storage using Kubeflow.

### Definition of Done

How-to guide is approved and published on our website

**Comment by mvlassis** [comment]
The guide has been released and has been published [in Discourse](https://discourse.charmhub.io/t/integrating-azure-blob-storage-with-charmed-kubeflow/14836).
