### ISSUE TITLE
Write the how-to guide for GPU spot instances on Azure

### ISSUE THREAD

**Issue by NohaIhab** [canonical/bundle-kubeflow#975]
### Context

Spot instances are an easy way to access extra computing without paying for it on a monthly basis - they are especially used for ML training. Kubeflow will access them in order to accelerate training.
This task is to write a how-to guide for using GPU spot instances on Azure with Charmed Kubeflow.

### What needs to get done

Write the how-to guide based on the exploration done in #954

### Definition of Done

How-to guide is approved and published

**Comment by DnPlas** [comment]
Guide has been published [here](https://charmed-kubeflow.io/docs/aks-spot)
