### ISSUE TITLE
Create charmhub tracks for CKF 1.9 charms

### ISSUE THREAD

**Issue by orfeas-k** [canonical/bundle-kubeflow#978]
### Context

Create tracks in charmhub for charms corresponding to versions used in 1.9. Context from this issue can help e.g for katib charms we need 0.17 track. For context on versions, take a look at https://github.com/canonical/bundle-kubeflow/issues/900.

### What needs to get done

Described above

### Definition of Done

All charms have a track corresponding to its 1.9 version.

**Comment by DnPlas** [comment]
All charms should have the required tracks by now. This can be checked comparing the expected version from https://github.com/canonical/bundle-kubeflow/issues/900 and the output of `charmcraft status <charm>`.
