### ISSUE TITLE
Cut branches for CKF 1.9 charms 

### ISSUE THREAD

**Issue by orfeas-k** [canonical/bundle-kubeflow#979]
### Context

Each repository should have a `track/version` branch corresponding to its 1.9 version (ref https://github.com/canonical/bundle-kubeflow/issues/900). This should be done after https://github.com/canonical/bundle-kubeflow/issues/978 so that charms are automatically published to `version/edge` channel.

### What needs to get done

Described above

### Definition of Done

There is a branch in each charm repo corresponding to its 1.9 version

**Comment by DnPlas** [comment]
All branches are now in place:

```

argo-operators → track/3.4

knative-operators → track/1.12

kserve-operators → track/0.13

minio → track/ckf-1.9

training-operator → track/1.8

katib-operators → track/0.17

notebook-operators → track/1.9

kubeflow-roles → track/1.9

envoy → track/2.2

admission-webhook → track/1.9

kubeflow-dashboard → track/1.9

kubeflow-profiles → track/1.9

tensoboards-operators → track/1.9

mlmd → track/ckf-1.9

oidc-gatekeeper → track/ckf-1.9

kubeflow/volumes → track/1.9

kfp-operators - track/2.2

metacontroller-operator - track/3.0
```

No further action is required.
