### ISSUE TITLE
Explore and identify cryptographic libraries in charms

### ISSUE THREAD

**Issue by DnPlas** [canonical/bundle-kubeflow#995]
### Context
Look through all the Charms to identify cryptographic libraries

### What needs to get done
Look through all the Charms to identify cryptographic libraries. We need to define
* What libraries we use, for cryptographic tasks
* What are the algorithms for each generated artifact

### Definition of Done
We have documented the above

**Comment by orfeas-k** [comment]
We should first understand where the following take place in our charms:
- Encryption / Decryption
- Hashing
- Digital signatures

and then we could figure out what are the exact libraries being used.

**Comment by mvlassis** [comment]
I updated the formatting in Orfeas' comment, added a few more explanations, and add the following information related to the upstream components:

### Upstream
#### Argo Workflows
The default configuration of the Argo Server is using  `TLS v1.2` by default, as explained in [the documentation](https://argo-workflows.readthedocs.io/en/latest/tls/#encrypted).
#### Dex
If dex's builtin connector is used, a static configuration file that stores the username (the field's name is `email`) and a bcrypt hash of their password, as explained in [the documentation](https://dexidp.io/docs/connectors/local/).
#### Istio
As documented in [this comment](https://github.com/canonical/bundle-kubeflow/issues/1020#issuecomment-2393551743), I have found the following:
- `istiod` distributes an `X.509` certificate to every sidecar charm, in the following path: `/var/run/secrets/istio/root-cert.pem`. The signature used is `sha256WithRSAEncryption`.
- Istio tunnels communication between services (a client and a server) using [Envoy proxies](https://www.envoyproxy.io/), which in our case are the sidecar containers that are injected in each pod in the user's namespace.
- When a workload container (**client**) sends a request to another workload container (**server**):
    - Istio re-routes the outbound traffic to the client's sidecar.
    - The client's sidecar starts an mTLS handshake with the server's sidecar.
    - The 2 sidecars establish an mTLS connection, and Istio forwards the traffic from the client to the server.
    - The server sidecar authorizes the request, and forwards the traffic to the backend service through local TCP connections.
- The minimum version of TLS used is `TLSv1_2`. The cipher suites used for the mTLS connection are:
    - `ECDHE-ECDSA-AES256-GCM-SHA384`
    - `ECDHE-RSA-AES256-GCM-SHA384`
    - `ECDHE-ECDSA-AES128-GCM-SHA256`
    - `ECDHE-RSA-AES128-GCM-SHA256`
    - `AES256-GCM-SHA384`
    - `AES128-GCM-SHA256`
- Our charm's code in `istio-pilot` does not perform any additional actions when it comes to cryptography between the sidecars. 
- `istio-pilot` uses `CertHandler` to create a TLS certificate used by the Istio gateway service.
- `CertHandler` requires the `tls-certificates` library, seen [here](https://github.com/canonical/istio-operators/blob/fcc67bf51622ab181ac5eb2575c2277112105f65/charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py#L42-L57).

Main reference page: https://istio.io/latest/docs/concepts/security/#mutual-tls-authentication

**Comment by NohaIhab** [comment]
Good work @mvlassis and @orfeas-k 
I think we are now ready to write the documentation in #1050
